/**
 * Plugin Table Generator
 *
 * Generates TypeScript files for plugin-generated TailorDB tables.
 * These files can be imported by plugin executors to reference generated tables.
 */

import * as fs from "node:fs";
import * as path from "pathe";
import { logger, styles } from "#/cli/shared/logger";
import ml from "#/utils/multiline";
import type { PluginGeneratedTableInfo, PluginTableGenerationResult } from "#/plugin/manager";
import type { PluginGeneratedTable } from "#/plugin/types";

type FieldMetadata = {
  required?: boolean;
  index?: boolean;
  unique?: boolean;
  description?: string;
  allowedValues?: ReadonlyArray<{ value: string }>;
};

type FieldDefinition = {
  type?: string;
  _metadata?: FieldMetadata;
  metadata?: FieldMetadata;
};

function isFieldDefinition(value: unknown): value is FieldDefinition {
  return typeof value === "object" && value !== null;
}

/**
 * Generate TypeScript files for plugin-generated tables.
 * These files export the table definition and can be imported by executor files.
 * @param tables - Array of plugin table information
 * @param outputDir - Base output directory (e.g., .tailor)
 * @returns Generation result with file paths
 */
export function generatePluginTableFiles(
  tables: ReadonlyArray<PluginGeneratedTableInfo>,
  outputDir: string,
): PluginTableGenerationResult {
  const tableFilePaths = new Map<string, string>();
  const generatedFiles: string[] = [];

  if (tables.length === 0) {
    return { tableFilePaths, generatedFiles };
  }

  const seenTableNames = new Map<string, PluginGeneratedTableInfo>();

  for (const info of tables) {
    const existing = seenTableNames.get(info.table.name);
    if (existing) {
      throw new Error(
        `Duplicate plugin-generated table name "${info.table.name}" detected. ` +
          `First: plugin "${existing.pluginId}" (kind: "${existing.kind}", source: "${existing.sourceTableName}"), ` +
          `Second: plugin "${info.pluginId}" (kind: "${info.kind}", source: "${info.sourceTableName}"). ` +
          `Plugin-generated table names must be unique.`,
      );
    }
    seenTableNames.set(info.table.name, info);

    const pluginDir = sanitizePluginId(info.pluginId);
    const tableOutputDir = path.join(outputDir, pluginDir, "types");
    fs.mkdirSync(tableOutputDir, { recursive: true });

    const fileName = `${toKebabCase(info.table.name)}.ts`;
    const filePath = path.join(tableOutputDir, fileName);
    const content = generateTableFileContent(info);

    fs.writeFileSync(filePath, content);
    generatedFiles.push(filePath);

    // Store relative path from outputDir for import resolution
    const relativePath = path.relative(outputDir, filePath);
    tableFilePaths.set(info.table.name, relativePath);

    const displayPath = path.relative(process.cwd(), filePath);
    logger.log(
      `  Plugin Table File: ${styles.success(displayPath)} (${styles.dim(info.kind)}) from plugin ${styles.info(info.pluginId)}`,
    );
  }

  return { tableFilePaths, generatedFiles };
}

/**
 * Generate TypeScript file content for a single table.
 * @param info - Plugin table information
 * @returns TypeScript source code
 */
function generateTableFileContent(info: PluginGeneratedTableInfo): string {
  const { table, pluginId, sourceTableName, kind } = info;
  const variableName = toCamelCase(table.name);
  const fieldsCode = generateFieldsCode(table);

  return ml /* ts */ `
    /**
     * Auto-generated table by plugin: ${pluginId}
     * Source: ${sourceTableName}
     * Kind: ${kind}
     *
     * DO NOT EDIT - This file is generated by @tailor-platform/sdk
     */
    import { db } from "@tailor-platform/sdk";

    export const ${variableName} = db.table(${JSON.stringify(table.name)}, ${fieldsCode});

    export type ${table.name} = typeof ${variableName};
  `;
}

/**
 * Generate TypeScript code for field definitions.
 * This creates a simplified version of the table's fields.
 * @param table - TailorDB table
 * @returns TypeScript code for fields object
 */
function generateFieldsCode(table: PluginGeneratedTable): string {
  const fieldEntries: string[] = [];

  for (const [fieldName, field] of Object.entries(table.fields)) {
    if (!isFieldDefinition(field)) continue;
    const fieldCode = generateSingleFieldCode(field);
    if (fieldCode) {
      fieldEntries.push(`  ${fieldName}: ${fieldCode}`);
    }
  }

  return `{\n${fieldEntries.join(",\n")},\n}`;
}

/**
 * Map from TailorDB table to SDK method name.
 */
const typeToMethodMap: Record<string, string> = {
  string: "string",
  integer: "int",
  float: "float",
  boolean: "bool",
  uuid: "uuid",
  datetime: "datetime",
  date: "date",
  time: "time",
  enum: "enum",
  nested: "nested",
};

/**
 * Generate TypeScript code for a single field definition.
 * @param field - Field definition object
 * @returns TypeScript code for the field
 */
function generateSingleFieldCode(field: FieldDefinition): string | null {
  const fieldType = field.type;
  if (!fieldType) {
    return null;
  }

  const method = typeToMethodMap[fieldType] ?? fieldType;
  const metadata: FieldMetadata = field._metadata ?? field.metadata ?? {};

  // Build options object
  const optionParts: string[] = [];
  if (metadata.required === false) {
    optionParts.push("optional: true");
  }

  const optionsArg = optionParts.length > 0 ? `{ ${optionParts.join(", ")} }` : "";

  // Handle enum type with values
  if (fieldType === "enum") {
    // Extract enum values from allowedValues array
    const allowedValues = metadata.allowedValues;
    let enumValues: string[] = [];
    if (Array.isArray(allowedValues)) {
      enumValues = allowedValues.map((v: { value: string }) => v.value);
    }

    let code = `db.enum(${JSON.stringify(enumValues)}${optionsArg ? `, ${optionsArg}` : ""})`;
    if (metadata.index) {
      code += ".index()";
    }
    if (metadata.unique) {
      code += ".unique()";
    }
    if (metadata.description) {
      code += `.description(${JSON.stringify(metadata.description)})`;
    }
    return code;
  }

  // Build method chain for other types
  let code = `db.${method}(${optionsArg})`;

  // Add index if present
  if (metadata.index) {
    code += ".index()";
  }

  // Add unique if present
  if (metadata.unique) {
    code += ".unique()";
  }

  // Add description if present
  if (metadata.description) {
    code += `.description(${JSON.stringify(metadata.description)})`;
  }

  return code;
}

/**
 * Convert plugin ID to safe directory name.
 * @param pluginId - Plugin identifier (e.g., "@tailor-platform/change-history")
 * @returns Safe directory name (e.g., "tailor-platform-change-history")
 */
function sanitizePluginId(pluginId: string): string {
  return pluginId.replace(/^@/, "").replace(/\//g, "-");
}

/**
 * Convert string to kebab-case.
 * @param str - Input string
 * @returns kebab-case string
 */
function toKebabCase(str: string): string {
  return str
    .replace(/([a-z])([A-Z])/g, "$1-$2")
    .replace(/[\s_]+/g, "-")
    .toLowerCase();
}

/**
 * Convert string to camelCase.
 * @param str - Input string
 * @returns camelCase string
 */
function toCamelCase(str: string): string {
  const result = str.replace(/[-_\s]+(.)?/g, (_, c) => (c ? c.toUpperCase() : ""));
  return result.charAt(0).toLowerCase() + result.slice(1);
}
