// @generated by protoc-gen-es v2.6.3
// @generated from file tailor/v1/ai.proto (package tailor.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { AiService, AiTask } from "./ai_resource_pb";
import type { PageDirection } from "./resource_pb";

/**
 * Describes the file tailor/v1/ai.proto.
 */
export declare const file_tailor_v1_ai: GenFile;

/**
 * @generated from message tailor.v1.CreateAiServiceRequest
 */
export declare type CreateAiServiceRequest = Message<"tailor.v1.CreateAiServiceRequest"> & {
  /**
   * @generated from field: string workspace_id = 1;
   */
  workspaceId: string;

  /**
   * @generated from field: string namespace_name = 2;
   */
  namespaceName: string;
};

/**
 * Describes the message tailor.v1.CreateAiServiceRequest.
 * Use `create(CreateAiServiceRequestSchema)` to create a new message.
 */
export declare const CreateAiServiceRequestSchema: GenMessage<CreateAiServiceRequest>;

/**
 * @generated from message tailor.v1.CreateAiServiceResponse
 */
export declare type CreateAiServiceResponse = Message<"tailor.v1.CreateAiServiceResponse"> & {
  /**
   * @generated from field: tailor.v1.AiService ai_service = 1;
   */
  aiService?: AiService;
};

/**
 * Describes the message tailor.v1.CreateAiServiceResponse.
 * Use `create(CreateAiServiceResponseSchema)` to create a new message.
 */
export declare const CreateAiServiceResponseSchema: GenMessage<CreateAiServiceResponse>;

/**
 * @generated from message tailor.v1.ListAiServicesRequest
 */
export declare type ListAiServicesRequest = Message<"tailor.v1.ListAiServicesRequest"> & {
  /**
   * @generated from field: string workspace_id = 1;
   */
  workspaceId: string;

  /**
   * @generated from field: string page_token = 2;
   */
  pageToken: string;

  /**
   * @generated from field: uint32 page_size = 3;
   */
  pageSize: number;

  /**
   * @generated from field: tailor.v1.PageDirection page_direction = 4;
   */
  pageDirection: PageDirection;
};

/**
 * Describes the message tailor.v1.ListAiServicesRequest.
 * Use `create(ListAiServicesRequestSchema)` to create a new message.
 */
export declare const ListAiServicesRequestSchema: GenMessage<ListAiServicesRequest>;

/**
 * @generated from message tailor.v1.ListAiServicesResponse
 */
export declare type ListAiServicesResponse = Message<"tailor.v1.ListAiServicesResponse"> & {
  /**
   * @generated from field: repeated tailor.v1.AiService ai_services = 1;
   */
  aiServices: AiService[];

  /**
   * @generated from field: string next_page_token = 2;
   */
  nextPageToken: string;

  /**
   * @generated from field: int64 total_count = 3;
   */
  totalCount: bigint;
};

/**
 * Describes the message tailor.v1.ListAiServicesResponse.
 * Use `create(ListAiServicesResponseSchema)` to create a new message.
 */
export declare const ListAiServicesResponseSchema: GenMessage<ListAiServicesResponse>;

/**
 * @generated from message tailor.v1.DeleteAiServiceRequest
 */
export declare type DeleteAiServiceRequest = Message<"tailor.v1.DeleteAiServiceRequest"> & {
  /**
   * @generated from field: string workspace_id = 1;
   */
  workspaceId: string;

  /**
   * @generated from field: string namespace_name = 2;
   */
  namespaceName: string;
};

/**
 * Describes the message tailor.v1.DeleteAiServiceRequest.
 * Use `create(DeleteAiServiceRequestSchema)` to create a new message.
 */
export declare const DeleteAiServiceRequestSchema: GenMessage<DeleteAiServiceRequest>;

/**
 * @generated from message tailor.v1.DeleteAiServiceResponse
 */
export declare type DeleteAiServiceResponse = Message<"tailor.v1.DeleteAiServiceResponse"> & {
};

/**
 * Describes the message tailor.v1.DeleteAiServiceResponse.
 * Use `create(DeleteAiServiceResponseSchema)` to create a new message.
 */
export declare const DeleteAiServiceResponseSchema: GenMessage<DeleteAiServiceResponse>;

/**
 * @generated from message tailor.v1.GetAiServiceRequest
 */
export declare type GetAiServiceRequest = Message<"tailor.v1.GetAiServiceRequest"> & {
  /**
   * @generated from field: string workspace_id = 1;
   */
  workspaceId: string;

  /**
   * @generated from field: string namespace_name = 2;
   */
  namespaceName: string;
};

/**
 * Describes the message tailor.v1.GetAiServiceRequest.
 * Use `create(GetAiServiceRequestSchema)` to create a new message.
 */
export declare const GetAiServiceRequestSchema: GenMessage<GetAiServiceRequest>;

/**
 * @generated from message tailor.v1.GetAiServiceResponse
 */
export declare type GetAiServiceResponse = Message<"tailor.v1.GetAiServiceResponse"> & {
  /**
   * @generated from field: tailor.v1.AiService ai_service = 1;
   */
  aiService?: AiService;
};

/**
 * Describes the message tailor.v1.GetAiServiceResponse.
 * Use `create(GetAiServiceResponseSchema)` to create a new message.
 */
export declare const GetAiServiceResponseSchema: GenMessage<GetAiServiceResponse>;

/**
 * @generated from message tailor.v1.CreateAiTaskRequest
 */
export declare type CreateAiTaskRequest = Message<"tailor.v1.CreateAiTaskRequest"> & {
  /**
   * @generated from field: string workspace_id = 1;
   */
  workspaceId: string;

  /**
   * @generated from field: string namespace_name = 2;
   */
  namespaceName: string;

  /**
   * @generated from field: tailor.v1.AiTask task = 3;
   */
  task?: AiTask;
};

/**
 * Describes the message tailor.v1.CreateAiTaskRequest.
 * Use `create(CreateAiTaskRequestSchema)` to create a new message.
 */
export declare const CreateAiTaskRequestSchema: GenMessage<CreateAiTaskRequest>;

/**
 * @generated from message tailor.v1.CreateAiTaskResponse
 */
export declare type CreateAiTaskResponse = Message<"tailor.v1.CreateAiTaskResponse"> & {
  /**
   * @generated from field: tailor.v1.AiTask task = 1;
   */
  task?: AiTask;
};

/**
 * Describes the message tailor.v1.CreateAiTaskResponse.
 * Use `create(CreateAiTaskResponseSchema)` to create a new message.
 */
export declare const CreateAiTaskResponseSchema: GenMessage<CreateAiTaskResponse>;

/**
 * @generated from message tailor.v1.ListAiTasksRequest
 */
export declare type ListAiTasksRequest = Message<"tailor.v1.ListAiTasksRequest"> & {
  /**
   * @generated from field: string workspace_id = 1;
   */
  workspaceId: string;

  /**
   * @generated from field: string namespace_name = 2;
   */
  namespaceName: string;

  /**
   * @generated from field: string page_token = 3;
   */
  pageToken: string;

  /**
   * @generated from field: uint32 page_size = 4;
   */
  pageSize: number;

  /**
   * @generated from field: tailor.v1.PageDirection page_direction = 5;
   */
  pageDirection: PageDirection;
};

/**
 * Describes the message tailor.v1.ListAiTasksRequest.
 * Use `create(ListAiTasksRequestSchema)` to create a new message.
 */
export declare const ListAiTasksRequestSchema: GenMessage<ListAiTasksRequest>;

/**
 * @generated from message tailor.v1.ListAiTasksResponse
 */
export declare type ListAiTasksResponse = Message<"tailor.v1.ListAiTasksResponse"> & {
  /**
   * @generated from field: repeated tailor.v1.AiTask tasks = 1;
   */
  tasks: AiTask[];

  /**
   * @generated from field: string next_page_token = 2;
   */
  nextPageToken: string;

  /**
   * @generated from field: int64 total_count = 3;
   */
  totalCount: bigint;
};

/**
 * Describes the message tailor.v1.ListAiTasksResponse.
 * Use `create(ListAiTasksResponseSchema)` to create a new message.
 */
export declare const ListAiTasksResponseSchema: GenMessage<ListAiTasksResponse>;

/**
 * @generated from message tailor.v1.GetAiTaskRequest
 */
export declare type GetAiTaskRequest = Message<"tailor.v1.GetAiTaskRequest"> & {
  /**
   * @generated from field: string workspace_id = 1;
   */
  workspaceId: string;

  /**
   * @generated from field: string namespace_name = 2;
   */
  namespaceName: string;

  /**
   * @generated from field: string task_name = 3;
   */
  taskName: string;
};

/**
 * Describes the message tailor.v1.GetAiTaskRequest.
 * Use `create(GetAiTaskRequestSchema)` to create a new message.
 */
export declare const GetAiTaskRequestSchema: GenMessage<GetAiTaskRequest>;

/**
 * @generated from message tailor.v1.GetAiTaskResponse
 */
export declare type GetAiTaskResponse = Message<"tailor.v1.GetAiTaskResponse"> & {
  /**
   * @generated from field: tailor.v1.AiTask task = 1;
   */
  task?: AiTask;
};

/**
 * Describes the message tailor.v1.GetAiTaskResponse.
 * Use `create(GetAiTaskResponseSchema)` to create a new message.
 */
export declare const GetAiTaskResponseSchema: GenMessage<GetAiTaskResponse>;

/**
 * @generated from message tailor.v1.UpdateAiTaskRequest
 */
export declare type UpdateAiTaskRequest = Message<"tailor.v1.UpdateAiTaskRequest"> & {
  /**
   * @generated from field: string workspace_id = 1;
   */
  workspaceId: string;

  /**
   * @generated from field: string namespace_name = 2;
   */
  namespaceName: string;

  /**
   * @generated from field: string task_name = 3;
   */
  taskName: string;

  /**
   * @generated from field: tailor.v1.AiTask task = 4;
   */
  task?: AiTask;
};

/**
 * Describes the message tailor.v1.UpdateAiTaskRequest.
 * Use `create(UpdateAiTaskRequestSchema)` to create a new message.
 */
export declare const UpdateAiTaskRequestSchema: GenMessage<UpdateAiTaskRequest>;

/**
 * @generated from message tailor.v1.UpdateAiTaskResponse
 */
export declare type UpdateAiTaskResponse = Message<"tailor.v1.UpdateAiTaskResponse"> & {
  /**
   * @generated from field: tailor.v1.AiTask task = 1;
   */
  task?: AiTask;
};

/**
 * Describes the message tailor.v1.UpdateAiTaskResponse.
 * Use `create(UpdateAiTaskResponseSchema)` to create a new message.
 */
export declare const UpdateAiTaskResponseSchema: GenMessage<UpdateAiTaskResponse>;

/**
 * @generated from message tailor.v1.DeleteAiTaskRequest
 */
export declare type DeleteAiTaskRequest = Message<"tailor.v1.DeleteAiTaskRequest"> & {
  /**
   * @generated from field: string workspace_id = 1;
   */
  workspaceId: string;

  /**
   * @generated from field: string namespace_name = 2;
   */
  namespaceName: string;

  /**
   * @generated from field: string task_name = 3;
   */
  taskName: string;
};

/**
 * Describes the message tailor.v1.DeleteAiTaskRequest.
 * Use `create(DeleteAiTaskRequestSchema)` to create a new message.
 */
export declare const DeleteAiTaskRequestSchema: GenMessage<DeleteAiTaskRequest>;

/**
 * @generated from message tailor.v1.DeleteAiTaskResponse
 */
export declare type DeleteAiTaskResponse = Message<"tailor.v1.DeleteAiTaskResponse"> & {
};

/**
 * Describes the message tailor.v1.DeleteAiTaskResponse.
 * Use `create(DeleteAiTaskResponseSchema)` to create a new message.
 */
export declare const DeleteAiTaskResponseSchema: GenMessage<DeleteAiTaskResponse>;

