// @generated by protoc-gen-es v2.6.3
// @generated from file tailor/v1/application.proto (package tailor.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Application, ApplicationSchemaUpdateAttempt, Subgraph } from "./application_resource_pb";
import type { FieldMask, Timestamp } from "@bufbuild/protobuf/wkt";
import type { PageDirection } from "./resource_pb";

/**
 * Describes the file tailor/v1/application.proto.
 */
export declare const file_tailor_v1_application: GenFile;

/**
 * @generated from message tailor.v1.CreateApplicationRequest
 */
export declare type CreateApplicationRequest = Message<"tailor.v1.CreateApplicationRequest"> & {
  /**
   * @generated from field: string workspace_id = 1;
   */
  workspaceId: string;

  /**
   * @generated from field: string application_name = 2;
   */
  applicationName: string;

  /**
   * optional
   *
   * @generated from field: string auth_namespace = 3;
   */
  authNamespace: string;

  /**
   * optional
   *
   * @generated from field: string auth_idp_config_name = 4;
   */
  authIdpConfigName: string;

  /**
   * @generated from field: repeated string cors = 5;
   */
  cors: string[];

  /**
   * @generated from field: repeated tailor.v1.Subgraph subgraphs = 6;
   */
  subgraphs: Subgraph[];

  /**
   * @generated from field: repeated string allowed_ip_addresses = 7;
   */
  allowedIpAddresses: string[];

  /**
   * @generated from field: bool disable_introspection = 8;
   */
  disableIntrospection: boolean;

  /**
   * @generated from field: bool disabled = 9;
   */
  disabled: boolean;
};

/**
 * Describes the message tailor.v1.CreateApplicationRequest.
 * Use `create(CreateApplicationRequestSchema)` to create a new message.
 */
export declare const CreateApplicationRequestSchema: GenMessage<CreateApplicationRequest>;

/**
 * @generated from message tailor.v1.CreateApplicationResponse
 */
export declare type CreateApplicationResponse = Message<"tailor.v1.CreateApplicationResponse"> & {
  /**
   * @generated from field: tailor.v1.Application application = 1;
   */
  application?: Application;
};

/**
 * Describes the message tailor.v1.CreateApplicationResponse.
 * Use `create(CreateApplicationResponseSchema)` to create a new message.
 */
export declare const CreateApplicationResponseSchema: GenMessage<CreateApplicationResponse>;

/**
 * @generated from message tailor.v1.UpdateApplicationRequest
 */
export declare type UpdateApplicationRequest = Message<"tailor.v1.UpdateApplicationRequest"> & {
  /**
   * @generated from field: string workspace_id = 1;
   */
  workspaceId: string;

  /**
   * @generated from field: string application_name = 2;
   */
  applicationName: string;

  /**
   * optional
   *
   * @generated from field: string auth_namespace = 3;
   */
  authNamespace: string;

  /**
   * optional
   *
   * @generated from field: string auth_idp_config_name = 4;
   */
  authIdpConfigName: string;

  /**
   * @generated from field: repeated string cors = 5;
   */
  cors: string[];

  /**
   * @generated from field: repeated tailor.v1.Subgraph subgraphs = 6;
   */
  subgraphs: Subgraph[];

  /**
   * @generated from field: repeated string allowed_ip_addresses = 7;
   */
  allowedIpAddresses: string[];

  /**
   * @generated from field: bool disable_introspection = 8;
   */
  disableIntrospection: boolean;

  /**
   * @generated from field: bool disabled = 9;
   */
  disabled: boolean;

  /**
   * @generated from field: google.protobuf.FieldMask update_mask = 100;
   */
  updateMask?: FieldMask;
};

/**
 * Describes the message tailor.v1.UpdateApplicationRequest.
 * Use `create(UpdateApplicationRequestSchema)` to create a new message.
 */
export declare const UpdateApplicationRequestSchema: GenMessage<UpdateApplicationRequest>;

/**
 * @generated from message tailor.v1.UpdateApplicationResponse
 */
export declare type UpdateApplicationResponse = Message<"tailor.v1.UpdateApplicationResponse"> & {
  /**
   * @generated from field: tailor.v1.Application application = 1;
   */
  application?: Application;
};

/**
 * Describes the message tailor.v1.UpdateApplicationResponse.
 * Use `create(UpdateApplicationResponseSchema)` to create a new message.
 */
export declare const UpdateApplicationResponseSchema: GenMessage<UpdateApplicationResponse>;

/**
 * @generated from message tailor.v1.DeleteApplicationRequest
 */
export declare type DeleteApplicationRequest = Message<"tailor.v1.DeleteApplicationRequest"> & {
  /**
   * @generated from field: string workspace_id = 1;
   */
  workspaceId: string;

  /**
   * @generated from field: string application_name = 2;
   */
  applicationName: string;
};

/**
 * Describes the message tailor.v1.DeleteApplicationRequest.
 * Use `create(DeleteApplicationRequestSchema)` to create a new message.
 */
export declare const DeleteApplicationRequestSchema: GenMessage<DeleteApplicationRequest>;

/**
 * @generated from message tailor.v1.DeleteApplicationResponse
 */
export declare type DeleteApplicationResponse = Message<"tailor.v1.DeleteApplicationResponse"> & {
};

/**
 * Describes the message tailor.v1.DeleteApplicationResponse.
 * Use `create(DeleteApplicationResponseSchema)` to create a new message.
 */
export declare const DeleteApplicationResponseSchema: GenMessage<DeleteApplicationResponse>;

/**
 * @generated from message tailor.v1.ListApplicationsRequest
 */
export declare type ListApplicationsRequest = Message<"tailor.v1.ListApplicationsRequest"> & {
  /**
   * @generated from field: string workspace_id = 1;
   */
  workspaceId: string;

  /**
   * @generated from field: string page_token = 2;
   */
  pageToken: string;

  /**
   * @generated from field: uint32 page_size = 3;
   */
  pageSize: number;

  /**
   * @generated from field: tailor.v1.PageDirection page_direction = 4;
   */
  pageDirection: PageDirection;
};

/**
 * Describes the message tailor.v1.ListApplicationsRequest.
 * Use `create(ListApplicationsRequestSchema)` to create a new message.
 */
export declare const ListApplicationsRequestSchema: GenMessage<ListApplicationsRequest>;

/**
 * @generated from message tailor.v1.ListApplicationsResponse
 */
export declare type ListApplicationsResponse = Message<"tailor.v1.ListApplicationsResponse"> & {
  /**
   * @generated from field: repeated tailor.v1.Application applications = 1;
   */
  applications: Application[];

  /**
   * @generated from field: string next_page_token = 2;
   */
  nextPageToken: string;

  /**
   * @generated from field: int64 total_count = 3;
   */
  totalCount: bigint;
};

/**
 * Describes the message tailor.v1.ListApplicationsResponse.
 * Use `create(ListApplicationsResponseSchema)` to create a new message.
 */
export declare const ListApplicationsResponseSchema: GenMessage<ListApplicationsResponse>;

/**
 * @generated from message tailor.v1.GetApplicationRequest
 */
export declare type GetApplicationRequest = Message<"tailor.v1.GetApplicationRequest"> & {
  /**
   * @generated from field: string workspace_id = 1;
   */
  workspaceId: string;

  /**
   * @generated from field: string application_name = 2;
   */
  applicationName: string;
};

/**
 * Describes the message tailor.v1.GetApplicationRequest.
 * Use `create(GetApplicationRequestSchema)` to create a new message.
 */
export declare const GetApplicationRequestSchema: GenMessage<GetApplicationRequest>;

/**
 * @generated from message tailor.v1.GetApplicationResponse
 */
export declare type GetApplicationResponse = Message<"tailor.v1.GetApplicationResponse"> & {
  /**
   * @generated from field: tailor.v1.Application application = 1;
   */
  application?: Application;
};

/**
 * Describes the message tailor.v1.GetApplicationResponse.
 * Use `create(GetApplicationResponseSchema)` to create a new message.
 */
export declare const GetApplicationResponseSchema: GenMessage<GetApplicationResponse>;

/**
 * @generated from message tailor.v1.GetApplicationSchemaHealthRequest
 */
export declare type GetApplicationSchemaHealthRequest = Message<"tailor.v1.GetApplicationSchemaHealthRequest"> & {
  /**
   * @generated from field: string workspace_id = 1;
   */
  workspaceId: string;

  /**
   * @generated from field: string application_name = 2;
   */
  applicationName: string;
};

/**
 * Describes the message tailor.v1.GetApplicationSchemaHealthRequest.
 * Use `create(GetApplicationSchemaHealthRequestSchema)` to create a new message.
 */
export declare const GetApplicationSchemaHealthRequestSchema: GenMessage<GetApplicationSchemaHealthRequest>;

/**
 * @generated from message tailor.v1.GetApplicationSchemaHealthResponse
 */
export declare type GetApplicationSchemaHealthResponse = Message<"tailor.v1.GetApplicationSchemaHealthResponse"> & {
  /**
   * @generated from field: tailor.v1.GetApplicationSchemaHealthResponse.ApplicationSchemaHealthStatus status = 1;
   */
  status: GetApplicationSchemaHealthResponse_ApplicationSchemaHealthStatus;

  /**
   * The timestamp of when the current serving schema updated.
   *
   * @generated from field: google.protobuf.Timestamp current_serving_schema_update_time = 2;
   */
  currentServingSchemaUpdateTime?: Timestamp;

  /**
   * @generated from field: tailor.v1.ApplicationSchemaUpdateAttempt last_schema_update_attempt = 3;
   */
  lastSchemaUpdateAttempt?: ApplicationSchemaUpdateAttempt;
};

/**
 * Describes the message tailor.v1.GetApplicationSchemaHealthResponse.
 * Use `create(GetApplicationSchemaHealthResponseSchema)` to create a new message.
 */
export declare const GetApplicationSchemaHealthResponseSchema: GenMessage<GetApplicationSchemaHealthResponse>;

/**
 * @generated from enum tailor.v1.GetApplicationSchemaHealthResponse.ApplicationSchemaHealthStatus
 */
export enum GetApplicationSchemaHealthResponse_ApplicationSchemaHealthStatus {
  /**
   * @generated from enum value: APPLICATION_SCHEMA_HEALTH_STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: APPLICATION_SCHEMA_HEALTH_STATUS_OK = 1;
   */
  OK = 1,

  /**
   * @generated from enum value: APPLICATION_SCHEMA_HEALTH_STATUS_COMPOSITION_ERROR = 2;
   */
  COMPOSITION_ERROR = 2,
}

/**
 * Describes the enum tailor.v1.GetApplicationSchemaHealthResponse.ApplicationSchemaHealthStatus.
 */
export declare const GetApplicationSchemaHealthResponse_ApplicationSchemaHealthStatusSchema: GenEnum<GetApplicationSchemaHealthResponse_ApplicationSchemaHealthStatus>;

