// @generated by protoc-gen-es v2.6.3
// @generated from file tailor/v1/executor.proto (package tailor.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { JsonObject, Message } from "@bufbuild/protobuf";
import type { ExecutorExecutor, ExecutorIncomingWebhook, ExecutorJob, ExecutorJobAttempt } from "./executor_resource_pb";
import type { Filter, PageDirection } from "./resource_pb";

/**
 * Describes the file tailor/v1/executor.proto.
 */
export declare const file_tailor_v1_executor: GenFile;

/**
 * @generated from message tailor.v1.CreateExecutorExecutorRequest
 */
export declare type CreateExecutorExecutorRequest = Message<"tailor.v1.CreateExecutorExecutorRequest"> & {
  /**
   * @generated from field: string workspace_id = 1;
   */
  workspaceId: string;

  /**
   * @generated from field: tailor.v1.ExecutorExecutor executor = 2;
   */
  executor?: ExecutorExecutor;
};

/**
 * Describes the message tailor.v1.CreateExecutorExecutorRequest.
 * Use `create(CreateExecutorExecutorRequestSchema)` to create a new message.
 */
export declare const CreateExecutorExecutorRequestSchema: GenMessage<CreateExecutorExecutorRequest>;

/**
 * @generated from message tailor.v1.CreateExecutorExecutorResponse
 */
export declare type CreateExecutorExecutorResponse = Message<"tailor.v1.CreateExecutorExecutorResponse"> & {
  /**
   * @generated from field: tailor.v1.ExecutorExecutor executor = 1;
   */
  executor?: ExecutorExecutor;
};

/**
 * Describes the message tailor.v1.CreateExecutorExecutorResponse.
 * Use `create(CreateExecutorExecutorResponseSchema)` to create a new message.
 */
export declare const CreateExecutorExecutorResponseSchema: GenMessage<CreateExecutorExecutorResponse>;

/**
 * @generated from message tailor.v1.UpdateExecutorExecutorRequest
 */
export declare type UpdateExecutorExecutorRequest = Message<"tailor.v1.UpdateExecutorExecutorRequest"> & {
  /**
   * @generated from field: string workspace_id = 1;
   */
  workspaceId: string;

  /**
   * @generated from field: tailor.v1.ExecutorExecutor executor = 2;
   */
  executor?: ExecutorExecutor;
};

/**
 * Describes the message tailor.v1.UpdateExecutorExecutorRequest.
 * Use `create(UpdateExecutorExecutorRequestSchema)` to create a new message.
 */
export declare const UpdateExecutorExecutorRequestSchema: GenMessage<UpdateExecutorExecutorRequest>;

/**
 * @generated from message tailor.v1.UpdateExecutorExecutorResponse
 */
export declare type UpdateExecutorExecutorResponse = Message<"tailor.v1.UpdateExecutorExecutorResponse"> & {
  /**
   * @generated from field: tailor.v1.ExecutorExecutor executor = 1;
   */
  executor?: ExecutorExecutor;
};

/**
 * Describes the message tailor.v1.UpdateExecutorExecutorResponse.
 * Use `create(UpdateExecutorExecutorResponseSchema)` to create a new message.
 */
export declare const UpdateExecutorExecutorResponseSchema: GenMessage<UpdateExecutorExecutorResponse>;

/**
 * @generated from message tailor.v1.GetExecutorExecutorRequest
 */
export declare type GetExecutorExecutorRequest = Message<"tailor.v1.GetExecutorExecutorRequest"> & {
  /**
   * @generated from field: string workspace_id = 1;
   */
  workspaceId: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;
};

/**
 * Describes the message tailor.v1.GetExecutorExecutorRequest.
 * Use `create(GetExecutorExecutorRequestSchema)` to create a new message.
 */
export declare const GetExecutorExecutorRequestSchema: GenMessage<GetExecutorExecutorRequest>;

/**
 * @generated from message tailor.v1.GetExecutorExecutorResponse
 */
export declare type GetExecutorExecutorResponse = Message<"tailor.v1.GetExecutorExecutorResponse"> & {
  /**
   * @generated from field: tailor.v1.ExecutorExecutor executor = 1;
   */
  executor?: ExecutorExecutor;
};

/**
 * Describes the message tailor.v1.GetExecutorExecutorResponse.
 * Use `create(GetExecutorExecutorResponseSchema)` to create a new message.
 */
export declare const GetExecutorExecutorResponseSchema: GenMessage<GetExecutorExecutorResponse>;

/**
 * @generated from message tailor.v1.DeleteExecutorExecutorRequest
 */
export declare type DeleteExecutorExecutorRequest = Message<"tailor.v1.DeleteExecutorExecutorRequest"> & {
  /**
   * @generated from field: string workspace_id = 1;
   */
  workspaceId: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;
};

/**
 * Describes the message tailor.v1.DeleteExecutorExecutorRequest.
 * Use `create(DeleteExecutorExecutorRequestSchema)` to create a new message.
 */
export declare const DeleteExecutorExecutorRequestSchema: GenMessage<DeleteExecutorExecutorRequest>;

/**
 * @generated from message tailor.v1.DeleteExecutorExecutorResponse
 */
export declare type DeleteExecutorExecutorResponse = Message<"tailor.v1.DeleteExecutorExecutorResponse"> & {
};

/**
 * Describes the message tailor.v1.DeleteExecutorExecutorResponse.
 * Use `create(DeleteExecutorExecutorResponseSchema)` to create a new message.
 */
export declare const DeleteExecutorExecutorResponseSchema: GenMessage<DeleteExecutorExecutorResponse>;

/**
 * @generated from message tailor.v1.ListExecutorExecutorsRequest
 */
export declare type ListExecutorExecutorsRequest = Message<"tailor.v1.ListExecutorExecutorsRequest"> & {
  /**
   * @generated from field: string workspace_id = 1;
   */
  workspaceId: string;

  /**
   * @generated from field: string page_token = 2;
   */
  pageToken: string;

  /**
   * @generated from field: uint32 page_size = 3;
   */
  pageSize: number;

  /**
   * @generated from field: tailor.v1.PageDirection page_direction = 4;
   */
  pageDirection: PageDirection;
};

/**
 * Describes the message tailor.v1.ListExecutorExecutorsRequest.
 * Use `create(ListExecutorExecutorsRequestSchema)` to create a new message.
 */
export declare const ListExecutorExecutorsRequestSchema: GenMessage<ListExecutorExecutorsRequest>;

/**
 * @generated from message tailor.v1.ListExecutorExecutorsResponse
 */
export declare type ListExecutorExecutorsResponse = Message<"tailor.v1.ListExecutorExecutorsResponse"> & {
  /**
   * @generated from field: repeated tailor.v1.ExecutorExecutor executors = 1;
   */
  executors: ExecutorExecutor[];

  /**
   * @generated from field: string next_page_token = 2;
   */
  nextPageToken: string;

  /**
   * @generated from field: int64 total_count = 3;
   */
  totalCount: bigint;
};

/**
 * Describes the message tailor.v1.ListExecutorExecutorsResponse.
 * Use `create(ListExecutorExecutorsResponseSchema)` to create a new message.
 */
export declare const ListExecutorExecutorsResponseSchema: GenMessage<ListExecutorExecutorsResponse>;

/**
 * @generated from message tailor.v1.GetExecutorJobRequest
 */
export declare type GetExecutorJobRequest = Message<"tailor.v1.GetExecutorJobRequest"> & {
  /**
   * @generated from field: string workspace_id = 1;
   */
  workspaceId: string;

  /**
   * @generated from field: string executor_name = 2;
   */
  executorName: string;

  /**
   * @generated from field: string job_id = 3;
   */
  jobId: string;
};

/**
 * Describes the message tailor.v1.GetExecutorJobRequest.
 * Use `create(GetExecutorJobRequestSchema)` to create a new message.
 */
export declare const GetExecutorJobRequestSchema: GenMessage<GetExecutorJobRequest>;

/**
 * @generated from message tailor.v1.GetExecutorJobResponse
 */
export declare type GetExecutorJobResponse = Message<"tailor.v1.GetExecutorJobResponse"> & {
  /**
   * @generated from field: tailor.v1.ExecutorJob job = 1;
   */
  job?: ExecutorJob;
};

/**
 * Describes the message tailor.v1.GetExecutorJobResponse.
 * Use `create(GetExecutorJobResponseSchema)` to create a new message.
 */
export declare const GetExecutorJobResponseSchema: GenMessage<GetExecutorJobResponse>;

/**
 * @generated from message tailor.v1.ListExecutorJobsRequest
 */
export declare type ListExecutorJobsRequest = Message<"tailor.v1.ListExecutorJobsRequest"> & {
  /**
   * @generated from field: string workspace_id = 1;
   */
  workspaceId: string;

  /**
   * @generated from field: string executor_name = 2;
   */
  executorName: string;

  /**
   * @generated from field: string page_token = 3;
   */
  pageToken: string;

  /**
   * @generated from field: uint32 page_size = 4;
   */
  pageSize: number;

  /**
   * @generated from field: tailor.v1.PageDirection page_direction = 5;
   */
  pageDirection: PageDirection;

  /**
   * @generated from field: tailor.v1.Filter filter = 6;
   */
  filter?: Filter;
};

/**
 * Describes the message tailor.v1.ListExecutorJobsRequest.
 * Use `create(ListExecutorJobsRequestSchema)` to create a new message.
 */
export declare const ListExecutorJobsRequestSchema: GenMessage<ListExecutorJobsRequest>;

/**
 * @generated from message tailor.v1.ListExecutorJobsResponse
 */
export declare type ListExecutorJobsResponse = Message<"tailor.v1.ListExecutorJobsResponse"> & {
  /**
   * @generated from field: repeated tailor.v1.ExecutorJob jobs = 1;
   */
  jobs: ExecutorJob[];

  /**
   * @generated from field: string next_page_token = 2;
   */
  nextPageToken: string;

  /**
   * @generated from field: int64 total_count = 3;
   */
  totalCount: bigint;
};

/**
 * Describes the message tailor.v1.ListExecutorJobsResponse.
 * Use `create(ListExecutorJobsResponseSchema)` to create a new message.
 */
export declare const ListExecutorJobsResponseSchema: GenMessage<ListExecutorJobsResponse>;

/**
 * @generated from message tailor.v1.ListExecutorJobAttemptsRequest
 */
export declare type ListExecutorJobAttemptsRequest = Message<"tailor.v1.ListExecutorJobAttemptsRequest"> & {
  /**
   * @generated from field: string workspace_id = 1;
   */
  workspaceId: string;

  /**
   * @generated from field: string job_id = 2;
   */
  jobId: string;

  /**
   * @generated from field: string page_token = 3;
   */
  pageToken: string;

  /**
   * @generated from field: uint32 page_size = 4;
   */
  pageSize: number;

  /**
   * @generated from field: tailor.v1.PageDirection page_direction = 5;
   */
  pageDirection: PageDirection;
};

/**
 * Describes the message tailor.v1.ListExecutorJobAttemptsRequest.
 * Use `create(ListExecutorJobAttemptsRequestSchema)` to create a new message.
 */
export declare const ListExecutorJobAttemptsRequestSchema: GenMessage<ListExecutorJobAttemptsRequest>;

/**
 * @generated from message tailor.v1.ListExecutorJobAttemptsResponse
 */
export declare type ListExecutorJobAttemptsResponse = Message<"tailor.v1.ListExecutorJobAttemptsResponse"> & {
  /**
   * @generated from field: repeated tailor.v1.ExecutorJobAttempt attempts = 1;
   */
  attempts: ExecutorJobAttempt[];

  /**
   * @generated from field: string next_page_token = 2;
   */
  nextPageToken: string;

  /**
   * @generated from field: int64 total_count = 3;
   */
  totalCount: bigint;
};

/**
 * Describes the message tailor.v1.ListExecutorJobAttemptsResponse.
 * Use `create(ListExecutorJobAttemptsResponseSchema)` to create a new message.
 */
export declare const ListExecutorJobAttemptsResponseSchema: GenMessage<ListExecutorJobAttemptsResponse>;

/**
 * @generated from message tailor.v1.ListExecutorIncomingWebhooksRequest
 */
export declare type ListExecutorIncomingWebhooksRequest = Message<"tailor.v1.ListExecutorIncomingWebhooksRequest"> & {
  /**
   * @generated from field: string workspace_id = 1;
   */
  workspaceId: string;

  /**
   * @generated from field: string page_token = 2;
   */
  pageToken: string;

  /**
   * @generated from field: uint32 page_size = 3;
   */
  pageSize: number;

  /**
   * @generated from field: tailor.v1.PageDirection page_direction = 4;
   */
  pageDirection: PageDirection;
};

/**
 * Describes the message tailor.v1.ListExecutorIncomingWebhooksRequest.
 * Use `create(ListExecutorIncomingWebhooksRequestSchema)` to create a new message.
 */
export declare const ListExecutorIncomingWebhooksRequestSchema: GenMessage<ListExecutorIncomingWebhooksRequest>;

/**
 * @generated from message tailor.v1.ListExecutorIncomingWebhooksResponse
 */
export declare type ListExecutorIncomingWebhooksResponse = Message<"tailor.v1.ListExecutorIncomingWebhooksResponse"> & {
  /**
   * @generated from field: repeated tailor.v1.ExecutorIncomingWebhook webhooks = 1;
   */
  webhooks: ExecutorIncomingWebhook[];

  /**
   * @generated from field: string next_page_token = 2;
   */
  nextPageToken: string;

  /**
   * @generated from field: int64 total_count = 3;
   */
  totalCount: bigint;
};

/**
 * Describes the message tailor.v1.ListExecutorIncomingWebhooksResponse.
 * Use `create(ListExecutorIncomingWebhooksResponseSchema)` to create a new message.
 */
export declare const ListExecutorIncomingWebhooksResponseSchema: GenMessage<ListExecutorIncomingWebhooksResponse>;

/**
 * @generated from message tailor.v1.GetExecutorIncomingWebhookRequest
 */
export declare type GetExecutorIncomingWebhookRequest = Message<"tailor.v1.GetExecutorIncomingWebhookRequest"> & {
  /**
   * @generated from field: string workspace_id = 1;
   */
  workspaceId: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;
};

/**
 * Describes the message tailor.v1.GetExecutorIncomingWebhookRequest.
 * Use `create(GetExecutorIncomingWebhookRequestSchema)` to create a new message.
 */
export declare const GetExecutorIncomingWebhookRequestSchema: GenMessage<GetExecutorIncomingWebhookRequest>;

/**
 * @generated from message tailor.v1.GetExecutorIncomingWebhookResponse
 */
export declare type GetExecutorIncomingWebhookResponse = Message<"tailor.v1.GetExecutorIncomingWebhookResponse"> & {
  /**
   * @generated from field: tailor.v1.ExecutorIncomingWebhook webhook = 1;
   */
  webhook?: ExecutorIncomingWebhook;
};

/**
 * Describes the message tailor.v1.GetExecutorIncomingWebhookResponse.
 * Use `create(GetExecutorIncomingWebhookResponseSchema)` to create a new message.
 */
export declare const GetExecutorIncomingWebhookResponseSchema: GenMessage<GetExecutorIncomingWebhookResponse>;

/**
 * @generated from message tailor.v1.TriggerExecutorRequest
 */
export declare type TriggerExecutorRequest = Message<"tailor.v1.TriggerExecutorRequest"> & {
  /**
   * @generated from field: string workspace_id = 1;
   */
  workspaceId: string;

  /**
   * @generated from field: string executor_name = 2;
   */
  executorName: string;

  /**
   * @generated from field: google.protobuf.Struct payload = 3;
   */
  payload?: JsonObject;
};

/**
 * Describes the message tailor.v1.TriggerExecutorRequest.
 * Use `create(TriggerExecutorRequestSchema)` to create a new message.
 */
export declare const TriggerExecutorRequestSchema: GenMessage<TriggerExecutorRequest>;

/**
 * @generated from message tailor.v1.TriggerExecutorResponse
 */
export declare type TriggerExecutorResponse = Message<"tailor.v1.TriggerExecutorResponse"> & {
  /**
   * @generated from field: string job_id = 1;
   */
  jobId: string;
};

/**
 * Describes the message tailor.v1.TriggerExecutorResponse.
 * Use `create(TriggerExecutorResponseSchema)` to create a new message.
 */
export declare const TriggerExecutorResponseSchema: GenMessage<TriggerExecutorResponse>;

