// @generated by protoc-gen-es v2.6.3
// @generated from file tailor/v1/function.proto (package tailor.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { AuthInvoker } from "./auth_resource_pb";
import type { FunctionExecution } from "./function_resource_pb";
import type { Filter, PageDirection } from "./resource_pb";

/**
 * Describes the file tailor/v1/function.proto.
 */
export declare const file_tailor_v1_function: GenFile;

/**
 * @generated from message tailor.v1.TestExecScriptRequest
 */
export declare type TestExecScriptRequest = Message<"tailor.v1.TestExecScriptRequest"> & {
  /**
   * @generated from field: string workspace_id = 1;
   */
  workspaceId: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string code = 3;
   */
  code: string;

  /**
   * @generated from field: optional string arg = 4;
   */
  arg?: string;

  /**
   * @generated from field: tailor.v1.AuthInvoker invoker = 5;
   */
  invoker?: AuthInvoker;
};

/**
 * Describes the message tailor.v1.TestExecScriptRequest.
 * Use `create(TestExecScriptRequestSchema)` to create a new message.
 */
export declare const TestExecScriptRequestSchema: GenMessage<TestExecScriptRequest>;

/**
 * @generated from message tailor.v1.TestExecScriptResponse
 */
export declare type TestExecScriptResponse = Message<"tailor.v1.TestExecScriptResponse"> & {
  /**
   * @generated from field: string result = 1;
   */
  result: string;

  /**
   * @generated from field: string execution_id = 3;
   */
  executionId: string;
};

/**
 * Describes the message tailor.v1.TestExecScriptResponse.
 * Use `create(TestExecScriptResponseSchema)` to create a new message.
 */
export declare const TestExecScriptResponseSchema: GenMessage<TestExecScriptResponse>;

/**
 * @generated from message tailor.v1.GetFunctionExecutionRequest
 */
export declare type GetFunctionExecutionRequest = Message<"tailor.v1.GetFunctionExecutionRequest"> & {
  /**
   * @generated from field: string workspace_id = 1;
   */
  workspaceId: string;

  /**
   * @generated from field: string execution_id = 2;
   */
  executionId: string;
};

/**
 * Describes the message tailor.v1.GetFunctionExecutionRequest.
 * Use `create(GetFunctionExecutionRequestSchema)` to create a new message.
 */
export declare const GetFunctionExecutionRequestSchema: GenMessage<GetFunctionExecutionRequest>;

/**
 * @generated from message tailor.v1.GetFunctionExecutionResponse
 */
export declare type GetFunctionExecutionResponse = Message<"tailor.v1.GetFunctionExecutionResponse"> & {
  /**
   * @generated from field: tailor.v1.FunctionExecution execution = 1;
   */
  execution?: FunctionExecution;
};

/**
 * Describes the message tailor.v1.GetFunctionExecutionResponse.
 * Use `create(GetFunctionExecutionResponseSchema)` to create a new message.
 */
export declare const GetFunctionExecutionResponseSchema: GenMessage<GetFunctionExecutionResponse>;

/**
 * @generated from message tailor.v1.ListFunctionExecutionsRequest
 */
export declare type ListFunctionExecutionsRequest = Message<"tailor.v1.ListFunctionExecutionsRequest"> & {
  /**
   * @generated from field: string workspace_id = 1;
   */
  workspaceId: string;

  /**
   * @generated from field: string page_token = 2;
   */
  pageToken: string;

  /**
   * @generated from field: uint32 page_size = 3;
   */
  pageSize: number;

  /**
   * @generated from field: tailor.v1.PageDirection page_direction = 4;
   */
  pageDirection: PageDirection;

  /**
   * @generated from field: tailor.v1.Filter filter = 5;
   */
  filter?: Filter;

  /**
   * @generated from field: string sort_by = 6;
   */
  sortBy: string;
};

/**
 * Describes the message tailor.v1.ListFunctionExecutionsRequest.
 * Use `create(ListFunctionExecutionsRequestSchema)` to create a new message.
 */
export declare const ListFunctionExecutionsRequestSchema: GenMessage<ListFunctionExecutionsRequest>;

/**
 * @generated from message tailor.v1.ListFunctionExecutionsResponse
 */
export declare type ListFunctionExecutionsResponse = Message<"tailor.v1.ListFunctionExecutionsResponse"> & {
  /**
   * @generated from field: repeated tailor.v1.FunctionExecution executions = 1;
   */
  executions: FunctionExecution[];

  /**
   * @generated from field: string next_page_token = 2;
   */
  nextPageToken: string;

  /**
   * @generated from field: int64 total_count = 3;
   */
  totalCount: bigint;
};

/**
 * Describes the message tailor.v1.ListFunctionExecutionsResponse.
 * Use `create(ListFunctionExecutionsResponseSchema)` to create a new message.
 */
export declare const ListFunctionExecutionsResponseSchema: GenMessage<ListFunctionExecutionsResponse>;

