// @generated by protoc-gen-es v2.6.3
// @generated from file tailor/v1/function_registry.proto (package tailor.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import type { Filter, PageDirection } from "./resource_pb";

/**
 * Describes the file tailor/v1/function_registry.proto.
 */
export declare const file_tailor_v1_function_registry: GenFile;

/**
 * FunctionRegistry represents a registered function in the registry.
 *
 * @generated from message tailor.v1.FunctionRegistry
 */
export declare type FunctionRegistry = Message<"tailor.v1.FunctionRegistry"> & {
  /**
   * Unique identifier
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * Workspace ID
   *
   * @generated from field: string workspace_id = 2;
   */
  workspaceId: string;

  /**
   * Function name
   *
   * @generated from field: string name = 3;
   */
  name: string;

  /**
   * Size in bytes
   *
   * @generated from field: int64 size_bytes = 4;
   */
  sizeBytes: bigint;

  /**
   * SHA-256 content hash (content identifier)
   *
   * @generated from field: string content_hash = 5;
   */
  contentHash: string;

  /**
   * Description
   *
   * @generated from field: string description = 6;
   */
  description: string;

  /**
   * Creation timestamp
   *
   * @generated from field: google.protobuf.Timestamp created_at = 7;
   */
  createdAt?: Timestamp;

  /**
   * Last update timestamp
   *
   * @generated from field: google.protobuf.Timestamp updated_at = 8;
   */
  updatedAt?: Timestamp;
};

/**
 * Describes the message tailor.v1.FunctionRegistry.
 * Use `create(FunctionRegistrySchema)` to create a new message.
 */
export declare const FunctionRegistrySchema: GenMessage<FunctionRegistry>;

/**
 * CreateFunctionRegistryRequest is used for client streaming upload.
 * First message must contain info, subsequent messages contain chunks.
 *
 * @generated from message tailor.v1.CreateFunctionRegistryRequest
 */
export declare type CreateFunctionRegistryRequest = Message<"tailor.v1.CreateFunctionRegistryRequest"> & {
  /**
   * @generated from oneof tailor.v1.CreateFunctionRegistryRequest.payload
   */
  payload: {
    /**
     * First message: metadata about the script
     *
     * @generated from field: tailor.v1.CreateFunctionRegistryInfo info = 1;
     */
    value: CreateFunctionRegistryInfo;
    case: "info";
  } | {
    /**
     * Subsequent messages: script content chunks (recommended 64KB each)
     *
     * @generated from field: bytes chunk = 2;
     */
    value: Uint8Array;
    case: "chunk";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message tailor.v1.CreateFunctionRegistryRequest.
 * Use `create(CreateFunctionRegistryRequestSchema)` to create a new message.
 */
export declare const CreateFunctionRegistryRequestSchema: GenMessage<CreateFunctionRegistryRequest>;

/**
 * CreateFunctionRegistryInfo contains metadata for function creation.
 *
 * @generated from message tailor.v1.CreateFunctionRegistryInfo
 */
export declare type CreateFunctionRegistryInfo = Message<"tailor.v1.CreateFunctionRegistryInfo"> & {
  /**
   * Workspace ID
   *
   * @generated from field: string workspace_id = 1;
   */
  workspaceId: string;

  /**
   * Function name (required, must be unique within workspace)
   *
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * Description of the function (optional)
   *
   * @generated from field: string description = 3;
   */
  description: string;

  /**
   * Size of the script in bytes
   *
   * max 20MB
   *
   * @generated from field: int64 size_bytes = 4;
   */
  sizeBytes: bigint;

  /**
   * Pre-computed SHA-256 hash of the script content (required, verified by server)
   *
   * @generated from field: string content_hash = 5;
   */
  contentHash: string;
};

/**
 * Describes the message tailor.v1.CreateFunctionRegistryInfo.
 * Use `create(CreateFunctionRegistryInfoSchema)` to create a new message.
 */
export declare const CreateFunctionRegistryInfoSchema: GenMessage<CreateFunctionRegistryInfo>;

/**
 * CreateFunctionRegistryResponse is returned after upload completes.
 *
 * @generated from message tailor.v1.CreateFunctionRegistryResponse
 */
export declare type CreateFunctionRegistryResponse = Message<"tailor.v1.CreateFunctionRegistryResponse"> & {
  /**
   * The created function
   *
   * @generated from field: tailor.v1.FunctionRegistry function = 1;
   */
  function?: FunctionRegistry;
};

/**
 * Describes the message tailor.v1.CreateFunctionRegistryResponse.
 * Use `create(CreateFunctionRegistryResponseSchema)` to create a new message.
 */
export declare const CreateFunctionRegistryResponseSchema: GenMessage<CreateFunctionRegistryResponse>;

/**
 * UpdateFunctionRegistryRequest is used for client streaming upload.
 * First message must contain info, subsequent messages contain chunks.
 *
 * @generated from message tailor.v1.UpdateFunctionRegistryRequest
 */
export declare type UpdateFunctionRegistryRequest = Message<"tailor.v1.UpdateFunctionRegistryRequest"> & {
  /**
   * @generated from oneof tailor.v1.UpdateFunctionRegistryRequest.payload
   */
  payload: {
    /**
     * First message: metadata about the script
     *
     * @generated from field: tailor.v1.UpdateFunctionRegistryInfo info = 1;
     */
    value: UpdateFunctionRegistryInfo;
    case: "info";
  } | {
    /**
     * Subsequent messages: script content chunks (recommended 64KB each)
     *
     * @generated from field: bytes chunk = 2;
     */
    value: Uint8Array;
    case: "chunk";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message tailor.v1.UpdateFunctionRegistryRequest.
 * Use `create(UpdateFunctionRegistryRequestSchema)` to create a new message.
 */
export declare const UpdateFunctionRegistryRequestSchema: GenMessage<UpdateFunctionRegistryRequest>;

/**
 * UpdateFunctionRegistryInfo contains metadata for function update.
 *
 * @generated from message tailor.v1.UpdateFunctionRegistryInfo
 */
export declare type UpdateFunctionRegistryInfo = Message<"tailor.v1.UpdateFunctionRegistryInfo"> & {
  /**
   * Workspace ID
   *
   * @generated from field: string workspace_id = 1;
   */
  workspaceId: string;

  /**
   * Function name (must exist)
   *
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * Description of the function (optional)
   *
   * @generated from field: string description = 3;
   */
  description: string;

  /**
   * Size of the script in bytes
   *
   * max 20MB
   *
   * @generated from field: int64 size_bytes = 4;
   */
  sizeBytes: bigint;

  /**
   * Pre-computed SHA-256 hash of the script content (required, verified by server)
   *
   * @generated from field: string content_hash = 5;
   */
  contentHash: string;
};

/**
 * Describes the message tailor.v1.UpdateFunctionRegistryInfo.
 * Use `create(UpdateFunctionRegistryInfoSchema)` to create a new message.
 */
export declare const UpdateFunctionRegistryInfoSchema: GenMessage<UpdateFunctionRegistryInfo>;

/**
 * UpdateFunctionRegistryResponse is returned after update completes.
 *
 * @generated from message tailor.v1.UpdateFunctionRegistryResponse
 */
export declare type UpdateFunctionRegistryResponse = Message<"tailor.v1.UpdateFunctionRegistryResponse"> & {
  /**
   * The updated function
   *
   * @generated from field: tailor.v1.FunctionRegistry function = 1;
   */
  function?: FunctionRegistry;
};

/**
 * Describes the message tailor.v1.UpdateFunctionRegistryResponse.
 * Use `create(UpdateFunctionRegistryResponseSchema)` to create a new message.
 */
export declare const UpdateFunctionRegistryResponseSchema: GenMessage<UpdateFunctionRegistryResponse>;

/**
 * GetFunctionRegistryRequest is the request message for GetFunctionRegistry.
 *
 * @generated from message tailor.v1.GetFunctionRegistryRequest
 */
export declare type GetFunctionRegistryRequest = Message<"tailor.v1.GetFunctionRegistryRequest"> & {
  /**
   * @generated from field: string workspace_id = 1;
   */
  workspaceId: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;
};

/**
 * Describes the message tailor.v1.GetFunctionRegistryRequest.
 * Use `create(GetFunctionRegistryRequestSchema)` to create a new message.
 */
export declare const GetFunctionRegistryRequestSchema: GenMessage<GetFunctionRegistryRequest>;

/**
 * GetFunctionRegistryResponse is the response message for GetFunctionRegistry.
 *
 * @generated from message tailor.v1.GetFunctionRegistryResponse
 */
export declare type GetFunctionRegistryResponse = Message<"tailor.v1.GetFunctionRegistryResponse"> & {
  /**
   * @generated from field: tailor.v1.FunctionRegistry function = 1;
   */
  function?: FunctionRegistry;
};

/**
 * Describes the message tailor.v1.GetFunctionRegistryResponse.
 * Use `create(GetFunctionRegistryResponseSchema)` to create a new message.
 */
export declare const GetFunctionRegistryResponseSchema: GenMessage<GetFunctionRegistryResponse>;

/**
 * ListFunctionRegistriesRequest is the request message for ListFunctionRegistries.
 *
 * @generated from message tailor.v1.ListFunctionRegistriesRequest
 */
export declare type ListFunctionRegistriesRequest = Message<"tailor.v1.ListFunctionRegistriesRequest"> & {
  /**
   * @generated from field: string workspace_id = 1;
   */
  workspaceId: string;

  /**
   * @generated from field: string page_token = 2;
   */
  pageToken: string;

  /**
   * @generated from field: uint32 page_size = 3;
   */
  pageSize: number;

  /**
   * @generated from field: tailor.v1.PageDirection page_direction = 4;
   */
  pageDirection: PageDirection;

  /**
   * @generated from field: tailor.v1.Filter filter = 5;
   */
  filter?: Filter;

  /**
   * @generated from field: string sort_by = 6;
   */
  sortBy: string;
};

/**
 * Describes the message tailor.v1.ListFunctionRegistriesRequest.
 * Use `create(ListFunctionRegistriesRequestSchema)` to create a new message.
 */
export declare const ListFunctionRegistriesRequestSchema: GenMessage<ListFunctionRegistriesRequest>;

/**
 * ListFunctionRegistriesResponse is the response message for ListFunctionRegistries.
 *
 * @generated from message tailor.v1.ListFunctionRegistriesResponse
 */
export declare type ListFunctionRegistriesResponse = Message<"tailor.v1.ListFunctionRegistriesResponse"> & {
  /**
   * @generated from field: repeated tailor.v1.FunctionRegistry functions = 1;
   */
  functions: FunctionRegistry[];

  /**
   * @generated from field: string next_page_token = 2;
   */
  nextPageToken: string;

  /**
   * @generated from field: int64 total_count = 3;
   */
  totalCount: bigint;
};

/**
 * Describes the message tailor.v1.ListFunctionRegistriesResponse.
 * Use `create(ListFunctionRegistriesResponseSchema)` to create a new message.
 */
export declare const ListFunctionRegistriesResponseSchema: GenMessage<ListFunctionRegistriesResponse>;

/**
 * DeleteFunctionRegistryRequest is the request message for DeleteFunctionRegistry.
 *
 * @generated from message tailor.v1.DeleteFunctionRegistryRequest
 */
export declare type DeleteFunctionRegistryRequest = Message<"tailor.v1.DeleteFunctionRegistryRequest"> & {
  /**
   * @generated from field: string workspace_id = 1;
   */
  workspaceId: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;
};

/**
 * Describes the message tailor.v1.DeleteFunctionRegistryRequest.
 * Use `create(DeleteFunctionRegistryRequestSchema)` to create a new message.
 */
export declare const DeleteFunctionRegistryRequestSchema: GenMessage<DeleteFunctionRegistryRequest>;

/**
 * DeleteFunctionRegistryResponse is the response message for DeleteFunctionRegistry.
 *
 * @generated from message tailor.v1.DeleteFunctionRegistryResponse
 */
export declare type DeleteFunctionRegistryResponse = Message<"tailor.v1.DeleteFunctionRegistryResponse"> & {
};

/**
 * Describes the message tailor.v1.DeleteFunctionRegistryResponse.
 * Use `create(DeleteFunctionRegistryResponseSchema)` to create a new message.
 */
export declare const DeleteFunctionRegistryResponseSchema: GenMessage<DeleteFunctionRegistryResponse>;

/**
 * DownloadFunctionRegistryScriptRequest is the request message for DownloadFunctionRegistryScript.
 *
 * @generated from message tailor.v1.DownloadFunctionRegistryScriptRequest
 */
export declare type DownloadFunctionRegistryScriptRequest = Message<"tailor.v1.DownloadFunctionRegistryScriptRequest"> & {
  /**
   * @generated from field: string workspace_id = 1;
   */
  workspaceId: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * Optional content hash to get specific version. If not provided, returns current version.
   *
   * @generated from field: optional string content_hash = 3;
   */
  contentHash?: string;
};

/**
 * Describes the message tailor.v1.DownloadFunctionRegistryScriptRequest.
 * Use `create(DownloadFunctionRegistryScriptRequestSchema)` to create a new message.
 */
export declare const DownloadFunctionRegistryScriptRequestSchema: GenMessage<DownloadFunctionRegistryScriptRequest>;

/**
 * DownloadFunctionRegistryScriptResponse is used for server streaming download.
 * First message contains metadata, subsequent messages contain chunks.
 *
 * @generated from message tailor.v1.DownloadFunctionRegistryScriptResponse
 */
export declare type DownloadFunctionRegistryScriptResponse = Message<"tailor.v1.DownloadFunctionRegistryScriptResponse"> & {
  /**
   * @generated from oneof tailor.v1.DownloadFunctionRegistryScriptResponse.payload
   */
  payload: {
    /**
     * First message: metadata about the script and function
     *
     * @generated from field: tailor.v1.FunctionRegistryScriptMetadata metadata = 1;
     */
    value: FunctionRegistryScriptMetadata;
    case: "metadata";
  } | {
    /**
     * Subsequent messages: script content chunks (64KB each)
     *
     * @generated from field: bytes chunk = 2;
     */
    value: Uint8Array;
    case: "chunk";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message tailor.v1.DownloadFunctionRegistryScriptResponse.
 * Use `create(DownloadFunctionRegistryScriptResponseSchema)` to create a new message.
 */
export declare const DownloadFunctionRegistryScriptResponseSchema: GenMessage<DownloadFunctionRegistryScriptResponse>;

/**
 * FunctionRegistryScriptMetadata contains metadata for script download.
 *
 * @generated from message tailor.v1.FunctionRegistryScriptMetadata
 */
export declare type FunctionRegistryScriptMetadata = Message<"tailor.v1.FunctionRegistryScriptMetadata"> & {
  /**
   * The function details
   *
   * @generated from field: tailor.v1.FunctionRegistry function = 1;
   */
  function?: FunctionRegistry;
};

/**
 * Describes the message tailor.v1.FunctionRegistryScriptMetadata.
 * Use `create(FunctionRegistryScriptMetadataSchema)` to create a new message.
 */
export declare const FunctionRegistryScriptMetadataSchema: GenMessage<FunctionRegistryScriptMetadata>;

