// @generated by protoc-gen-es v2.6.3
// @generated from file tailor/v1/gateway_filter_resource.proto (package tailor.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file tailor/v1/gateway_filter_resource.proto.
 */
export declare const file_tailor_v1_gateway_filter_resource: GenFile;

/**
 * @generated from message tailor.v1.GatewayFilter
 */
export declare type GatewayFilter = Message<"tailor.v1.GatewayFilter"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string path_pattern = 2;
   */
  pathPattern: string;

  /**
   * @generated from field: repeated string methods = 3;
   */
  methods: string[];

  /**
   * @generated from field: string input_filter_script = 4;
   */
  inputFilterScript: string;

  /**
   * optional
   *
   * @generated from field: string output_filter_script = 5;
   */
  outputFilterScript: string;

  /**
   * @generated from field: bool enabled = 6;
   */
  enabled: boolean;

  /**
   * @generated from field: int32 priority = 7;
   */
  priority: number;

  /**
   * @generated from field: google.protobuf.Timestamp create_time = 8;
   */
  createTime?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp update_time = 9;
   */
  updateTime?: Timestamp;
};

/**
 * Describes the message tailor.v1.GatewayFilter.
 * Use `create(GatewayFilterSchema)` to create a new message.
 */
export declare const GatewayFilterSchema: GenMessage<GatewayFilter>;

