// @generated by protoc-gen-es v2.6.3
// @generated from file tailor/v1/idp_resource.proto (package tailor.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Namespace } from "./resource_pb";

/**
 * Describes the file tailor/v1/idp_resource.proto.
 */
export declare const file_tailor_v1_idp_resource: GenFile;

/**
 * @generated from message tailor.v1.IdPService
 */
export declare type IdPService = Message<"tailor.v1.IdPService"> & {
  /**
   * @generated from field: tailor.v1.Namespace namespace = 1;
   */
  namespace?: Namespace;

  /**
   * @generated from field: string authorization = 2;
   */
  authorization: string;

  /**
   * @generated from field: string provider_url = 3;
   */
  providerUrl: string;

  /**
   * @generated from field: tailor.v1.IdPUserAuthPolicy user_auth_policy = 4;
   */
  userAuthPolicy?: IdPUserAuthPolicy;

  /**
   * lang is the IETF BCP 47 language subtag.
   *
   * @generated from field: tailor.v1.IdPLang lang = 5;
   */
  lang: IdPLang;

  /**
   * publish_user_events indicates whether user lifecycle events (created, updated, deleted) are enabled.
   * When enabled, events are published to the dataplane event topic.
   *
   * @generated from field: bool publish_user_events = 6;
   */
  publishUserEvents: boolean;

  /**
   * @generated from field: tailor.v1.IdPDisableGqlOperations disable_gql_operations = 7;
   */
  disableGqlOperations?: IdPDisableGqlOperations;

  /**
   * @generated from field: tailor.v1.IdPEmailConfig email_config = 8;
   */
  emailConfig?: IdPEmailConfig;
};

/**
 * Describes the message tailor.v1.IdPService.
 * Use `create(IdPServiceSchema)` to create a new message.
 */
export declare const IdPServiceSchema: GenMessage<IdPService>;

/**
 * IdPDisableGqlOperations controls which IdP-related GraphQL operations are disabled.
 *
 * @generated from message tailor.v1.IdPDisableGqlOperations
 */
export declare type IdPDisableGqlOperations = Message<"tailor.v1.IdPDisableGqlOperations"> & {
  /**
   * create disables the _createUser GraphQL mutation.
   *
   * @generated from field: bool create = 1;
   */
  create: boolean;

  /**
   * update disables the _updateUser GraphQL mutation.
   *
   * @generated from field: bool update = 2;
   */
  update: boolean;

  /**
   * delete disables the _deleteUser GraphQL mutation.
   *
   * @generated from field: bool delete = 3;
   */
  delete: boolean;

  /**
   * read disables the _users and _user GraphQL queries.
   *
   * @generated from field: bool read = 4;
   */
  read: boolean;

  /**
   * send_password_reset_email disables the _sendPasswordResetEmail GraphQL mutation.
   *
   * @generated from field: bool send_password_reset_email = 5;
   */
  sendPasswordResetEmail: boolean;
};

/**
 * Describes the message tailor.v1.IdPDisableGqlOperations.
 * Use `create(IdPDisableGqlOperationsSchema)` to create a new message.
 */
export declare const IdPDisableGqlOperationsSchema: GenMessage<IdPDisableGqlOperations>;

/**
 * IdPEmailConfig holds namespace-level email configuration defaults.
 *
 * @generated from message tailor.v1.IdPEmailConfig
 */
export declare type IdPEmailConfig = Message<"tailor.v1.IdPEmailConfig"> & {
  /**
   * from_name is the default sender display name for emails. Empty means use mailer default.
   *
   * @generated from field: string from_name = 1;
   */
  fromName: string;

  /**
   * password_reset_subject is the default subject for password reset emails. Empty means use localized default.
   *
   * @generated from field: string password_reset_subject = 2;
   */
  passwordResetSubject: string;
};

/**
 * Describes the message tailor.v1.IdPEmailConfig.
 * Use `create(IdPEmailConfigSchema)` to create a new message.
 */
export declare const IdPEmailConfigSchema: GenMessage<IdPEmailConfig>;

/**
 * @generated from message tailor.v1.IdPClient
 */
export declare type IdPClient = Message<"tailor.v1.IdPClient"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string client_id = 2;
   */
  clientId: string;

  /**
   * @generated from field: string client_secret = 3;
   */
  clientSecret: string;
};

/**
 * Describes the message tailor.v1.IdPClient.
 * Use `create(IdPClientSchema)` to create a new message.
 */
export declare const IdPClientSchema: GenMessage<IdPClient>;

/**
 * @generated from message tailor.v1.IdPUserAuthPolicy
 */
export declare type IdPUserAuthPolicy = Message<"tailor.v1.IdPUserAuthPolicy"> & {
  /**
   * @generated from field: bool use_non_email_identifier = 1;
   */
  useNonEmailIdentifier: boolean;

  /**
   * @generated from field: bool allow_self_password_reset = 2;
   */
  allowSelfPasswordReset: boolean;

  /**
   * Password policy fields (stored in Identity Platform, not in DB)
   *
   * @generated from field: bool password_require_uppercase = 3;
   */
  passwordRequireUppercase: boolean;

  /**
   * @generated from field: bool password_require_lowercase = 4;
   */
  passwordRequireLowercase: boolean;

  /**
   * @generated from field: bool password_require_non_alphanumeric = 5;
   */
  passwordRequireNonAlphanumeric: boolean;

  /**
   * @generated from field: bool password_require_numeric = 6;
   */
  passwordRequireNumeric: boolean;

  /**
   * password_min_length: valid range is 6-30 (default: 6). When 0 (unset), uses default value 6.
   *
   * @generated from field: int32 password_min_length = 7;
   */
  passwordMinLength: number;

  /**
   * password_max_length: valid range is 6-4096 (default: 4096). When 0 (unset), uses default value 4096.
   *
   * @generated from field: int32 password_max_length = 8;
   */
  passwordMaxLength: number;

  /**
   * List of allowed email domains (e.g., ["example.com", "corp.example.com"])
   * Empty list means all domains are allowed (backward compatible)
   * Cannot be set when use_non_email_identifier is true
   *
   * @generated from field: repeated string allowed_email_domains = 9;
   */
  allowedEmailDomains: string[];

  /**
   * allow_google_oauth enables "Sign in with Google" for this namespace.
   * When enabled, users can authenticate using their Google account.
   * Cannot be enabled when use_non_email_identifier is true.
   * Requires allowed_email_domains to be set.
   *
   * @generated from field: bool allow_google_oauth = 10;
   */
  allowGoogleOauth: boolean;

  /**
   * disable_password_auth disables password-based authentication for this namespace.
   * When enabled, users cannot sign in or reset their password using email/password.
   * Requires allow_google_oauth or allow_microsoft_oauth to be enabled.
   * Cannot be used with allow_self_password_reset.
   *
   * @generated from field: bool disable_password_auth = 11;
   */
  disablePasswordAuth: boolean;

  /**
   * allow_microsoft_oauth enables "Sign in with Microsoft" for this namespace.
   * Requires disable_password_auth to be true.
   * Cannot be enabled when use_non_email_identifier is true.
   *
   * @generated from field: bool allow_microsoft_oauth = 12;
   */
  allowMicrosoftOauth: boolean;
};

/**
 * Describes the message tailor.v1.IdPUserAuthPolicy.
 * Use `create(IdPUserAuthPolicySchema)` to create a new message.
 */
export declare const IdPUserAuthPolicySchema: GenMessage<IdPUserAuthPolicy>;

/**
 * IdPLang represents the IETF BCP 47 language subtag.
 *
 * @generated from enum tailor.v1.IdPLang
 */
export enum IdPLang {
  /**
   * @generated from enum value: ID_P_LANG_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: ID_P_LANG_EN = 1;
   */
  EN = 1,

  /**
   * @generated from enum value: ID_P_LANG_JA = 2;
   */
  JA = 2,
}

/**
 * Describes the enum tailor.v1.IdPLang.
 */
export declare const IdPLangSchema: GenEnum<IdPLang>;

