// @generated by protoc-gen-es v2.6.3
// @generated from file tailor/v1/idp.proto (package tailor.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { PageDirection } from "./resource_pb";
import type { IdPClient, IdPService, IdPUserAuthPolicy } from "./idp_resource_pb";

/**
 * Describes the file tailor/v1/idp.proto.
 */
export declare const file_tailor_v1_idp: GenFile;

/**
 * @generated from message tailor.v1.ListIdPServicesRequest
 */
export declare type ListIdPServicesRequest = Message<"tailor.v1.ListIdPServicesRequest"> & {
  /**
   * @generated from field: string workspace_id = 1;
   */
  workspaceId: string;

  /**
   * @generated from field: string page_token = 2;
   */
  pageToken: string;

  /**
   * @generated from field: uint32 page_size = 3;
   */
  pageSize: number;

  /**
   * @generated from field: tailor.v1.PageDirection page_direction = 4;
   */
  pageDirection: PageDirection;
};

/**
 * Describes the message tailor.v1.ListIdPServicesRequest.
 * Use `create(ListIdPServicesRequestSchema)` to create a new message.
 */
export declare const ListIdPServicesRequestSchema: GenMessage<ListIdPServicesRequest>;

/**
 * @generated from message tailor.v1.ListIdPServicesResponse
 */
export declare type ListIdPServicesResponse = Message<"tailor.v1.ListIdPServicesResponse"> & {
  /**
   * @generated from field: repeated tailor.v1.IdPService idp_services = 1;
   */
  idpServices: IdPService[];

  /**
   * @generated from field: string next_page_token = 2;
   */
  nextPageToken: string;

  /**
   * @generated from field: int64 total_count = 3;
   */
  totalCount: bigint;
};

/**
 * Describes the message tailor.v1.ListIdPServicesResponse.
 * Use `create(ListIdPServicesResponseSchema)` to create a new message.
 */
export declare const ListIdPServicesResponseSchema: GenMessage<ListIdPServicesResponse>;

/**
 * @generated from message tailor.v1.CreateIdPServiceRequest
 */
export declare type CreateIdPServiceRequest = Message<"tailor.v1.CreateIdPServiceRequest"> & {
  /**
   * @generated from field: string workspace_id = 1;
   */
  workspaceId: string;

  /**
   * @generated from field: string namespace_name = 2;
   */
  namespaceName: string;

  /**
   * @generated from field: string authorization = 3;
   */
  authorization: string;

  /**
   * @generated from field: tailor.v1.IdPUserAuthPolicy user_auth_policy = 4;
   */
  userAuthPolicy?: IdPUserAuthPolicy;
};

/**
 * Describes the message tailor.v1.CreateIdPServiceRequest.
 * Use `create(CreateIdPServiceRequestSchema)` to create a new message.
 */
export declare const CreateIdPServiceRequestSchema: GenMessage<CreateIdPServiceRequest>;

/**
 * @generated from message tailor.v1.CreateIdPServiceResponse
 */
export declare type CreateIdPServiceResponse = Message<"tailor.v1.CreateIdPServiceResponse"> & {
  /**
   * @generated from field: tailor.v1.IdPService idp_service = 1;
   */
  idpService?: IdPService;
};

/**
 * Describes the message tailor.v1.CreateIdPServiceResponse.
 * Use `create(CreateIdPServiceResponseSchema)` to create a new message.
 */
export declare const CreateIdPServiceResponseSchema: GenMessage<CreateIdPServiceResponse>;

/**
 * @generated from message tailor.v1.UpdateIdPServiceRequest
 */
export declare type UpdateIdPServiceRequest = Message<"tailor.v1.UpdateIdPServiceRequest"> & {
  /**
   * @generated from field: string workspace_id = 1;
   */
  workspaceId: string;

  /**
   * @generated from field: string namespace_name = 2;
   */
  namespaceName: string;

  /**
   * @generated from field: string authorization = 3;
   */
  authorization: string;

  /**
   * @generated from field: tailor.v1.IdPUserAuthPolicy user_auth_policy = 4;
   */
  userAuthPolicy?: IdPUserAuthPolicy;
};

/**
 * Describes the message tailor.v1.UpdateIdPServiceRequest.
 * Use `create(UpdateIdPServiceRequestSchema)` to create a new message.
 */
export declare const UpdateIdPServiceRequestSchema: GenMessage<UpdateIdPServiceRequest>;

/**
 * @generated from message tailor.v1.UpdateIdPServiceResponse
 */
export declare type UpdateIdPServiceResponse = Message<"tailor.v1.UpdateIdPServiceResponse"> & {
  /**
   * @generated from field: tailor.v1.IdPService idp_service = 1;
   */
  idpService?: IdPService;
};

/**
 * Describes the message tailor.v1.UpdateIdPServiceResponse.
 * Use `create(UpdateIdPServiceResponseSchema)` to create a new message.
 */
export declare const UpdateIdPServiceResponseSchema: GenMessage<UpdateIdPServiceResponse>;

/**
 * @generated from message tailor.v1.DeleteIdPServiceRequest
 */
export declare type DeleteIdPServiceRequest = Message<"tailor.v1.DeleteIdPServiceRequest"> & {
  /**
   * @generated from field: string workspace_id = 1;
   */
  workspaceId: string;

  /**
   * @generated from field: string namespace_name = 2;
   */
  namespaceName: string;
};

/**
 * Describes the message tailor.v1.DeleteIdPServiceRequest.
 * Use `create(DeleteIdPServiceRequestSchema)` to create a new message.
 */
export declare const DeleteIdPServiceRequestSchema: GenMessage<DeleteIdPServiceRequest>;

/**
 * @generated from message tailor.v1.DeleteIdPServiceResponse
 */
export declare type DeleteIdPServiceResponse = Message<"tailor.v1.DeleteIdPServiceResponse"> & {
};

/**
 * Describes the message tailor.v1.DeleteIdPServiceResponse.
 * Use `create(DeleteIdPServiceResponseSchema)` to create a new message.
 */
export declare const DeleteIdPServiceResponseSchema: GenMessage<DeleteIdPServiceResponse>;

/**
 * @generated from message tailor.v1.GetIdPServiceRequest
 */
export declare type GetIdPServiceRequest = Message<"tailor.v1.GetIdPServiceRequest"> & {
  /**
   * @generated from field: string workspace_id = 1;
   */
  workspaceId: string;

  /**
   * @generated from field: string namespace_name = 2;
   */
  namespaceName: string;
};

/**
 * Describes the message tailor.v1.GetIdPServiceRequest.
 * Use `create(GetIdPServiceRequestSchema)` to create a new message.
 */
export declare const GetIdPServiceRequestSchema: GenMessage<GetIdPServiceRequest>;

/**
 * @generated from message tailor.v1.GetIdPServiceResponse
 */
export declare type GetIdPServiceResponse = Message<"tailor.v1.GetIdPServiceResponse"> & {
  /**
   * @generated from field: tailor.v1.IdPService idp_service = 1;
   */
  idpService?: IdPService;
};

/**
 * Describes the message tailor.v1.GetIdPServiceResponse.
 * Use `create(GetIdPServiceResponseSchema)` to create a new message.
 */
export declare const GetIdPServiceResponseSchema: GenMessage<GetIdPServiceResponse>;

/**
 * @generated from message tailor.v1.ListIdPClientsRequest
 */
export declare type ListIdPClientsRequest = Message<"tailor.v1.ListIdPClientsRequest"> & {
  /**
   * @generated from field: string workspace_id = 1;
   */
  workspaceId: string;

  /**
   * @generated from field: string namespace_name = 2;
   */
  namespaceName: string;

  /**
   * @generated from field: string page_token = 3;
   */
  pageToken: string;

  /**
   * @generated from field: uint32 page_size = 4;
   */
  pageSize: number;

  /**
   * @generated from field: tailor.v1.PageDirection page_direction = 5;
   */
  pageDirection: PageDirection;
};

/**
 * Describes the message tailor.v1.ListIdPClientsRequest.
 * Use `create(ListIdPClientsRequestSchema)` to create a new message.
 */
export declare const ListIdPClientsRequestSchema: GenMessage<ListIdPClientsRequest>;

/**
 * @generated from message tailor.v1.ListIdPClientsResponse
 */
export declare type ListIdPClientsResponse = Message<"tailor.v1.ListIdPClientsResponse"> & {
  /**
   * @generated from field: repeated tailor.v1.IdPClient clients = 1;
   */
  clients: IdPClient[];

  /**
   * @generated from field: string next_page_token = 2;
   */
  nextPageToken: string;

  /**
   * @generated from field: int64 total_count = 3;
   */
  totalCount: bigint;
};

/**
 * Describes the message tailor.v1.ListIdPClientsResponse.
 * Use `create(ListIdPClientsResponseSchema)` to create a new message.
 */
export declare const ListIdPClientsResponseSchema: GenMessage<ListIdPClientsResponse>;

/**
 * @generated from message tailor.v1.CreateIdPClientRequest
 */
export declare type CreateIdPClientRequest = Message<"tailor.v1.CreateIdPClientRequest"> & {
  /**
   * @generated from field: string workspace_id = 1;
   */
  workspaceId: string;

  /**
   * @generated from field: string namespace_name = 2;
   */
  namespaceName: string;

  /**
   * @generated from field: tailor.v1.IdPClient client = 3;
   */
  client?: IdPClient;
};

/**
 * Describes the message tailor.v1.CreateIdPClientRequest.
 * Use `create(CreateIdPClientRequestSchema)` to create a new message.
 */
export declare const CreateIdPClientRequestSchema: GenMessage<CreateIdPClientRequest>;

/**
 * @generated from message tailor.v1.CreateIdPClientResponse
 */
export declare type CreateIdPClientResponse = Message<"tailor.v1.CreateIdPClientResponse"> & {
  /**
   * @generated from field: tailor.v1.IdPClient client = 1;
   */
  client?: IdPClient;
};

/**
 * Describes the message tailor.v1.CreateIdPClientResponse.
 * Use `create(CreateIdPClientResponseSchema)` to create a new message.
 */
export declare const CreateIdPClientResponseSchema: GenMessage<CreateIdPClientResponse>;

/**
 * @generated from message tailor.v1.GetIdPClientRequest
 */
export declare type GetIdPClientRequest = Message<"tailor.v1.GetIdPClientRequest"> & {
  /**
   * @generated from field: string workspace_id = 1;
   */
  workspaceId: string;

  /**
   * @generated from field: string namespace_name = 2;
   */
  namespaceName: string;

  /**
   * @generated from field: string name = 3;
   */
  name: string;
};

/**
 * Describes the message tailor.v1.GetIdPClientRequest.
 * Use `create(GetIdPClientRequestSchema)` to create a new message.
 */
export declare const GetIdPClientRequestSchema: GenMessage<GetIdPClientRequest>;

/**
 * @generated from message tailor.v1.GetIdPClientResponse
 */
export declare type GetIdPClientResponse = Message<"tailor.v1.GetIdPClientResponse"> & {
  /**
   * @generated from field: tailor.v1.IdPClient client = 1;
   */
  client?: IdPClient;
};

/**
 * Describes the message tailor.v1.GetIdPClientResponse.
 * Use `create(GetIdPClientResponseSchema)` to create a new message.
 */
export declare const GetIdPClientResponseSchema: GenMessage<GetIdPClientResponse>;

/**
 * @generated from message tailor.v1.DeleteIdPClientRequest
 */
export declare type DeleteIdPClientRequest = Message<"tailor.v1.DeleteIdPClientRequest"> & {
  /**
   * @generated from field: string workspace_id = 1;
   */
  workspaceId: string;

  /**
   * @generated from field: string namespace_name = 2;
   */
  namespaceName: string;

  /**
   * @generated from field: string name = 3;
   */
  name: string;
};

/**
 * Describes the message tailor.v1.DeleteIdPClientRequest.
 * Use `create(DeleteIdPClientRequestSchema)` to create a new message.
 */
export declare const DeleteIdPClientRequestSchema: GenMessage<DeleteIdPClientRequest>;

/**
 * @generated from message tailor.v1.DeleteIdPClientResponse
 */
export declare type DeleteIdPClientResponse = Message<"tailor.v1.DeleteIdPClientResponse"> & {
};

/**
 * Describes the message tailor.v1.DeleteIdPClientResponse.
 * Use `create(DeleteIdPClientResponseSchema)` to create a new message.
 */
export declare const DeleteIdPClientResponseSchema: GenMessage<DeleteIdPClientResponse>;

