// @generated by protoc-gen-es v2.6.3
// @generated from file tailor/v1/idp_resource.proto (package tailor.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Namespace } from "./resource_pb";
import type { Value } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file tailor/v1/idp_resource.proto.
 */
export declare const file_tailor_v1_idp_resource: GenFile;

/**
 * @generated from message tailor.v1.IdPService
 */
export declare type IdPService = Message<"tailor.v1.IdPService"> & {
  /**
   * @generated from field: tailor.v1.Namespace namespace = 1;
   */
  namespace?: Namespace;

  /**
   * @generated from field: string authorization = 2;
   */
  authorization: string;

  /**
   * @generated from field: string provider_url = 3;
   */
  providerUrl: string;

  /**
   * @generated from field: tailor.v1.IdPUserAuthPolicy user_auth_policy = 4;
   */
  userAuthPolicy?: IdPUserAuthPolicy;

  /**
   * lang is the IETF BCP 47 language subtag.
   *
   * @generated from field: tailor.v1.IdPLang lang = 5;
   */
  lang: IdPLang;

  /**
   * publish_user_events indicates whether user lifecycle events (created, updated, deleted) are enabled.
   * When enabled, events are published to the dataplane event topic.
   *
   * @generated from field: bool publish_user_events = 6;
   */
  publishUserEvents: boolean;

  /**
   * @generated from field: tailor.v1.IdPDisableGqlOperations disable_gql_operations = 7;
   */
  disableGqlOperations?: IdPDisableGqlOperations;

  /**
   * @generated from field: tailor.v1.IdPEmailConfig email_config = 8;
   */
  emailConfig?: IdPEmailConfig;

  /**
   * @generated from field: tailor.v1.IdPPermission permission = 9;
   */
  permission?: IdPPermission;
};

/**
 * Describes the message tailor.v1.IdPService.
 * Use `create(IdPServiceSchema)` to create a new message.
 */
export declare const IdPServiceSchema: GenMessage<IdPService>;

/**
 * IdPPermission defines per-operation permission policies for IDP namespaces.
 *
 * @generated from message tailor.v1.IdPPermission
 */
export declare type IdPPermission = Message<"tailor.v1.IdPPermission"> & {
  /**
   * @generated from field: repeated tailor.v1.IdPPermissionPolicy create = 1;
   */
  create: IdPPermissionPolicy[];

  /**
   * @generated from field: repeated tailor.v1.IdPPermissionPolicy read = 2;
   */
  read: IdPPermissionPolicy[];

  /**
   * @generated from field: repeated tailor.v1.IdPPermissionPolicy update = 3;
   */
  update: IdPPermissionPolicy[];

  /**
   * @generated from field: repeated tailor.v1.IdPPermissionPolicy delete = 4;
   */
  delete: IdPPermissionPolicy[];

  /**
   * @generated from field: repeated tailor.v1.IdPPermissionPolicy send_password_reset_email = 5;
   */
  sendPasswordResetEmail: IdPPermissionPolicy[];

  /**
   * unenroll_mfa policies guard the dataplane MFA-unenroll mutation, which
   * removes a single enrolled MFA factor from a user.
   *
   * @generated from field: repeated tailor.v1.IdPPermissionPolicy unenroll_mfa = 6;
   */
  unenrollMfa: IdPPermissionPolicy[];
};

/**
 * Describes the message tailor.v1.IdPPermission.
 * Use `create(IdPPermissionSchema)` to create a new message.
 */
export declare const IdPPermissionSchema: GenMessage<IdPPermission>;

/**
 * @generated from message tailor.v1.IdPPermissionPolicy
 */
export declare type IdPPermissionPolicy = Message<"tailor.v1.IdPPermissionPolicy"> & {
  /**
   * @generated from field: repeated tailor.v1.IdPPermissionCondition conditions = 1;
   */
  conditions: IdPPermissionCondition[];

  /**
   * @generated from field: tailor.v1.IdPPermissionPermit permit = 2;
   */
  permit: IdPPermissionPermit;

  /**
   * @generated from field: optional string description = 3;
   */
  description?: string;
};

/**
 * Describes the message tailor.v1.IdPPermissionPolicy.
 * Use `create(IdPPermissionPolicySchema)` to create a new message.
 */
export declare const IdPPermissionPolicySchema: GenMessage<IdPPermissionPolicy>;

/**
 * @generated from message tailor.v1.IdPPermissionCondition
 */
export declare type IdPPermissionCondition = Message<"tailor.v1.IdPPermissionCondition"> & {
  /**
   * @generated from field: tailor.v1.IdPPermissionOperand left = 1;
   */
  left?: IdPPermissionOperand;

  /**
   * @generated from field: tailor.v1.IdPPermissionOperator operator = 2;
   */
  operator: IdPPermissionOperator;

  /**
   * @generated from field: tailor.v1.IdPPermissionOperand right = 3;
   */
  right?: IdPPermissionOperand;
};

/**
 * Describes the message tailor.v1.IdPPermissionCondition.
 * Use `create(IdPPermissionConditionSchema)` to create a new message.
 */
export declare const IdPPermissionConditionSchema: GenMessage<IdPPermissionCondition>;

/**
 * @generated from message tailor.v1.IdPPermissionOperand
 */
export declare type IdPPermissionOperand = Message<"tailor.v1.IdPPermissionOperand"> & {
  /**
   * @generated from oneof tailor.v1.IdPPermissionOperand.kind
   */
  kind: {
    /**
     * @generated from field: string user_field = 1;
     */
    value: string;
    case: "userField";
  } | {
    /**
     * @generated from field: string idp_user_field = 2;
     */
    value: string;
    case: "idpUserField";
  } | {
    /**
     * @generated from field: string old_idp_user_field = 3;
     */
    value: string;
    case: "oldIdpUserField";
  } | {
    /**
     * @generated from field: string new_idp_user_field = 4;
     */
    value: string;
    case: "newIdpUserField";
  } | {
    /**
     * @generated from field: google.protobuf.Value value = 5;
     */
    value: Value;
    case: "value";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message tailor.v1.IdPPermissionOperand.
 * Use `create(IdPPermissionOperandSchema)` to create a new message.
 */
export declare const IdPPermissionOperandSchema: GenMessage<IdPPermissionOperand>;

/**
 * IdPDisableGqlOperations controls which IdP-related GraphQL operations are disabled.
 *
 * @generated from message tailor.v1.IdPDisableGqlOperations
 */
export declare type IdPDisableGqlOperations = Message<"tailor.v1.IdPDisableGqlOperations"> & {
  /**
   * create disables the _createUser GraphQL mutation.
   *
   * @generated from field: bool create = 1;
   */
  create: boolean;

  /**
   * update disables the _updateUser GraphQL mutation.
   *
   * @generated from field: bool update = 2;
   */
  update: boolean;

  /**
   * delete disables the _deleteUser GraphQL mutation.
   *
   * @generated from field: bool delete = 3;
   */
  delete: boolean;

  /**
   * read disables the _users and _user GraphQL queries.
   *
   * @generated from field: bool read = 4;
   */
  read: boolean;

  /**
   * send_password_reset_email disables the _sendPasswordResetEmail GraphQL mutation.
   *
   * @generated from field: bool send_password_reset_email = 5;
   */
  sendPasswordResetEmail: boolean;

  /**
   * request_mfa_settings_url disables the _requestMfaSettingsUrl GraphQL query.
   *
   * @generated from field: bool request_mfa_settings_url = 6;
   */
  requestMfaSettingsUrl: boolean;

  /**
   * unenroll_mfa disables the _unenrollMfa GraphQL mutation.
   *
   * @generated from field: bool unenroll_mfa = 7;
   */
  unenrollMfa: boolean;
};

/**
 * Describes the message tailor.v1.IdPDisableGqlOperations.
 * Use `create(IdPDisableGqlOperationsSchema)` to create a new message.
 */
export declare const IdPDisableGqlOperationsSchema: GenMessage<IdPDisableGqlOperations>;

/**
 * IdPEmailConfig holds namespace-level email configuration defaults.
 *
 * @generated from message tailor.v1.IdPEmailConfig
 */
export declare type IdPEmailConfig = Message<"tailor.v1.IdPEmailConfig"> & {
  /**
   * from_name is the default sender display name for emails. Empty means use mailer default.
   *
   * @generated from field: string from_name = 1;
   */
  fromName: string;

  /**
   * password_reset_subject is the default subject for password reset emails. Empty means use localized default.
   *
   * @generated from field: string password_reset_subject = 2;
   */
  passwordResetSubject: string;
};

/**
 * Describes the message tailor.v1.IdPEmailConfig.
 * Use `create(IdPEmailConfigSchema)` to create a new message.
 */
export declare const IdPEmailConfigSchema: GenMessage<IdPEmailConfig>;

/**
 * @generated from message tailor.v1.IdPClient
 */
export declare type IdPClient = Message<"tailor.v1.IdPClient"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string client_id = 2;
   */
  clientId: string;

  /**
   * @generated from field: string client_secret = 3;
   */
  clientSecret: string;
};

/**
 * Describes the message tailor.v1.IdPClient.
 * Use `create(IdPClientSchema)` to create a new message.
 */
export declare const IdPClientSchema: GenMessage<IdPClient>;

/**
 * @generated from message tailor.v1.IdPUserAuthPolicy
 */
export declare type IdPUserAuthPolicy = Message<"tailor.v1.IdPUserAuthPolicy"> & {
  /**
   * @generated from field: bool use_non_email_identifier = 1;
   */
  useNonEmailIdentifier: boolean;

  /**
   * @generated from field: bool allow_self_password_reset = 2;
   */
  allowSelfPasswordReset: boolean;

  /**
   * Password policy fields (stored in Identity Platform, not in DB)
   *
   * @generated from field: bool password_require_uppercase = 3;
   */
  passwordRequireUppercase: boolean;

  /**
   * @generated from field: bool password_require_lowercase = 4;
   */
  passwordRequireLowercase: boolean;

  /**
   * @generated from field: bool password_require_non_alphanumeric = 5;
   */
  passwordRequireNonAlphanumeric: boolean;

  /**
   * @generated from field: bool password_require_numeric = 6;
   */
  passwordRequireNumeric: boolean;

  /**
   * password_min_length: valid range is 6-30 (default: 6). When 0 (unset), uses default value 6.
   *
   * @generated from field: int32 password_min_length = 7;
   */
  passwordMinLength: number;

  /**
   * password_max_length: valid range is 6-4096 (default: 4096). When 0 (unset), uses default value 4096.
   *
   * @generated from field: int32 password_max_length = 8;
   */
  passwordMaxLength: number;

  /**
   * List of allowed email domains (e.g., ["example.com", "corp.example.com"])
   * Empty list means all domains are allowed (backward compatible)
   * Cannot be set when use_non_email_identifier is true
   *
   * @generated from field: repeated string allowed_email_domains = 9;
   */
  allowedEmailDomains: string[];

  /**
   * allow_google_oauth enables "Sign in with Google" for this namespace.
   * When enabled, users can authenticate using their Google account.
   * Cannot be enabled when use_non_email_identifier is true.
   * Requires allowed_email_domains to be set.
   *
   * @generated from field: bool allow_google_oauth = 10;
   */
  allowGoogleOauth: boolean;

  /**
   * disable_password_auth disables password-based authentication for this namespace.
   * When enabled, users cannot sign in or reset their password using email/password.
   * Requires allow_google_oauth or allow_microsoft_oauth to be enabled.
   * Cannot be used with allow_self_password_reset.
   *
   * @generated from field: bool disable_password_auth = 11;
   */
  disablePasswordAuth: boolean;

  /**
   * allow_microsoft_oauth enables "Sign in with Microsoft" for this namespace.
   * Requires disable_password_auth to be true.
   * Cannot be enabled when use_non_email_identifier is true.
   *
   * @generated from field: bool allow_microsoft_oauth = 12;
   */
  allowMicrosoftOauth: boolean;

  /**
   * enable_mfa makes TOTP MFA available for users in this namespace. When true the
   * Identity Platform tenant has mfaConfig.State=ENABLED. When false, MFA cannot
   * be enrolled or challenged regardless of require_mfa.
   *
   * @generated from field: bool enable_mfa = 13;
   */
  enableMfa: boolean;

  /**
   * require_mfa enforces TOTP MFA enrollment and challenge for password-authenticated
   * users in this namespace. OAuth (Google/Microsoft) sign-in is not affected.
   * Requires enable_mfa to be true.
   *
   * @generated from field: bool require_mfa = 14;
   */
  requireMfa: boolean;

  /**
   * allowed_return_origins lists application origins (e.g. "https://app.example.com")
   * that the IdP is allowed to redirect users back to from self-service pages such
   * as /mfa/settings. This is intentionally separate from OIDC redirect_uri, and
   * covers the general case of "send the user back to the app after an action in
   * the IdP UI". Each entry must be an origin (RFC 6454, scheme + host + optional
   * port, no path, query, or fragment). The caller's returnTo URL may freely
   * include a path and query; the matcher extracts its origin and compares against
   * this list.
   *
   * The per-item pattern is stricter than RFC 6454 by design:
   *   - host must match [a-zA-Z0-9.-]+ (DNS-friendly), so IPv6 literals
   *     (http://[::1]) and underscores in hostnames are not accepted
   *   - only http and https schemes are allowed
   *   - path / query / fragment are rejected, since matching is origin-only
   *
   * @generated from field: repeated string allowed_return_origins = 15;
   */
  allowedReturnOrigins: string[];

  /**
   * mfa_issuer is the label shown next to the user account in authenticator apps
   * (Google Authenticator, 1Password, etc.) when TOTP is enrolled. When empty the
   * server falls back to "Tailor Platform IdP".
   *
   * @generated from field: string mfa_issuer = 16;
   */
  mfaIssuer: string;
};

/**
 * Describes the message tailor.v1.IdPUserAuthPolicy.
 * Use `create(IdPUserAuthPolicySchema)` to create a new message.
 */
export declare const IdPUserAuthPolicySchema: GenMessage<IdPUserAuthPolicy>;

/**
 * @generated from enum tailor.v1.IdPPermissionOperator
 */
export enum IdPPermissionOperator {
  /**
   * @generated from enum value: ID_P_PERMISSION_OPERATOR_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: ID_P_PERMISSION_OPERATOR_EQ = 1;
   */
  EQ = 1,

  /**
   * @generated from enum value: ID_P_PERMISSION_OPERATOR_NE = 2;
   */
  NE = 2,

  /**
   * @generated from enum value: ID_P_PERMISSION_OPERATOR_IN = 3;
   */
  IN = 3,

  /**
   * @generated from enum value: ID_P_PERMISSION_OPERATOR_NIN = 4;
   */
  NIN = 4,
}

/**
 * Describes the enum tailor.v1.IdPPermissionOperator.
 */
export declare const IdPPermissionOperatorSchema: GenEnum<IdPPermissionOperator>;

/**
 * @generated from enum tailor.v1.IdPPermissionPermit
 */
export enum IdPPermissionPermit {
  /**
   * @generated from enum value: ID_P_PERMISSION_PERMIT_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: ID_P_PERMISSION_PERMIT_ALLOW = 1;
   */
  ALLOW = 1,

  /**
   * @generated from enum value: ID_P_PERMISSION_PERMIT_DENY = 2;
   */
  DENY = 2,
}

/**
 * Describes the enum tailor.v1.IdPPermissionPermit.
 */
export declare const IdPPermissionPermitSchema: GenEnum<IdPPermissionPermit>;

/**
 * IdPLang represents the IETF BCP 47 language subtag.
 *
 * @generated from enum tailor.v1.IdPLang
 */
export enum IdPLang {
  /**
   * @generated from enum value: ID_P_LANG_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: ID_P_LANG_EN = 1;
   */
  EN = 1,

  /**
   * @generated from enum value: ID_P_LANG_JA = 2;
   */
  JA = 2,
}

/**
 * Describes the enum tailor.v1.IdPLang.
 */
export declare const IdPLangSchema: GenEnum<IdPLang>;

