// @generated by protoc-gen-es v2.6.3
// @generated from file tailor/v1/telemetryrouter.proto (package tailor.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { ResourceAttributesConfig, TelemetryExport } from "./telemetryrouter_resource_pb";
import type { PageDirection } from "./resource_pb";

/**
 * Describes the file tailor/v1/telemetryrouter.proto.
 */
export declare const file_tailor_v1_telemetryrouter: GenFile;

/**
 * @generated from message tailor.v1.CreateTelemetryExportRequest
 */
export declare type CreateTelemetryExportRequest = Message<"tailor.v1.CreateTelemetryExportRequest"> & {
  /**
   * @generated from field: string workspace_id = 1;
   */
  workspaceId: string;

  /**
   * @generated from field: tailor.v1.TelemetryExport telemetry_export = 2;
   */
  telemetryExport?: TelemetryExport;
};

/**
 * Describes the message tailor.v1.CreateTelemetryExportRequest.
 * Use `create(CreateTelemetryExportRequestSchema)` to create a new message.
 */
export declare const CreateTelemetryExportRequestSchema: GenMessage<CreateTelemetryExportRequest>;

/**
 * @generated from message tailor.v1.CreateTelemetryExportResponse
 */
export declare type CreateTelemetryExportResponse = Message<"tailor.v1.CreateTelemetryExportResponse"> & {
  /**
   * @generated from field: tailor.v1.TelemetryExport telemetry_export = 1;
   */
  telemetryExport?: TelemetryExport;
};

/**
 * Describes the message tailor.v1.CreateTelemetryExportResponse.
 * Use `create(CreateTelemetryExportResponseSchema)` to create a new message.
 */
export declare const CreateTelemetryExportResponseSchema: GenMessage<CreateTelemetryExportResponse>;

/**
 * @generated from message tailor.v1.UpdateTelemetryExportRequest
 */
export declare type UpdateTelemetryExportRequest = Message<"tailor.v1.UpdateTelemetryExportRequest"> & {
  /**
   * @generated from field: string workspace_id = 1;
   */
  workspaceId: string;

  /**
   * @generated from field: tailor.v1.TelemetryExport telemetry_export = 2;
   */
  telemetryExport?: TelemetryExport;
};

/**
 * Describes the message tailor.v1.UpdateTelemetryExportRequest.
 * Use `create(UpdateTelemetryExportRequestSchema)` to create a new message.
 */
export declare const UpdateTelemetryExportRequestSchema: GenMessage<UpdateTelemetryExportRequest>;

/**
 * @generated from message tailor.v1.UpdateTelemetryExportResponse
 */
export declare type UpdateTelemetryExportResponse = Message<"tailor.v1.UpdateTelemetryExportResponse"> & {
  /**
   * @generated from field: tailor.v1.TelemetryExport telemetry_export = 1;
   */
  telemetryExport?: TelemetryExport;
};

/**
 * Describes the message tailor.v1.UpdateTelemetryExportResponse.
 * Use `create(UpdateTelemetryExportResponseSchema)` to create a new message.
 */
export declare const UpdateTelemetryExportResponseSchema: GenMessage<UpdateTelemetryExportResponse>;

/**
 * @generated from message tailor.v1.GetTelemetryExportRequest
 */
export declare type GetTelemetryExportRequest = Message<"tailor.v1.GetTelemetryExportRequest"> & {
  /**
   * @generated from field: string workspace_id = 1;
   */
  workspaceId: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;
};

/**
 * Describes the message tailor.v1.GetTelemetryExportRequest.
 * Use `create(GetTelemetryExportRequestSchema)` to create a new message.
 */
export declare const GetTelemetryExportRequestSchema: GenMessage<GetTelemetryExportRequest>;

/**
 * @generated from message tailor.v1.GetTelemetryExportResponse
 */
export declare type GetTelemetryExportResponse = Message<"tailor.v1.GetTelemetryExportResponse"> & {
  /**
   * @generated from field: tailor.v1.TelemetryExport telemetry_export = 1;
   */
  telemetryExport?: TelemetryExport;
};

/**
 * Describes the message tailor.v1.GetTelemetryExportResponse.
 * Use `create(GetTelemetryExportResponseSchema)` to create a new message.
 */
export declare const GetTelemetryExportResponseSchema: GenMessage<GetTelemetryExportResponse>;

/**
 * @generated from message tailor.v1.ListTelemetryExportsRequest
 */
export declare type ListTelemetryExportsRequest = Message<"tailor.v1.ListTelemetryExportsRequest"> & {
  /**
   * @generated from field: string workspace_id = 1;
   */
  workspaceId: string;

  /**
   * @generated from field: string page_token = 2;
   */
  pageToken: string;

  /**
   * @generated from field: uint32 page_size = 3;
   */
  pageSize: number;

  /**
   * @generated from field: tailor.v1.PageDirection page_direction = 4;
   */
  pageDirection: PageDirection;
};

/**
 * Describes the message tailor.v1.ListTelemetryExportsRequest.
 * Use `create(ListTelemetryExportsRequestSchema)` to create a new message.
 */
export declare const ListTelemetryExportsRequestSchema: GenMessage<ListTelemetryExportsRequest>;

/**
 * @generated from message tailor.v1.ListTelemetryExportsResponse
 */
export declare type ListTelemetryExportsResponse = Message<"tailor.v1.ListTelemetryExportsResponse"> & {
  /**
   * @generated from field: repeated tailor.v1.TelemetryExport telemetry_exports = 1;
   */
  telemetryExports: TelemetryExport[];

  /**
   * @generated from field: string next_page_token = 2;
   */
  nextPageToken: string;

  /**
   * @generated from field: int64 total_count = 3;
   */
  totalCount: bigint;
};

/**
 * Describes the message tailor.v1.ListTelemetryExportsResponse.
 * Use `create(ListTelemetryExportsResponseSchema)` to create a new message.
 */
export declare const ListTelemetryExportsResponseSchema: GenMessage<ListTelemetryExportsResponse>;

/**
 * @generated from message tailor.v1.DeleteTelemetryExportRequest
 */
export declare type DeleteTelemetryExportRequest = Message<"tailor.v1.DeleteTelemetryExportRequest"> & {
  /**
   * @generated from field: string workspace_id = 1;
   */
  workspaceId: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;
};

/**
 * Describes the message tailor.v1.DeleteTelemetryExportRequest.
 * Use `create(DeleteTelemetryExportRequestSchema)` to create a new message.
 */
export declare const DeleteTelemetryExportRequestSchema: GenMessage<DeleteTelemetryExportRequest>;

/**
 * @generated from message tailor.v1.DeleteTelemetryExportResponse
 */
export declare type DeleteTelemetryExportResponse = Message<"tailor.v1.DeleteTelemetryExportResponse"> & {
};

/**
 * Describes the message tailor.v1.DeleteTelemetryExportResponse.
 * Use `create(DeleteTelemetryExportResponseSchema)` to create a new message.
 */
export declare const DeleteTelemetryExportResponseSchema: GenMessage<DeleteTelemetryExportResponse>;

/**
 * @generated from message tailor.v1.TestTelemetryExportRequest
 */
export declare type TestTelemetryExportRequest = Message<"tailor.v1.TestTelemetryExportRequest"> & {
  /**
   * @generated from field: string workspace_id = 1;
   */
  workspaceId: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;
};

/**
 * Describes the message tailor.v1.TestTelemetryExportRequest.
 * Use `create(TestTelemetryExportRequestSchema)` to create a new message.
 */
export declare const TestTelemetryExportRequestSchema: GenMessage<TestTelemetryExportRequest>;

/**
 * @generated from message tailor.v1.TestTelemetryExportResponse
 */
export declare type TestTelemetryExportResponse = Message<"tailor.v1.TestTelemetryExportResponse"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;

  /**
   * @generated from field: string message = 2;
   */
  message: string;
};

/**
 * Describes the message tailor.v1.TestTelemetryExportResponse.
 * Use `create(TestTelemetryExportResponseSchema)` to create a new message.
 */
export declare const TestTelemetryExportResponseSchema: GenMessage<TestTelemetryExportResponse>;

/**
 * @generated from message tailor.v1.CreateResourceAttributesConfigRequest
 */
export declare type CreateResourceAttributesConfigRequest = Message<"tailor.v1.CreateResourceAttributesConfigRequest"> & {
  /**
   * @generated from field: string workspace_id = 1;
   */
  workspaceId: string;

  /**
   * @generated from field: tailor.v1.ResourceAttributesConfig resource_attributes_config = 2;
   */
  resourceAttributesConfig?: ResourceAttributesConfig;
};

/**
 * Describes the message tailor.v1.CreateResourceAttributesConfigRequest.
 * Use `create(CreateResourceAttributesConfigRequestSchema)` to create a new message.
 */
export declare const CreateResourceAttributesConfigRequestSchema: GenMessage<CreateResourceAttributesConfigRequest>;

/**
 * @generated from message tailor.v1.CreateResourceAttributesConfigResponse
 */
export declare type CreateResourceAttributesConfigResponse = Message<"tailor.v1.CreateResourceAttributesConfigResponse"> & {
  /**
   * @generated from field: tailor.v1.ResourceAttributesConfig resource_attributes_config = 1;
   */
  resourceAttributesConfig?: ResourceAttributesConfig;
};

/**
 * Describes the message tailor.v1.CreateResourceAttributesConfigResponse.
 * Use `create(CreateResourceAttributesConfigResponseSchema)` to create a new message.
 */
export declare const CreateResourceAttributesConfigResponseSchema: GenMessage<CreateResourceAttributesConfigResponse>;

/**
 * @generated from message tailor.v1.GetResourceAttributesConfigRequest
 */
export declare type GetResourceAttributesConfigRequest = Message<"tailor.v1.GetResourceAttributesConfigRequest"> & {
  /**
   * @generated from field: string workspace_id = 1;
   */
  workspaceId: string;
};

/**
 * Describes the message tailor.v1.GetResourceAttributesConfigRequest.
 * Use `create(GetResourceAttributesConfigRequestSchema)` to create a new message.
 */
export declare const GetResourceAttributesConfigRequestSchema: GenMessage<GetResourceAttributesConfigRequest>;

/**
 * @generated from message tailor.v1.GetResourceAttributesConfigResponse
 */
export declare type GetResourceAttributesConfigResponse = Message<"tailor.v1.GetResourceAttributesConfigResponse"> & {
  /**
   * @generated from field: tailor.v1.ResourceAttributesConfig resource_attributes_config = 1;
   */
  resourceAttributesConfig?: ResourceAttributesConfig;
};

/**
 * Describes the message tailor.v1.GetResourceAttributesConfigResponse.
 * Use `create(GetResourceAttributesConfigResponseSchema)` to create a new message.
 */
export declare const GetResourceAttributesConfigResponseSchema: GenMessage<GetResourceAttributesConfigResponse>;

/**
 * @generated from message tailor.v1.UpdateResourceAttributesConfigRequest
 */
export declare type UpdateResourceAttributesConfigRequest = Message<"tailor.v1.UpdateResourceAttributesConfigRequest"> & {
  /**
   * @generated from field: string workspace_id = 1;
   */
  workspaceId: string;

  /**
   * @generated from field: tailor.v1.ResourceAttributesConfig resource_attributes_config = 2;
   */
  resourceAttributesConfig?: ResourceAttributesConfig;
};

/**
 * Describes the message tailor.v1.UpdateResourceAttributesConfigRequest.
 * Use `create(UpdateResourceAttributesConfigRequestSchema)` to create a new message.
 */
export declare const UpdateResourceAttributesConfigRequestSchema: GenMessage<UpdateResourceAttributesConfigRequest>;

/**
 * @generated from message tailor.v1.UpdateResourceAttributesConfigResponse
 */
export declare type UpdateResourceAttributesConfigResponse = Message<"tailor.v1.UpdateResourceAttributesConfigResponse"> & {
  /**
   * @generated from field: tailor.v1.ResourceAttributesConfig resource_attributes_config = 1;
   */
  resourceAttributesConfig?: ResourceAttributesConfig;
};

/**
 * Describes the message tailor.v1.UpdateResourceAttributesConfigResponse.
 * Use `create(UpdateResourceAttributesConfigResponseSchema)` to create a new message.
 */
export declare const UpdateResourceAttributesConfigResponseSchema: GenMessage<UpdateResourceAttributesConfigResponse>;

/**
 * @generated from message tailor.v1.DeleteResourceAttributesConfigRequest
 */
export declare type DeleteResourceAttributesConfigRequest = Message<"tailor.v1.DeleteResourceAttributesConfigRequest"> & {
  /**
   * @generated from field: string workspace_id = 1;
   */
  workspaceId: string;
};

/**
 * Describes the message tailor.v1.DeleteResourceAttributesConfigRequest.
 * Use `create(DeleteResourceAttributesConfigRequestSchema)` to create a new message.
 */
export declare const DeleteResourceAttributesConfigRequestSchema: GenMessage<DeleteResourceAttributesConfigRequest>;

/**
 * @generated from message tailor.v1.DeleteResourceAttributesConfigResponse
 */
export declare type DeleteResourceAttributesConfigResponse = Message<"tailor.v1.DeleteResourceAttributesConfigResponse"> & {
};

/**
 * Describes the message tailor.v1.DeleteResourceAttributesConfigResponse.
 * Use `create(DeleteResourceAttributesConfigResponseSchema)` to create a new message.
 */
export declare const DeleteResourceAttributesConfigResponseSchema: GenMessage<DeleteResourceAttributesConfigResponse>;

