// @generated by protoc-gen-es v2.6.3
// @generated from file tailor/v1/telemetryrouter_resource.proto (package tailor.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import type { SecretValue } from "./secret_manager_resource_pb";

/**
 * Describes the file tailor/v1/telemetryrouter_resource.proto.
 */
export declare const file_tailor_v1_telemetryrouter_resource: GenFile;

/**
 * @generated from message tailor.v1.OTLPExporter
 */
export declare type OTLPExporter = Message<"tailor.v1.OTLPExporter"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: bool enabled = 2;
   */
  enabled: boolean;

  /**
   * @generated from field: string endpoint = 3;
   */
  endpoint: string;

  /**
   * @generated from field: tailor.v1.OTLPExporterProtocol protocol = 4;
   */
  protocol: OTLPExporterProtocol;

  /**
   * @generated from field: map<string, string> headers = 5;
   */
  headers: { [key: string]: string };

  /**
   * @generated from field: tailor.v1.OTLPExporterAuthConfig auth = 6;
   */
  auth?: OTLPExporterAuthConfig;

  /**
   * @generated from field: tailor.v1.TracesConfig traces = 7;
   */
  traces?: TracesConfig;

  /**
   * @generated from field: tailor.v1.MetricsConfig metrics = 8;
   */
  metrics?: MetricsConfig;

  /**
   * @generated from field: tailor.v1.LogsConfig logs = 9;
   */
  logs?: LogsConfig;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 10;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 11;
   */
  updatedAt?: Timestamp;
};

/**
 * Describes the message tailor.v1.OTLPExporter.
 * Use `create(OTLPExporterSchema)` to create a new message.
 */
export declare const OTLPExporterSchema: GenMessage<OTLPExporter>;

/**
 * @generated from message tailor.v1.TracesConfig
 */
export declare type TracesConfig = Message<"tailor.v1.TracesConfig"> & {
  /**
   * @generated from field: bool enabled = 1;
   */
  enabled: boolean;
};

/**
 * Describes the message tailor.v1.TracesConfig.
 * Use `create(TracesConfigSchema)` to create a new message.
 */
export declare const TracesConfigSchema: GenMessage<TracesConfig>;

/**
 * @generated from message tailor.v1.MetricsConfig
 */
export declare type MetricsConfig = Message<"tailor.v1.MetricsConfig"> & {
  /**
   * @generated from field: bool enabled = 1;
   */
  enabled: boolean;
};

/**
 * Describes the message tailor.v1.MetricsConfig.
 * Use `create(MetricsConfigSchema)` to create a new message.
 */
export declare const MetricsConfigSchema: GenMessage<MetricsConfig>;

/**
 * @generated from message tailor.v1.LogsConfig
 */
export declare type LogsConfig = Message<"tailor.v1.LogsConfig"> & {
  /**
   * @generated from field: bool enabled = 1;
   */
  enabled: boolean;
};

/**
 * Describes the message tailor.v1.LogsConfig.
 * Use `create(LogsConfigSchema)` to create a new message.
 */
export declare const LogsConfigSchema: GenMessage<LogsConfig>;

/**
 * @generated from message tailor.v1.OTLPExporterAuthConfig
 */
export declare type OTLPExporterAuthConfig = Message<"tailor.v1.OTLPExporterAuthConfig"> & {
  /**
   * @generated from oneof tailor.v1.OTLPExporterAuthConfig.method
   */
  method: {
    /**
     * @generated from field: tailor.v1.OTLPExporterApiKeyAuth api_key = 1;
     */
    value: OTLPExporterApiKeyAuth;
    case: "apiKey";
  } | {
    /**
     * @generated from field: tailor.v1.OTLPExporterBearerTokenAuth bearer_token = 2;
     */
    value: OTLPExporterBearerTokenAuth;
    case: "bearerToken";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message tailor.v1.OTLPExporterAuthConfig.
 * Use `create(OTLPExporterAuthConfigSchema)` to create a new message.
 */
export declare const OTLPExporterAuthConfigSchema: GenMessage<OTLPExporterAuthConfig>;

/**
 * @generated from message tailor.v1.OTLPExporterApiKeyAuth
 */
export declare type OTLPExporterApiKeyAuth = Message<"tailor.v1.OTLPExporterApiKeyAuth"> & {
  /**
   * @generated from field: string header_name = 1;
   */
  headerName: string;

  /**
   * @generated from field: tailor.v1.SecretValue secret_value = 2;
   */
  secretValue?: SecretValue;
};

/**
 * Describes the message tailor.v1.OTLPExporterApiKeyAuth.
 * Use `create(OTLPExporterApiKeyAuthSchema)` to create a new message.
 */
export declare const OTLPExporterApiKeyAuthSchema: GenMessage<OTLPExporterApiKeyAuth>;

/**
 * @generated from message tailor.v1.OTLPExporterBearerTokenAuth
 */
export declare type OTLPExporterBearerTokenAuth = Message<"tailor.v1.OTLPExporterBearerTokenAuth"> & {
  /**
   * @generated from field: tailor.v1.SecretValue secret_value = 1;
   */
  secretValue?: SecretValue;
};

/**
 * Describes the message tailor.v1.OTLPExporterBearerTokenAuth.
 * Use `create(OTLPExporterBearerTokenAuthSchema)` to create a new message.
 */
export declare const OTLPExporterBearerTokenAuthSchema: GenMessage<OTLPExporterBearerTokenAuth>;

/**
 * ResourceAttributesConfig is a workspace-level singleton that controls
 * the resource attributes enriched onto outgoing telemetry signals.
 *
 * @generated from message tailor.v1.ResourceAttributesConfig
 */
export declare type ResourceAttributesConfig = Message<"tailor.v1.ResourceAttributesConfig"> & {
  /**
   * Developer-specified prefix prepended to each microservice's own
   * service.name (e.g. "gateway", "tailordb") to form the final
   * service.name resource attribute on outgoing signals:
   * "<service_name_prefix>-<service.name>".
   *
   * @generated from field: string service_name_prefix = 1;
   */
  serviceNamePrefix: string;

  /**
   * Customer-side deployment environment (e.g. "production", "staging").
   * Optional; when empty, the enricher leaves deployment.environment.name
   * untouched. Follows OTel semconv `deployment.environment.name` semantics
   * (free-form string; max 256 chars).
   *
   * @generated from field: string deployment_environment_name = 2;
   */
  deploymentEnvironmentName: string;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 3;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 4;
   */
  updatedAt?: Timestamp;
};

/**
 * Describes the message tailor.v1.ResourceAttributesConfig.
 * Use `create(ResourceAttributesConfigSchema)` to create a new message.
 */
export declare const ResourceAttributesConfigSchema: GenMessage<ResourceAttributesConfig>;

/**
 * @generated from enum tailor.v1.OTLPExporterProtocol
 */
export enum OTLPExporterProtocol {
  /**
   * @generated from enum value: OTLP_EXPORTER_PROTOCOL_UNSPECIFIED = 0;
   */
  OTLP_EXPORTER_PROTOCOL_UNSPECIFIED = 0,

  /**
   * @generated from enum value: OTLP_EXPORTER_PROTOCOL_GRPC = 1;
   */
  OTLP_EXPORTER_PROTOCOL_GRPC = 1,

  /**
   * @generated from enum value: OTLP_EXPORTER_PROTOCOL_HTTP = 2;
   */
  OTLP_EXPORTER_PROTOCOL_HTTP = 2,
}

/**
 * Describes the enum tailor.v1.OTLPExporterProtocol.
 */
export declare const OTLPExporterProtocolSchema: GenEnum<OTLPExporterProtocol>;

