// @generated by protoc-gen-es v2.6.3
// @generated from file tailor/v1/workspace_resource.proto (package tailor.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file tailor/v1/workspace_resource.proto.
 */
export declare const file_tailor_v1_workspace_resource: GenFile;

/**
 * @generated from message tailor.v1.Organization
 */
export declare type Organization = Message<"tailor.v1.Organization"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: google.protobuf.Timestamp create_time = 3;
   */
  createTime?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp update_time = 4;
   */
  updateTime?: Timestamp;
};

/**
 * Describes the message tailor.v1.Organization.
 * Use `create(OrganizationSchema)` to create a new message.
 */
export declare const OrganizationSchema: GenMessage<Organization>;

/**
 * @generated from message tailor.v1.OrganizationAccess
 */
export declare type OrganizationAccess = Message<"tailor.v1.OrganizationAccess"> & {
  /**
   * @generated from field: string organization_id = 1;
   */
  organizationId: string;

  /**
   * @generated from field: tailor.v1.OrganizationRole role = 2;
   */
  role: OrganizationRole;

  /**
   * @generated from oneof tailor.v1.OrganizationAccess.member
   */
  member: {
    /**
     * @generated from field: tailor.v1.OrganizationAccess.Team team = 3;
     */
    value: OrganizationAccess_Team;
    case: "team";
  } | {
    /**
     * @generated from field: tailor.v1.OrganizationAccess.PlatformUser platform_user = 4;
     */
    value: OrganizationAccess_PlatformUser;
    case: "platformUser";
  } | {
    /**
     * @generated from field: tailor.v1.OrganizationAccess.MachineUser machine_user = 5;
     */
    value: OrganizationAccess_MachineUser;
    case: "machineUser";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message tailor.v1.OrganizationAccess.
 * Use `create(OrganizationAccessSchema)` to create a new message.
 */
export declare const OrganizationAccessSchema: GenMessage<OrganizationAccess>;

/**
 * @generated from message tailor.v1.OrganizationAccess.PlatformUser
 */
export declare type OrganizationAccess_PlatformUser = Message<"tailor.v1.OrganizationAccess.PlatformUser"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string email = 2;
   */
  email: string;
};

/**
 * Describes the message tailor.v1.OrganizationAccess.PlatformUser.
 * Use `create(OrganizationAccess_PlatformUserSchema)` to create a new message.
 */
export declare const OrganizationAccess_PlatformUserSchema: GenMessage<OrganizationAccess_PlatformUser>;

/**
 * @generated from message tailor.v1.OrganizationAccess.Team
 */
export declare type OrganizationAccess_Team = Message<"tailor.v1.OrganizationAccess.Team"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;
};

/**
 * Describes the message tailor.v1.OrganizationAccess.Team.
 * Use `create(OrganizationAccess_TeamSchema)` to create a new message.
 */
export declare const OrganizationAccess_TeamSchema: GenMessage<OrganizationAccess_Team>;

/**
 * @generated from message tailor.v1.OrganizationAccess.MachineUser
 */
export declare type OrganizationAccess_MachineUser = Message<"tailor.v1.OrganizationAccess.MachineUser"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;
};

/**
 * Describes the message tailor.v1.OrganizationAccess.MachineUser.
 * Use `create(OrganizationAccess_MachineUserSchema)` to create a new message.
 */
export declare const OrganizationAccess_MachineUserSchema: GenMessage<OrganizationAccess_MachineUser>;

/**
 * @generated from message tailor.v1.Folder
 */
export declare type Folder = Message<"tailor.v1.Folder"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string organization_id = 3;
   */
  organizationId: string;

  /**
   * NOTE: can be empty = top level folder in organization
   *
   * @generated from field: string parent_folder_id = 4;
   */
  parentFolderId: string;

  /**
   * @generated from field: bool has_children = 7;
   */
  hasChildren: boolean;

  /**
   * @generated from field: google.protobuf.Timestamp create_time = 5;
   */
  createTime?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp update_time = 6;
   */
  updateTime?: Timestamp;
};

/**
 * Describes the message tailor.v1.Folder.
 * Use `create(FolderSchema)` to create a new message.
 */
export declare const FolderSchema: GenMessage<Folder>;

/**
 * @generated from message tailor.v1.FolderAccess
 */
export declare type FolderAccess = Message<"tailor.v1.FolderAccess"> & {
  /**
   * @generated from field: string folder_id = 1;
   */
  folderId: string;

  /**
   * @generated from field: tailor.v1.FolderRole role = 2;
   */
  role: FolderRole;

  /**
   * @generated from oneof tailor.v1.FolderAccess.member
   */
  member: {
    /**
     * @generated from field: tailor.v1.FolderAccess.Team team = 3;
     */
    value: FolderAccess_Team;
    case: "team";
  } | {
    /**
     * @generated from field: tailor.v1.FolderAccess.PlatformUser platform_user = 4;
     */
    value: FolderAccess_PlatformUser;
    case: "platformUser";
  } | {
    /**
     * @generated from field: tailor.v1.FolderAccess.MachineUser machine_user = 5;
     */
    value: FolderAccess_MachineUser;
    case: "machineUser";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message tailor.v1.FolderAccess.
 * Use `create(FolderAccessSchema)` to create a new message.
 */
export declare const FolderAccessSchema: GenMessage<FolderAccess>;

/**
 * @generated from message tailor.v1.FolderAccess.PlatformUser
 */
export declare type FolderAccess_PlatformUser = Message<"tailor.v1.FolderAccess.PlatformUser"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string email = 2;
   */
  email: string;
};

/**
 * Describes the message tailor.v1.FolderAccess.PlatformUser.
 * Use `create(FolderAccess_PlatformUserSchema)` to create a new message.
 */
export declare const FolderAccess_PlatformUserSchema: GenMessage<FolderAccess_PlatformUser>;

/**
 * @generated from message tailor.v1.FolderAccess.Team
 */
export declare type FolderAccess_Team = Message<"tailor.v1.FolderAccess.Team"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;
};

/**
 * Describes the message tailor.v1.FolderAccess.Team.
 * Use `create(FolderAccess_TeamSchema)` to create a new message.
 */
export declare const FolderAccess_TeamSchema: GenMessage<FolderAccess_Team>;

/**
 * @generated from message tailor.v1.FolderAccess.MachineUser
 */
export declare type FolderAccess_MachineUser = Message<"tailor.v1.FolderAccess.MachineUser"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;
};

/**
 * Describes the message tailor.v1.FolderAccess.MachineUser.
 * Use `create(FolderAccess_MachineUserSchema)` to create a new message.
 */
export declare const FolderAccess_MachineUserSchema: GenMessage<FolderAccess_MachineUser>;

/**
 * @generated from message tailor.v1.Team
 */
export declare type Team = Message<"tailor.v1.Team"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string organization_id = 3;
   */
  organizationId: string;

  /**
   * @generated from field: google.protobuf.Timestamp create_time = 4;
   */
  createTime?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp update_time = 5;
   */
  updateTime?: Timestamp;
};

/**
 * Describes the message tailor.v1.Team.
 * Use `create(TeamSchema)` to create a new message.
 */
export declare const TeamSchema: GenMessage<Team>;

/**
 * @generated from message tailor.v1.TeamMember
 */
export declare type TeamMember = Message<"tailor.v1.TeamMember"> & {
  /**
   * @generated from field: string team_id = 1;
   */
  teamId: string;

  /**
   * @generated from field: tailor.v1.TeamMember.PlatformUser platform_user = 2;
   */
  platformUser?: TeamMember_PlatformUser;

  /**
   * @generated from field: tailor.v1.TeamRole role = 3;
   */
  role: TeamRole;
};

/**
 * Describes the message tailor.v1.TeamMember.
 * Use `create(TeamMemberSchema)` to create a new message.
 */
export declare const TeamMemberSchema: GenMessage<TeamMember>;

/**
 * @generated from message tailor.v1.TeamMember.PlatformUser
 */
export declare type TeamMember_PlatformUser = Message<"tailor.v1.TeamMember.PlatformUser"> & {
  /**
   * @generated from field: string user_id = 1;
   */
  userId: string;

  /**
   * @generated from field: string email = 2;
   */
  email: string;
};

/**
 * Describes the message tailor.v1.TeamMember.PlatformUser.
 * Use `create(TeamMember_PlatformUserSchema)` to create a new message.
 */
export declare const TeamMember_PlatformUserSchema: GenMessage<TeamMember_PlatformUser>;

/**
 * @generated from message tailor.v1.Workspace
 */
export declare type Workspace = Message<"tailor.v1.Workspace"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string create_user_id = 3;
   */
  createUserId: string;

  /**
   * @generated from field: string update_user_id = 4;
   */
  updateUserId: string;

  /**
   * @generated from field: google.protobuf.Timestamp create_time = 5;
   */
  createTime?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp update_time = 6;
   */
  updateTime?: Timestamp;

  /**
   * @generated from field: string region = 8;
   */
  region: string;

  /**
   * @generated from field: bool delete_protection = 9;
   */
  deleteProtection: boolean;

  /**
   * @generated from field: string organization_id = 10;
   */
  organizationId: string;

  /**
   * @generated from field: string folder_id = 11;
   */
  folderId: string;
};

/**
 * Describes the message tailor.v1.Workspace.
 * Use `create(WorkspaceSchema)` to create a new message.
 */
export declare const WorkspaceSchema: GenMessage<Workspace>;

/**
 * @generated from message tailor.v1.WorkspacePlatformUser
 */
export declare type WorkspacePlatformUser = Message<"tailor.v1.WorkspacePlatformUser"> & {
  /**
   * @generated from field: tailor.v1.WorkspacePlatformUserRole role = 1;
   */
  role: WorkspacePlatformUserRole;

  /**
   * @generated from field: tailor.v1.WorkspacePlatformUser.PlatformUser platform_user = 2;
   */
  platformUser?: WorkspacePlatformUser_PlatformUser;
};

/**
 * Describes the message tailor.v1.WorkspacePlatformUser.
 * Use `create(WorkspacePlatformUserSchema)` to create a new message.
 */
export declare const WorkspacePlatformUserSchema: GenMessage<WorkspacePlatformUser>;

/**
 * @generated from message tailor.v1.WorkspacePlatformUser.PlatformUser
 */
export declare type WorkspacePlatformUser_PlatformUser = Message<"tailor.v1.WorkspacePlatformUser.PlatformUser"> & {
  /**
   * @generated from field: string user_id = 1;
   */
  userId: string;

  /**
   * @generated from field: string email = 2;
   */
  email: string;
};

/**
 * Describes the message tailor.v1.WorkspacePlatformUser.PlatformUser.
 * Use `create(WorkspacePlatformUser_PlatformUserSchema)` to create a new message.
 */
export declare const WorkspacePlatformUser_PlatformUserSchema: GenMessage<WorkspacePlatformUser_PlatformUser>;

/**
 * @generated from message tailor.v1.PlatformAccountPlan
 */
export declare type PlatformAccountPlan = Message<"tailor.v1.PlatformAccountPlan"> & {
  /**
   * @generated from field: tailor.v1.PlatformAccountPlanType plan_type = 1;
   */
  planType: PlatformAccountPlanType;

  /**
   * @generated from oneof tailor.v1.PlatformAccountPlan.plan_meta
   */
  planMeta: {
    /**
     * @generated from field: tailor.v1.PlatformAccountPlan.PlatformAccountPlanTrial trial = 2;
     */
    value: PlatformAccountPlan_PlatformAccountPlanTrial;
    case: "trial";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message tailor.v1.PlatformAccountPlan.
 * Use `create(PlatformAccountPlanSchema)` to create a new message.
 */
export declare const PlatformAccountPlanSchema: GenMessage<PlatformAccountPlan>;

/**
 * @generated from message tailor.v1.PlatformAccountPlan.PlatformAccountPlanTrial
 */
export declare type PlatformAccountPlan_PlatformAccountPlanTrial = Message<"tailor.v1.PlatformAccountPlan.PlatformAccountPlanTrial"> & {
  /**
   * @generated from field: google.protobuf.Timestamp start_at = 1;
   */
  startAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp end_at = 2;
   */
  endAt?: Timestamp;

  /**
   * @generated from field: bool is_expired = 3;
   */
  isExpired: boolean;
};

/**
 * Describes the message tailor.v1.PlatformAccountPlan.PlatformAccountPlanTrial.
 * Use `create(PlatformAccountPlan_PlatformAccountPlanTrialSchema)` to create a new message.
 */
export declare const PlatformAccountPlan_PlatformAccountPlanTrialSchema: GenMessage<PlatformAccountPlan_PlatformAccountPlanTrial>;

/**
 * @generated from enum tailor.v1.OrganizationRole
 */
export enum OrganizationRole {
  /**
   * @generated from enum value: ORGANIZATION_ROLE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: ORGANIZATION_ROLE_ADMIN = 1;
   */
  ADMIN = 1,

  /**
   * @generated from enum value: ORGANIZATION_ROLE_EDITOR = 2;
   */
  EDITOR = 2,

  /**
   * @generated from enum value: ORGANIZATION_ROLE_VIEWER = 3;
   */
  VIEWER = 3,
}

/**
 * Describes the enum tailor.v1.OrganizationRole.
 */
export declare const OrganizationRoleSchema: GenEnum<OrganizationRole>;

/**
 * @generated from enum tailor.v1.FolderRole
 */
export enum FolderRole {
  /**
   * @generated from enum value: FOLDER_ROLE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: FOLDER_ROLE_ADMIN = 1;
   */
  ADMIN = 1,

  /**
   * @generated from enum value: FOLDER_ROLE_EDITOR = 2;
   */
  EDITOR = 2,

  /**
   * @generated from enum value: FOLDER_ROLE_VIEWER = 3;
   */
  VIEWER = 3,
}

/**
 * Describes the enum tailor.v1.FolderRole.
 */
export declare const FolderRoleSchema: GenEnum<FolderRole>;

/**
 * @generated from enum tailor.v1.TeamRole
 */
export enum TeamRole {
  /**
   * @generated from enum value: TEAM_ROLE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: TEAM_ROLE_ADMIN = 1;
   */
  ADMIN = 1,

  /**
   * @generated from enum value: TEAM_ROLE_MANAGER = 2;
   */
  MANAGER = 2,

  /**
   * @generated from enum value: TEAM_ROLE_MEMBER = 3;
   */
  MEMBER = 3,
}

/**
 * Describes the enum tailor.v1.TeamRole.
 */
export declare const TeamRoleSchema: GenEnum<TeamRole>;

/**
 * @generated from enum tailor.v1.WorkspacePlatformUserRole
 */
export enum WorkspacePlatformUserRole {
  /**
   * @generated from enum value: WORKSPACE_PLATFORM_USER_ROLE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: WORKSPACE_PLATFORM_USER_ROLE_ADMIN = 1;
   */
  ADMIN = 1,

  /**
   * @generated from enum value: WORKSPACE_PLATFORM_USER_ROLE_EDITOR = 2;
   */
  EDITOR = 2,

  /**
   * @generated from enum value: WORKSPACE_PLATFORM_USER_ROLE_VIEWER = 3;
   */
  VIEWER = 3,
}

/**
 * Describes the enum tailor.v1.WorkspacePlatformUserRole.
 */
export declare const WorkspacePlatformUserRoleSchema: GenEnum<WorkspacePlatformUserRole>;

/**
 * @generated from enum tailor.v1.PlatformAccountPlanType
 */
export enum PlatformAccountPlanType {
  /**
   * @generated from enum value: PLATFORM_ACCOUNT_PLAN_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: PLATFORM_ACCOUNT_PLAN_TYPE_TRIAL = 1;
   */
  TRIAL = 1,

  /**
   * @generated from enum value: PLATFORM_ACCOUNT_PLAN_TYPE_BASIC = 2;
   */
  BASIC = 2,
}

/**
 * Describes the enum tailor.v1.PlatformAccountPlanType.
 */
export declare const PlatformAccountPlanTypeSchema: GenEnum<PlatformAccountPlanType>;

