// Zinfer-generated types
export type {
  AuthInvoker,
  OIDC,
  SAMLInput,
  SAML,
  IDToken,
  BuiltinIdP,
  IdProviderInput,
  IdProvider as IdProviderConfig,
  OAuth2ClientGrantType,
  OAuth2ClientInput,
  OAuth2Client,
  SCIMAuthorization,
  SCIMAttributeType,
  SCIMAttributeInput,
  SCIMAttribute,
  SCIMAttributeMapping,
  SCIMResource,
  SCIMConfigInput,
  SCIMConfig,
  TenantProvider as TenantProviderConfig,
  AuthConfigInput,
  AuthConfig as AuthConfigOutput,
} from "@/types/auth";

// Manual types
export type {
  AuthInvokerWithName,
  ValueOperand,
  AuthAttributeValue,
  UsernameFieldKey,
  UserAttributeKey,
  UserAttributeListKey,
  UserAttributeMap,
  AuthServiceInput,
  AuthDefinitionBrand,
  DefinedAuth,
  AuthExternalConfig,
  AuthOwnConfig,
  AuthConfig,
} from "@/types/auth.manual";
