// This file is auto-generated by @tailor-platform/sdk
// Do not edit this file manually
// Regenerated automatically when running 'tailor-sdk apply' or 'tailor-sdk generate'

declare module "@tailor-platform/sdk" {
  interface AttributeMap {
    role: string;
  }
  interface AttributeList {
    __tuple?: [];
  }
  interface Env {
    appName: "Resolver Template";
    version: 1;
  }
  interface MachineUserNameRegistry {
    admin: true;
  }
  interface IdpNameRegistry {}
}

export {};
