const siteName = "portal";
const setup = `pnpm tailor staticwebsite deploy --name ${siteName}`;
const deploy = "tailor deploy";
const envFileDeploy = "tailor --env-file .env deploy";
const profileValue = "tailor --profile tailor-sdk deploy";
const help = "tailor --help";
const npxVersion = "npx tailor-sdk --version";
const generated = "Run tailor generate after changes";
const dynamicCommand = `tailor ${subcommand}`;
const dynamicPnpmCommand = `pnpm tailor ${subcommand}`;
const dynamicProfileCommand = `tailor --profile ${profile} deploy`;
const indentedDynamicCommand = `
  tailor ${subcommand}`;
const latest = "npx tailor-sdk@latest login";
const npxPackageFlag = "npx -p tailor-sdk tailor-sdk login";
const npxPackageFlagEquals = "npx --package=tailor-sdk tailor-sdk login";
const packageName = "tailor-sdk";
const packageMessage = "package tailor-sdk is installed";
const mixedPackageAndCommand = "Install tailor-sdk before running tailor deploy";
const outputDir = ".tailor-sdk/";
const scaffold = "create-tailor-sdk";
const skills = "tailor-sdk-skills install";
