const siteName = "portal";
const setup = `pnpm tailor staticwebsite deploy --name ${siteName}`;
const deploy = "tailor deploy";
const envFileDeploy = "tailor --env-file .env deploy";
const profileValue = "tailor --profile tailor-sdk deploy";
const help = "tailor --help";
const npxVersion = "npx @tailor-platform/sdk --version";
const generated = "Run tailor generate after changes";
const dynamicCommand = `tailor ${subcommand}`;
const dynamicPnpmCommand = `pnpm tailor ${subcommand}`;
const dynamicProfileCommand = `tailor --profile ${profile} deploy`;
const dynamicEqualsProfileCommand = `tailor --profile=${profile} deploy`;
const dynamicEqualsWorkspaceCommand = `tailor --workspace-id=${workspaceId} deploy`;
const indentedDynamicCommand = `
  tailor ${subcommand}`;
const latest = "npx @tailor-platform/sdk@latest login";
const latestOnly = "npx @tailor-platform/sdk@latest";
const latestWithRunnerOption = "npx --yes @tailor-platform/sdk@latest login";
const dynamicNpxCommand = `npx @tailor-platform/sdk ${subcommand}`;
const dynamicBunxCommand = `bunx @tailor-platform/sdk ${subcommand}`;
const dynamicDlxCommand = `pnpm dlx @tailor-platform/sdk ${subcommand}`;
const pnpmDlxWithOption = "pnpm --silent dlx @tailor-platform/sdk login";
const yarnDlxWithOption = "yarn --quiet dlx @tailor-platform/sdk login";
const npxPackageFlag = "npx -p @tailor-platform/sdk tailor login";
const npxPackageFlagEquals = "npx --package=@tailor-platform/sdk tailor login";
const npxPackageFlagDynamic = `npx -p @tailor-platform/sdk tailor ${subcommand}`;
const npxPackageEqualsDynamic = `npx --package=@tailor-platform/sdk tailor ${subcommand}`;
const npxRegistryPackageFlag = "npx --registry https://registry.npmjs.org -p @tailor-platform/sdk tailor login";
const npxProfileValue = "npx @tailor-platform/sdk -p tailor-sdk login";
const escapedArg = "tailor --arg \"tailor-sdk deploy\" deploy";
const packageName = "tailor-sdk";
const packageMessage = "package tailor-sdk is installed";
const mixedPackageAndCommand = "Install tailor-sdk before running tailor deploy";
const outputDir = ".tailor-sdk/";
const scaffold = "create-tailor-sdk";
const skills = "tailor-sdk-skills install";
