const siteName = "portal";
const setup = `pnpm tailor staticwebsite deploy --name ${siteName}`;
const deploy = "tailor deploy";
const dynamicCommand = `tailor ${subcommand}`;
const dynamicCommandAfterSeparator = `cd app && tailor ${subcommand}`;
const dynamicCommandAfterEnv = `env FOO=bar tailor ${subcommand}`;
const dynamicCommandAfterAssignment = `TAILOR=1 tailor ${subcommand}`;
const dynamicPnpmCommand = `pnpm tailor ${subcommand}`;
const dynamicPnpmExecCommand = `pnpm exec tailor ${subcommand}`;
const dynamicCommandWithFlags = `tailor ${flags} deploy`;
const dynamicCommandWithConditionalFlags = `tailor ${useJson ? "--json" : ""} deploy`;
const profileValue = "tailor --profile tailor-sdk deploy";
const shortProfileValue = "tailor -p tailor-sdk deploy";
const latest = "npx @tailor-platform/sdk@latest login";
const cacheRunner = "npx --cache .npm @tailor-platform/sdk login";
const registryRunner = "npx --registry=https://npm.example/tailor-sdk @tailor-platform/sdk login";
const pnpmOptionRunner = "pnpm --dir . dlx @tailor-platform/sdk login";
const inlineBooleanFlagRunner = "npx --yes=true @tailor-platform/sdk login";
const packageOptionRunner = "npx --package=@tailor-platform/sdk tailor login";
const separatePackageOptionRunner = "npx --package @tailor-platform/sdk tailor login";
const separatePackageOptionTemplate = `npx --package @tailor-platform/sdk tailor login`;
const quotedPackageOptionRunner = 'npx --package="@tailor-platform/sdk" tailor login';
const dynamicPackageOptionRunner = `npx --package=${useLocal ? "@tailor-platform/sdk" : pkg} tailor login`;
const dynamicSeparatePackageOptionRunner = `npx ${useLocal ? "--package" : ""} ${useLocal ? "@tailor-platform/sdk" : pkg} tailor login`;
const dynamicPackageOptionCommand = `npx --package @tailor-platform/sdk tailor ${subcommand}`;
const dynamicInlinePackageOptionCommand = `npx --package=${pkg} tailor ${subcommand}`;
const dynamicFlagStaticTemplate = `npx ${yes ? "-y" : ""} @tailor-platform/sdk login`;
const dynamicFlagConditionTemplate = `npx ${mode === "prod" ? "-y" : "--yes"} @tailor-platform/sdk login`;
const dynamicDlxValueFlagTemplate = `pnpm ${use ? "--filter" : ""} app dlx @tailor-platform/sdk login`;
const dynamicDlxInlineValueFlagTemplate = `pnpm ${use ? "--filter=tailor-sdk" : ""} dlx @tailor-platform/sdk login`;
const packageConditionTemplate = `npx ${pkg === "tailor-sdk" ? pkg : "@tailor-platform/sdk"} login`;
const quotedCacheTemplate = `npx --cache 'tailor-sdk/${cache}' @tailor-platform/sdk login`;
const quotedRegistryTemplate = `npx --registry "https://npm.example/tailor-sdk/${scope}" @tailor-platform/sdk login`;
const cacheValue = "npx --cache tailor-sdk some-package";
const outputDir = ".tailor-sdk/";
const scaffold = "create-tailor-sdk";
const skills = "tailor-sdk-skills install";
const proseTemplate = `package tailor-sdk ${version}`;
