const siteName = "portal";
const setup = `pnpm tailor-sdk staticwebsite deploy --name ${siteName}`;
const deploy = "tailor-sdk deploy";
const envFileDeploy = "tailor-sdk --env-file .env deploy";
const profileValue = "tailor-sdk --profile tailor-sdk deploy";
const pnpmExecProfileValue = "pnpm exec tailor-sdk --profile tailor-sdk deploy";
const yarnExecProfileValue = "yarn exec tailor-sdk --profile tailor-sdk deploy";
const nameValue = "tailor tailordb migration generate --name \"tailor-sdk deploy\"";
const directNameValue = "tailor-sdk tailordb migration generate --name \"tailor-sdk deploy\"";
const namespaceValue = "tailor tailordb truncate --namespace tailor-sdk";
const dirValue = "tailor staticwebsite deploy --name site --dir tailor-sdk";
const pathQualifiedArgValue = "./node_modules/.bin/tailor-sdk --arg \"tailor-sdk deploy\" deploy";
const pathQualifiedCliRenameCommand = "./node_modules/.bin/tailor-sdk apply";
const help = "tailor-sdk --help";
const npxVersion = "npx tailor-sdk --version";
const generated = "Run tailor-sdk generate after changes";
const cliRenameCommand = "tailor-sdk crash-report list";
const cliRenameFlag = "tailor-sdk login --machineuser";
const shellWrappedCliRenameCommand = "sh -c \"tailor-sdk apply\"";
const dynamicCommand = `tailor-sdk ${subcommand}`;
const dynamicCliRenameCommand = `tailor-sdk ${"apply"}`;
const dynamicCommandWithTrailingFlag = `tailor-sdk ${subcommand} --json`;
const dynamicCommandBeforeSeparator = `tailor-sdk ${subcommand} && echo done`;
const dynamicPnpmCommand = `pnpm tailor-sdk ${subcommand}`;
const dynamicPnpmCommandBeforePipe = `pnpm tailor-sdk ${subcommand} | jq`;
const dynamicProfileCommand = `tailor-sdk --profile ${profile} deploy`;
const dynamicEqualsProfileCommand = `tailor-sdk --profile=${profile} deploy`;
const dynamicEqualsWorkspaceCommand = `tailor-sdk --workspace-id=${workspaceId} deploy`;
const indentedDynamicCommand = `
  tailor-sdk ${subcommand}`;
const latest = "npx tailor-sdk@latest login";
const latestOnly = "npx tailor-sdk@latest";
const latestWithRunnerOption = "npx --yes tailor-sdk@latest login";
const dynamicNpxCommand = `npx tailor-sdk ${subcommand}`;
const dynamicNpxRegistryCommand = `npx --registry ${registry} tailor-sdk login`;
const dynamicRunnerCommand = `${runner} tailor-sdk login`;
const literalPlaceholderCommand = `prefix __TAILOR_SDK_TEMPLATE_EXPR_0__ tailor-sdk ${subcommand}`;
const npxOtherPackage = "npx foo tailor-sdk login";
const npxOtherPackageFlag = "npx foo -p tailor-sdk tailor-sdk login";
const npxOtherPackageFlagEquals = "npx foo --package=tailor-sdk tailor-sdk login";
const npxQuotedPackage = "npx \"tailor-sdk\" login";
const dynamicBunxCommand = `bunx tailor-sdk ${subcommand}`;
const dynamicDlxCommand = `pnpm dlx tailor-sdk ${subcommand}`;
const pnpmDlxWithOption = "pnpm --silent dlx tailor-sdk login";
const pnpmDlxWithOptionValue = "pnpm --filter app dlx tailor-sdk login";
const pnpmFilterNamedDlxCommand = "pnpm --filter dlx tailor-sdk deploy";
const pnpmDlxAfterFilterNamedDlx = "pnpm --filter dlx dlx tailor-sdk login";
const dynamicPnpmDlxWithOptionValue = `pnpm --filter ${app} dlx tailor-sdk login`;
const yarnDlxWithOption = "yarn --quiet dlx tailor-sdk login";
const nestedCommand = `run ${"tailor-sdk deploy"}`;
const nestedTailorCommand = `tailor deploy ${"tailor-sdk login"}`;
const nestedArgValue = `tailor-sdk --arg ${"tailor-sdk deploy"} deploy`;
const nestedInlineArgValue = `tailor-sdk --arg=${"tailor-sdk deploy"} deploy`;
const npxPackageFlag = "npx -p tailor-sdk tailor-sdk login";
const npxMultiPackageFlag = "npx -p tailor-sdk -p dotenv-cli tailor-sdk login";
const npxMultiPackageFlagSecond = "npx -p dotenv-cli -p tailor-sdk tailor-sdk login";
const npxPackageFlagWithRunnerOption = "npx --package tailor-sdk --yes tailor-sdk login";
const npxPackageSplitOnly = "npx --package tailor-sdk";
const npxPackageSplitHelp = "npx -p tailor-sdk --help";
const npxPackageFlagEquals = "npx --package=tailor-sdk tailor-sdk login";
const npxPackageSingleQuoted = "npx --package 'tailor-sdk' tailor-sdk login";
const npxPackageDoubleQuoted = "npx --package \"tailor-sdk\" tailor-sdk login";
const npxPackageEqualsDoubleQuoted = "npx --package=\"tailor-sdk\" tailor-sdk login";
const npxPackageFlagDynamic = `npx -p tailor-sdk tailor-sdk ${subcommand}`;
const npxPackageEqualsDynamic = `npx --package=tailor-sdk tailor-sdk ${subcommand}`;
const npxRegistryValue = "npx --registry tailor-sdk tailor-sdk login";
const npxRegistryPackageFlag = "npx --registry https://registry.npmjs.org -p tailor-sdk tailor-sdk login";
const npxProfileValue = "npx tailor-sdk -p tailor-sdk login";
const pnpmDlxPackageFlag = "pnpm dlx --package tailor-sdk tailor-sdk login";
const pnpmDlxPackageFlagEquals = "pnpm dlx --package=tailor-sdk tailor-sdk login";
const yarnDlxPackageFlag = "yarn dlx --package tailor-sdk tailor-sdk login";
const pnpmDlxOtherPackageFlag = "pnpm dlx foo -p tailor-sdk tailor-sdk login";
const npxOtherPackageQuoted = "npx foo \"tailor-sdk login\"";
const npxOtherPackageSingleQuoted = "npx foo 'tailor-sdk login'";
const shellWrapped = "sh -c \"tailor-sdk deploy\"";
const escapedArg = "tailor-sdk --arg \"tailor-sdk deploy\" deploy";
const packageName = "tailor-sdk";
const packageMessage = "package tailor-sdk is installed";
const mixedPackageAndCommand = "Install tailor-sdk before running tailor-sdk deploy";
const outputDir = ".tailor-sdk/";
const scaffold = "create-tailor-sdk";
const skills = "tailor-sdk-skills install";
