minimumReleaseAge: 4320 # 3 days

packages:
  - packages/*
  - packages/create-sdk/templates/*
  - example

allowBuilds:
  "@swc/core": true
  esbuild: true
  lefthook: true
  multiline-ts: true
  oxc-resolver: true
