import * as fs from "node:fs";
import * as path from "pathe";
import { logBetaWarning } from "#/cli/shared/beta";
import { logger, styles } from "#/cli/shared/logger";
import { prompt } from "#/cli/shared/prompt";
import { resolveWithinRoot } from "./check";
import { LOCK_VERSION, readLock, writeLock, type LockTarget } from "./lock";

export type DeleteOptions = {
  /** Repo-relative paths to managed workflow/action files, as printed by `setup <target>`. */
  files: string[];
  /** Skip the confirmation prompt. */
  yes: boolean;
  outputDir: string;
};

// Mirrors the --dir normalization in generate.ts's resolve(): POSIX separators,
// collapsed duplicate slashes, no leading "./" or trailing "/", so a path typed
// with either style still matches the posix-normalized `file` recorded in the lock.
function normalizeRelPath(input: string): string {
  return input
    .replaceAll("\\", "/")
    .replace(/\/{2,}/g, "/")
    .replace(/^\.\//, "")
    .replace(/\/$/, "");
}

type Match = { relPath: string; absPath: string; target: LockTarget };

function targetKey(target: LockTarget): string {
  return `${target.kind}:${target.workspaceName}`;
}

function resolveMatch(outputDir: string, targets: readonly LockTarget[], input: string): Match {
  const relPath = normalizeRelPath(input);
  const absPath = resolveWithinRoot(outputDir, relPath);
  if (absPath === null) {
    throw new Error(`"${input}" must be a path inside the repository.`);
  }
  const target = targets.find((t) => t.file === relPath);
  if (!target) {
    throw new Error(
      `"${relPath}" is not a managed workflow/action file (not recorded in .github/tailor-sdk.lock). ` +
        "Only files generated by `tailor-sdk setup` can be deleted with this command.",
    );
  }
  return { relPath, absPath, target };
}

// Skips the warning when the referencing coordinator is also part of this
// delete call, regardless of the order the files were passed in.
function warnCoordinatorReferences(
  allTargets: readonly LockTarget[],
  deletedKeys: ReadonlySet<string>,
  match: Match,
): void {
  if (match.target.kind !== "action") return;
  for (const coordinator of allTargets) {
    if (
      coordinator.kind === "coordinate" &&
      coordinator.inputs.actionDirs?.includes(match.target.inputs.dir) &&
      !deletedKeys.has(targetKey(coordinator))
    ) {
      logger.warn(
        `Coordinator "${coordinator.workspaceName}" still references this action's directory ` +
          `(${match.target.inputs.dir}). Re-run \`tailor-sdk setup coordinate\` without ` +
          `--action ${match.target.workspaceName} to remove it there too.`,
      );
    }
  }
}

/**
 * Delete managed workflow/action files and their `.github/tailor-sdk.lock` entries.
 *
 * Refuses to touch files that are not recorded in the lock, so it never
 * deletes hand-written workflows or the user-owned tailor-setup action.
 * @param options - Delete options
 */
export async function setupDelete(options: DeleteOptions): Promise<void> {
  logBetaWarning("setup");

  const { outputDir, yes } = options;
  const lock = readLock(outputDir);
  if (!lock || lock.targets.length === 0) {
    throw new Error(
      "No managed workflows found (.github/tailor-sdk.lock is missing or empty). " +
        "Run `tailor-sdk setup branch` (or another setup subcommand) first.",
    );
  }

  const relPaths = [...new Set(options.files.map(normalizeRelPath))];
  const matches = relPaths.map((relPath) => resolveMatch(outputDir, lock.targets, relPath));

  const deletedKeys = new Set(matches.map((m) => targetKey(m.target)));
  for (const match of matches) {
    warnCoordinatorReferences(lock.targets, deletedKeys, match);
  }

  if (!yes) {
    const list = matches.map((m) => m.relPath).join("\n  ");
    const confirmed = await prompt.confirm({
      message:
        `This will delete the following file(s) and their .github/tailor-sdk.lock entries:\n  ${list}\n` +
        "Continue?",
      default: false,
    });
    if (!confirmed) {
      logger.info("Delete cancelled.");
      return;
    }
  }

  const remaining = [...lock.targets];
  try {
    for (const { relPath, absPath, target } of matches) {
      fs.rmSync(absPath, { force: true });
      if (target.kind === "action") {
        const dir = path.dirname(absPath);
        if (fs.existsSync(dir) && fs.readdirSync(dir).length === 0) {
          fs.rmdirSync(dir);
        }
      }
      const index = remaining.findIndex((t) => targetKey(t) === targetKey(target));
      if (index !== -1) remaining.splice(index, 1);
      logger.success(`Deleted ${styles.path(relPath)} (${target.kind} ${target.workspaceName})`);
    }
  } finally {
    if (remaining.length !== lock.targets.length) {
      writeLock(outputDir, { version: LOCK_VERSION, targets: remaining });
    }
  }
}
