locale: en
repository: ${GITHUB_REPOSITORY}/packages/sdk

coverage:
  paths:
    - coverage/lcov.info

codeToTestRatio:
  code:
    - src/**/*.ts
  test:
    - src/**/*.test.ts

testExecutionTime:
  if: false

report:
  if: is_default_branch
  datastores:
    - artifact://${GITHUB_REPOSITORY}/sdk/coverage

diff:
  datastores:
    - artifact://${GITHUB_REPOSITORY}/sdk/coverage

comment:
  if: is_pull_request

summary:
  if: true
