locale: en
repository: ${GITHUB_REPOSITORY}/packages/sdk

coverage:
  paths:
    - coverage/lcov.info

codeToTestRatio:
  if: false

testExecutionTime:
  if: false

report:
  if: is_default_branch
  datastores:
    - artifact://${GITHUB_REPOSITORY}/octocov-report-sdk-test-coverage

diff:
  datastores:
    - artifact://${GITHUB_REPOSITORY}/octocov-report-sdk-test-coverage

comment:
  if: is_pull_request

summary:
  if: true
