entityDependencies:
  Customer: []
  Deleted_Customer: []
  CustomerHistory: []
  Invoice: [SalesOrder]
  NestedProfile: []
  PurchaseOrder: [Supplier]
  SalesOrder: [Customer]
  SalesOrderCreated: []
  Selfie: []
  Supplier: []
  User: []
  UserChangeRequest: [User]
  UserChangeStep: [UserChangeRequest]
  UserChangeApproval: [UserChangeRequest]
  UserChangeReworkEvent: [UserChangeRequest]
  UserLog: [User]
  UserSetting: [User]
  AuditLog: []
  Event: []
  _User: [User]
