name: Install deps
description: Install dependencies

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
      name: Install pnpm
      with:
        standalone: true
        run_install: false

    - name: Install Node.js
      run: pnpm env use --global 24
      shell: bash

    - name: Install dependencies
      run: pnpm install
      shell: bash

    # Build SDK so that the bin entry points to a real dist file
    - name: Build SDK package
      run: pnpm exec turbo run build --filter @tailor-platform/sdk
      shell: bash

    # Recreate .bin links after build
    - name: Re-install to create bin links
      run: pnpm install --frozen-lockfile
      shell: bash
