name: Install deps
description: Install dependencies

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
      name: Install pnpm
      with:
        run_install: false

    - name: Install Node.js
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version: 22
        cache: "pnpm"

    - name: Install dependencies
      run: pnpm install
      shell: bash

    # Build SDK so that the bin entry points to a real dist file
    - name: Build SDK package
      run: pnpm exec turbo run build --filter @tailor-platform/tailor-sdk
      shell: bash

    # Recreate .bin links after build
    - name: Re-install to create bin links
      run: pnpm install --frozen-lockfile
      shell: bash
