#!/usr/bin/env node

import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { pathToFileURL } from "node:url";
import { register } from "node:module";

const __dirname = import.meta.dirname;

async function install() {
  const cwd = process.env.INIT_CWD || process.cwd();
  const forceCreate = process.env.FORCE_CREATE === "1";

  // Skip if running in the tailor-sdk package itself (unless forced)
  if (
    !forceCreate &&
    (cwd === __dirname || cwd === resolve(__dirname, "..", ".."))
  ) {
    console.log("⚠️  Skipping postinstall in tailor-sdk package itself");
    return;
  }

  console.log("🔧 Initializing Tailor SDK type definitions...");

  // Create plugin-generated.d.ts in the dist directory
  const distDir = resolve(__dirname, "dist");
  const pluginTypesPath = resolve(distDir, "plugin-generated.d.ts");

  // Check if dist directory exists
  if (!existsSync(distDir)) {
    console.log("⚠️  Dist directory not found, skipping type initialization");
    return;
  }

  // Try to find and load the user's tailor.config.ts
  const configPath = process.env.TAILOR_SDK_CONFIG_PATH
    ? resolve(cwd, process.env.TAILOR_SDK_CONFIG_PATH)
    : resolve(cwd, "tailor.config.ts");

  if (existsSync(configPath)) {
    try {
      // Register tsx to handle TypeScript imports
      register("tsx", import.meta.url, { data: {} });

      // Import the generateUserTypes function from the built CLI
      const { generateUserTypes } = await import(
        pathToFileURL(resolve(__dirname, "dist", "cli", "api.mjs")).href
      );

      // Load the config and generate types
      const { loadConfig } = await import(
        pathToFileURL(resolve(__dirname, "dist", "cli", "api.mjs")).href
      );
      const { config } = await loadConfig(configPath);

      await generateUserTypes(config, configPath);
      return;
    } catch (error) {
      console.warn("⚠️  Failed to generate types from config:", error.message);
      // Fall through to create empty type definition
    }
  }

  // Create empty type definition file as fallback
  const initialContent = `// This file is auto-generated by @tailor-platform/tailor-sdk
// Do not edit this file manually
// Regenerated automatically when running 'tailor-sdk apply' or 'tailor-sdk generate'

declare global {
  namespace TailorSDK {
    interface AttributeMap {}
    type AttributeList = [];
  }
}

export {};
`;

  try {
    mkdirSync(dirname(pluginTypesPath), { recursive: true });
    writeFileSync(pluginTypesPath, initialContent);
    console.log("✅ Created initial type definitions");
  } catch (error) {
    console.error("❌ Failed to create type definitions:", error.message);
    // Don't exit with error - this shouldn't break the installation
  }
}

// Only run if this is the main module
if (import.meta.url === new URL(import.meta.url).href) {
  install();
}
