/**
 * Generates `tailor-env.d.ts` content from a manifest.
 *
 * Produces a `declare module` augmentation that maps each namespace/type
 * pair to `InferTable<typeof import(...)["exportName"]>`, enabling
 * type-safe `getDB()` calls without manual code generation.
 */

import * as path from "pathe";
import type { Manifest } from "@/cli/generator/manifest";

/**
 * Generate the content of `tailor-env.d.ts` from a manifest.
 * @param manifest - The manifest describing namespaces and types
 * @param outputDir - Absolute path to the directory where the .d.ts will be written
 * @returns The content string for `tailor-env.d.ts`
 */
export function generateDts(manifest: Manifest, outputDir: string): string {
  const lines: string[] = [
    "// tailor-env.d.ts (auto-generated by @tailor-platform/sdk/ts-plugin)",
    "// Do not edit this file manually.",
    "",
    'import type { InferTable } from "@tailor-platform/sdk/kysely";',
    "",
    'declare module "@tailor-platform/sdk/kysely" {',
    "  interface GeneratedNamespace {",
  ];

  for (const [namespace, nsData] of Object.entries(manifest.namespaces)) {
    lines.push(`    ${namespace}: {`);
    for (const entry of nsData.types) {
      const absolutePath = path.resolve(manifest.configDir, entry.filePath);
      const relativePath = path.relative(outputDir, absolutePath);
      // Ensure forward slashes and strip .ts extension for import specifier
      const importPath = `./${relativePath.replace(/\\/g, "/").replace(/\.ts$/, "")}`;
      lines.push(
        `      ${entry.typeName}: InferTable<(typeof import("${importPath}"))["${entry.exportName}"]>;`,
      );
    }
    lines.push("    };");
  }

  lines.push("  }");
  lines.push("}");
  lines.push("");

  return lines.join("\n");
}
