import * as fs from "node:fs";
import { createRequire } from "node:module";
import ml from "multiline-ts";
import * as path from "pathe";
import { logger } from "@/cli/utils/logger";
import type { AppConfig } from "@/parser/app-config";
import type { Plugin } from "@/parser/plugin-config";

/**
 * Type alias for plugin config schema field type
 */
type ConfigSchemaField = Exclude<Plugin["configSchema"], undefined>;

export interface AttributeMapConfig {
  [key: string]: string;
}

export type AttributeListConfig = readonly string[];

interface ExtractedAttributes {
  attributeMap?: AttributeMapConfig;
  attributeList?: AttributeListConfig;
  env?: Record<string, string | number | boolean>;
}

type AttributeFieldLike = {
  type?: string;
  metadata?: {
    array?: boolean;
    allowedValues?: Array<{ value: string }>;
  };
};

/**
 * Extract attribute definitions from the app config for user-defined typing.
 * @param config - Application config to inspect
 * @returns Extracted attribute map/list and env values
 * @internal
 */
export function extractAttributesFromConfig(config: AppConfig): ExtractedAttributes {
  return collectAttributesFromConfig(config);
}

/**
 * Generate the contents of the user-defined type definition file.
 * @param attributeMap - Attribute map configuration
 * @param attributeList - Attribute list configuration
 * @param env - Environment configuration
 * @param pluginConfigs - Plugin configuration entries for PluginConfigs interface
 * @returns Generated type definition source
 */
export function generateTypeDefinition(
  attributeMap: AttributeMapConfig | undefined,
  attributeList: AttributeListConfig | undefined,
  env?: Record<string, string | number | boolean>,
  pluginConfigs?: PluginConfigForTypeGen[],
): string {
  // Generate AttributeMap interface
  // attributeMap values are type string representations (e.g., "string", "boolean", "string[]")
  const mapFields = attributeMap
    ? Object.entries(attributeMap)
        .map(([key, value]) => `    ${key}: ${value};`)
        .join("\n")
    : "";

  const mapBody =
    !attributeMap || Object.keys(attributeMap).length === 0
      ? "{}"
      : `{
${mapFields}
  }`;

  // Generate AttributeList type as a tuple of strings based on the length
  const listType = attributeList ? `[${attributeList.map(() => "string").join(", ")}]` : "[]";

  // Use interface with __tuple marker for declaration merging and tuple type support
  const listBody = `{
    __tuple?: ${listType};
  }`;

  // Generate Env interface
  const envFields = env
    ? Object.entries(env)
        .map(([key, value]) => {
          const valueType = typeof value === "string" ? `"${value}"` : String(value);
          return `    ${key}: ${valueType};`;
        })
        .join("\n")
    : "";

  const envBody =
    !env || Object.keys(env).length === 0
      ? "{}"
      : `{
${envFields}
  }`;

  // Generate PluginConfigs interface if plugins are provided
  const pluginConfigsSection =
    pluginConfigs && pluginConfigs.length > 0
      ? `\n${generatePluginConfigsDefinition(pluginConfigs)}`
      : "";

  // Generate TailorDBType.plugin() overload for IDE completion
  const pluginMethodOverload =
    pluginConfigs && pluginConfigs.length > 0
      ? `\n${generatePluginMethodOverload(pluginConfigs)}`
      : "";

  return ml /* ts */ `
// This file is auto-generated by @tailor-platform/sdk
// Do not edit this file manually
// Regenerated automatically when running 'tailor-sdk apply' or 'tailor-sdk generate'

declare module "@tailor-platform/sdk" {
  interface AttributeMap ${mapBody}
  interface AttributeList ${listBody}
  interface Env ${envBody}${pluginConfigsSection}${pluginMethodOverload}
}

export {};

`;
}

const require = createRequire(import.meta.url);

function collectAttributesFromConfig(config: AppConfig): ExtractedAttributes {
  const auth = config.auth;
  if (!auth || typeof auth !== "object") {
    return {};
  }

  const inferAttributeType = (field?: AttributeFieldLike): string => {
    const type = field?.type;
    const metadata = field?.metadata;

    // Default to string if no metadata
    if (!metadata) {
      return "string";
    }

    let typeStr = "string";

    if (type === "boolean") {
      typeStr = "boolean";
    } else if (type === "enum" && metadata.allowedValues) {
      // Generate union type from enum values
      typeStr = metadata.allowedValues.map((v) => `"${v.value}"`).join(" | ");
    }

    // Add array suffix if needed
    if (metadata.array) {
      typeStr += "[]";
    }

    return typeStr;
  };

  // Check if auth has userProfile with attributes/attributeList
  if ("userProfile" in auth) {
    const userProfile = (
      auth as {
        userProfile?: {
          type?: {
            fields?: Record<string, AttributeFieldLike>;
          };
          attributes?: Record<string, true>;
          attributeList?: AttributeListConfig;
        };
      }
    ).userProfile;

    const attributes = userProfile?.attributes;
    const fields = userProfile?.type?.fields;
    const attributeList = userProfile?.attributeList;

    // Convert attributes to AttributeMapConfig by inferring types from field metadata
    const attributeMap: AttributeMapConfig | undefined = attributes
      ? Object.keys(attributes).reduce((acc, key) => {
          acc[key] = inferAttributeType(fields?.[key]);
          return acc;
        }, {} as AttributeMapConfig)
      : undefined;

    return {
      attributeMap,
      attributeList,
    };
  }

  if ("machineUserAttributes" in auth) {
    const machineUserAttributes = (
      auth as {
        machineUserAttributes?: Record<string, AttributeFieldLike>;
      }
    ).machineUserAttributes;

    if (!machineUserAttributes) {
      return {};
    }

    const attributeMap = Object.entries(machineUserAttributes).reduce((acc, [key, field]) => {
      acc[key] = inferAttributeType(field);
      return acc;
    }, {} as AttributeMapConfig);

    return {
      attributeMap,
    };
  }

  return {};
}

/**
 * Resolve the output path for the generated type definition file.
 * @param configPath - Path to Tailor config file
 * @returns Absolute path to the type definition file
 */
function resolveTypeDefinitionPath(configPath: string): string {
  // Check for environment variable override
  const typePath = process.env.TAILOR_PLATFORM_SDK_TYPE_PATH;
  if (typePath) {
    return path.resolve(process.cwd(), typePath);
  }

  const configDir = path.dirname(path.resolve(configPath));
  const packageDir = resolvePackageDirectory(configDir);

  if (!packageDir) {
    return path.join(
      configDir,
      "node_modules",
      "@tailor-platform",
      "sdk",
      "dist",
      "user-defined.d.ts",
    );
  }

  return path.join(packageDir, "dist", "user-defined.d.ts");
}

/**
 * Options for generating user type definitions
 */
interface GenerateUserTypesOptions {
  /** Application config */
  config: AppConfig;
  /** Path to Tailor config file */
  configPath: string;
  /** Optional array of plugins to generate PluginConfigs for */
  plugins?: Plugin[];
}

/**
 * Generate user type definitions from the app config and write them to disk.
 * @param options - Generation options
 * @returns Promise that resolves when types are generated
 */
export async function generateUserTypes(options: GenerateUserTypesOptions): Promise<void> {
  const { config, configPath, plugins } = options;
  try {
    const { attributeMap, attributeList } = extractAttributesFromConfig(config);
    if (!attributeMap && !attributeList) {
      logger.info("No attributes found in configuration", { mode: "plain" });
    }

    if (attributeMap) {
      logger.debug(`Extracted AttributeMap: ${JSON.stringify(attributeMap)}`);
    }
    if (attributeList) {
      logger.debug(`Extracted AttributeList: ${JSON.stringify(attributeList)}`);
    }

    const env = config.env;
    if (env) {
      logger.debug(`Extracted Env: ${JSON.stringify(env)}`);
    }

    // Convert plugins to PluginConfigForTypeGen format
    const pluginConfigs: PluginConfigForTypeGen[] | undefined = plugins
      ?.filter(
        (p): p is Plugin & { configSchema: ConfigSchemaField } => p.configSchema !== undefined,
      )
      .map((p) => ({
        id: p.id,
        configSchema: p.configSchema,
        configTypeTemplate: p.configTypeTemplate,
        typeConfigRequired: isTypeConfigRequired(p),
      }));

    if (pluginConfigs && pluginConfigs.length > 0) {
      logger.debug(`Extracted PluginConfigs: ${pluginConfigs.map((p) => p.id).join(", ")}`);
    }

    // Generate type definition
    const typeDefContent = generateTypeDefinition(attributeMap, attributeList, env, pluginConfigs);
    const outputPath = resolveTypeDefinitionPath(configPath);

    // Write to file
    fs.mkdirSync(path.dirname(outputPath), { recursive: true });
    fs.writeFileSync(outputPath, typeDefContent);
    const relativePath = path.relative(process.cwd(), outputPath);
    logger.newline();
    logger.success(`Generated type definitions: ${relativePath}`, {
      mode: "plain",
    });
  } catch (error) {
    logger.error("Error generating types");
    logger.error(String(error));
    // Don't throw - this should not block apply/generate
  }
}

function resolvePackageDirectory(startDir: string): string | null {
  let currentDir = startDir;
  const root = path.parse(currentDir).root;

  while (true) {
    const candidate = path.join(currentDir, "node_modules", "@tailor-platform", "sdk");
    const packageJsonPath = path.join(candidate, "package.json");
    if (fs.existsSync(packageJsonPath)) {
      return candidate;
    }

    if (currentDir === root) {
      break;
    }

    const parentDir = path.dirname(currentDir);
    currentDir = parentDir;
  }

  try {
    const resolved = require.resolve("@tailor-platform/sdk/package.json", {
      paths: [startDir],
    });
    return path.dirname(resolved);
  } catch {
    return null;
  }
}

/**
 * Configuration for plugin type generation
 */
export interface PluginConfigForTypeGen {
  id: string;
  configSchema: ConfigSchemaField;
  /** Optional TypeScript type template (uses Fields for field names) */
  configTypeTemplate?: string;
  /** Whether per-type config is required when attaching via .plugin() */
  typeConfigRequired?: boolean;
}

/**
 * Convert a ConfigSchemaField to its TypeScript type string representation.
 * @param field - The field to convert
 * @param indent - Current indentation level
 * @returns TypeScript type string
 */
function fieldToTypeString(field: ConfigSchemaField, indent = 0): string {
  const indentStr = "  ".repeat(indent);
  const metadata = field.metadata;

  let baseType: string;

  switch (field.type) {
    case "string":
    case "uuid":
    case "date":
    case "datetime":
    case "time":
      baseType = "string";
      break;
    case "integer":
    case "float":
      baseType = "number";
      break;
    case "boolean":
      baseType = "boolean";
      break;
    case "enum":
      if (metadata.allowedValues && metadata.allowedValues.length > 0) {
        baseType = metadata.allowedValues.map((v: { value: string }) => `"${v.value}"`).join(" | ");
      } else {
        baseType = "string";
      }
      break;
    case "nested": {
      const fieldEntries = Object.entries(field.fields);
      if (fieldEntries.length === 0) {
        // Empty object - allow any properties (for dynamic configs like labels)
        baseType = "Record<string, unknown>";
      } else {
        const fieldLines = fieldEntries.map(([name, nestedField]) => {
          const nestedType = fieldToTypeString(nestedField as ConfigSchemaField, indent + 1);
          const isOptional = !(nestedField as ConfigSchemaField).metadata.required;
          return `${indentStr}  ${name}${isOptional ? "?" : ""}: ${nestedType};`;
        });
        baseType = `{\n${fieldLines.join("\n")}\n${indentStr}}`;
      }
      break;
    }
    default:
      baseType = "unknown";
  }

  // Handle array type
  if (metadata.array) {
    baseType = `(${baseType})[]`;
  }

  return baseType;
}

function isTypeConfigRequired(plugin: Plugin): boolean {
  const required = plugin.typeConfigRequired;
  if (typeof required === "function") {
    return required(plugin.pluginConfig);
  }
  return required === true;
}

/**
 * Generate PluginConfigs interface extension for user-defined.d.ts
 * @param plugins - Array of plugin configurations
 * @returns TypeScript interface extension string, or empty string if no plugins
 */
function generatePluginConfigsDefinition(plugins: PluginConfigForTypeGen[]): string {
  if (plugins.length === 0) {
    return "";
  }

  const pluginEntries = plugins.map((plugin) => {
    // Use configTypeTemplate if provided, otherwise generate from configSchema
    const typeString = plugin.configTypeTemplate ?? fieldToTypeString(plugin.configSchema, 2);
    const optionalMarker = plugin.typeConfigRequired ? "" : "?";
    return `    "${plugin.id}"${optionalMarker}: ${typeString};`;
  });

  return `  interface PluginConfigs<Fields extends string> {
${pluginEntries.join("\n")}
  }`;
}

/**
 * Generate TailorDBType.plugin() method overload for IDE completion.
 * This adds an overload that uses `keyof Fields` directly for field-aware types,
 * enabling IDE autocompletion for field names in plugin configs.
 * @param plugins - Array of plugin configurations
 * @returns TypeScript interface extension string
 */
function generatePluginMethodOverload(plugins: PluginConfigForTypeGen[]): string {
  // Generate plugin config entries, converting Fields to keyof Fields & string
  const pluginEntries = plugins.map((plugin) => {
    // Use configTypeTemplate, replacing "Fields" with "keyof Fields & string"
    const typeTemplate = plugin.configTypeTemplate ?? fieldToTypeString(plugin.configSchema, 3);
    const typeString = typeTemplate.replace(/\bFields\b/g, "keyof Fields & string");
    const optionalMarker = plugin.typeConfigRequired ? "" : "?";
    return `      "${plugin.id}"${optionalMarker}: ${typeString};`;
  });

  const allEntries = pluginEntries;

  return `  // Overload for .plugin() method to enable IDE completion for field names
  interface TailorDBType<Fields, User> {
    plugin(config: {
${allEntries.join("\n")}
    }): this;
  }`;
}
