const machineUser = "ci";
const report = `tailor-sdk crashreport list --machine-user ${machineUser}`;
const conditionalArg = `tailor-sdk login ${isCI ? "--machine-user" : ""}`;
const conditionalCommand = `tailor-sdk ${showReports ? "crashreport" : "login"} list`;
const dynamicGlobalTemplate = `tailor-sdk ${verbose ? "--verbose" : ""} ${showReports ? "crashreport" : "login"} list`;
const staticCommandAfterDynamicGlobal = `tailor-sdk ${verbose ? "--verbose" : ""} crashreport list`;
const dynamicInlineGlobalTemplate = `tailor-sdk ${useEnv ? "--env-file=.env" : "--json"} ${showReports ? "crashreport" : "login"} list`;
const dynamicProfileTemplate = `tailor-sdk --profile ${profile} crashreport --machine-user`;
const separatedTemplate = `tailor-sdk crashreport; ${next}`;
const packageRunnerTemplate = `npx --package tailor-sdk tailor-sdk crashreport --machine-user=ci`;
const shortPackageRunnerTemplate = `npx -p tailor-sdk tailor-sdk crashreport --machine-user=ci`;
const valueFlagPackageRunnerTemplate = `npx --cache tailor-sdk tailor-sdk crashreport --machine-user=ci`;
const repeatedTemplate = `tailor-sdk crashreport --machine-user
tailor-sdk crashreport --machine-user`;
const repeatedSeparatedTemplate = `tailor-sdk crashreport; tailor-sdk crashreport --machine-user`;
const joinedRepeatedSeparatedTemplate = `tailor-sdk crashreport;tailor-sdk crashreport`;
const conditionalGlobalComparison = `tailor-sdk ${mode === "prod" ? "--verbose" : "--json"} crashreport list`;
const conditionalOptionComparison = `tailor-sdk login ${flag === "--machineuser" ? "--json" : "--machine-user"}`;
const conditionalCommandComparison = `tailor-sdk ${cmd === "crash-report" ? "login" : "crashreport"} list`;
const inlineEnvTemplate = `tailor-sdk --env-file=${envFile} ${showReports ? "crashreport" : "login"} list`;
const login = "tailor-sdk login --machine-user ci";
const envFilePath = "tailor-sdk --env-file=/tmp/--machineuser crashreport";
const envFileCommandSubstitutionPath = "tailor-sdk --env-file=$(pwd)/--machineuser crashreport --machine-user";
const argPayload = "tailor-sdk function test-run --arg=--machineuser";
const argCommandSubstitutionPayload = "tailor-sdk function test-run --arg=$(printf --machineuser) --machine-user";
const quotedArgCommandPayload = "tailor-sdk function test-run --arg='tailor-sdk crash-report --machineuser' --machine-user";
const escapedQueryCommand = "tailor-sdk query --query \"select 1\" --machine-user";
const profileCommand = "tailor-sdk --profile prod crashreport --machine-user";
const profileMachineUserValue = "tailor-sdk --profile --machineuser crashreport --machine-user";
const workspaceCommand = "tailor-sdk -w workspace-1 crashreport";
const chainedShellCommand = "cd app && tailor-sdk crashreport --machine-user";
const envShellCommand = "env FOO=bar tailor-sdk crashreport --machine-user";
const assignmentShellCommand = "TAILOR=1 tailor-sdk crashreport --machine-user";
const envDynamicCommandTemplate = `env FOO=bar tailor-sdk ${showReports ? "crashreport" : "login"} --machine-user`;
const assignmentDynamicCommandTemplate = `TAILOR=1 tailor-sdk ${showReports ? "crashreport" : "login"} --machine-user`;
const unknownInlineValue = "tailor-sdk login --name=--machineuser";
const argTemplatePayload = `tailor-sdk function test-run --arg=${payload ? "--machineuser" : ""}`;
const dynamicArgTemplatePayload = `tailor-sdk function test-run ${includeArg ? "--arg" : ""} ${payload ? "--machineuser" : ""} --machine-user`;
const quotedQueryTemplate = `tailor-sdk query --query "select --machineuser ${where}" --machine-user`;
const inlineQueryTemplate = `tailor-sdk query --query=${payload ? "--machineuser" : ""} --machine-user`;
const chainedCommandTemplate = `tailor-sdk login --machine-user && other-cli --machineuser`;
const joinedSeparatorTemplate = `tailor-sdk login --machine-user;other-cli --machineuser`;
const newlineCommandTemplate = `tailor-sdk login --machine-user
other-cli --machineuser`;
const other = "other-cli --machineuser ci";
