const machineUser = "ci";
const report = `tailor-sdk crash-report list --machineuser ${machineUser}`;
const conditionalArg = `tailor-sdk login ${isCI ? "--machineuser" : ""}`;
const conditionalCommand = `tailor-sdk ${showReports ? "crash-report" : "login"} list`;
const dynamicGlobalTemplate = `tailor-sdk ${verbose ? "--verbose" : ""} ${showReports ? "crash-report" : "login"} list`;
const staticCommandAfterDynamicGlobal = `tailor-sdk ${verbose ? "--verbose" : ""} crash-report list`;
const dynamicInlineGlobalTemplate = `tailor-sdk ${useEnv ? "--env-file=.env" : "--json"} ${showReports ? "crash-report" : "login"} list`;
const dynamicProfileTemplate = `tailor-sdk --profile ${profile} crash-report --machineuser`;
const separatedTemplate = `tailor-sdk crash-report; ${next}`;
const packageRunnerTemplate = `npx --package tailor-sdk tailor-sdk crash-report --machineuser=ci`;
const shortPackageRunnerTemplate = `npx -p tailor-sdk tailor-sdk crash-report --machineuser=ci`;
const valueFlagPackageRunnerTemplate = `npx --cache tailor-sdk tailor-sdk crash-report --machineuser=ci`;
const repeatedTemplate = `tailor-sdk crash-report --machineuser
tailor-sdk crash-report --machineuser`;
const repeatedSeparatedTemplate = `tailor-sdk crash-report; tailor-sdk crash-report --machineuser`;
const joinedRepeatedSeparatedTemplate = `tailor-sdk crash-report;tailor-sdk crash-report`;
const conditionalGlobalComparison = `tailor-sdk ${mode === "prod" ? "--verbose" : "--json"} crash-report list`;
const conditionalOptionComparison = `tailor-sdk login ${flag === "--machineuser" ? "--json" : "--machineuser"}`;
const conditionalCommandComparison = `tailor-sdk ${cmd === "crash-report" ? "login" : "crash-report"} list`;
const inlineEnvTemplate = `tailor-sdk --env-file=${envFile} ${showReports ? "crash-report" : "login"} list`;
const login = "tailor-sdk login --machineuser ci";
const envFilePath = "tailor-sdk --env-file=/tmp/--machineuser crash-report";
const envFileCommandSubstitutionPath = "tailor-sdk --env-file=$(pwd)/--machineuser crash-report --machineuser";
const argPayload = "tailor-sdk function test-run --arg=--machineuser";
const argCommandSubstitutionPayload = "tailor-sdk function test-run --arg=$(printf --machineuser) --machineuser";
const quotedArgCommandPayload = "tailor-sdk function test-run --arg='tailor-sdk crash-report --machineuser' --machineuser";
const escapedQueryCommand = "tailor-sdk query --query \"select 1\" --machineuser";
const profileCommand = "tailor-sdk --profile prod crash-report --machineuser";
const profileMachineUserValue = "tailor-sdk --profile --machineuser crash-report --machineuser";
const workspaceCommand = "tailor-sdk -w workspace-1 crash-report";
const chainedShellCommand = "cd app && tailor-sdk crash-report --machineuser";
const envShellCommand = "env FOO=bar tailor-sdk crash-report --machineuser";
const assignmentShellCommand = "TAILOR=1 tailor-sdk crash-report --machineuser";
const envDynamicCommandTemplate = `env FOO=bar tailor-sdk ${showReports ? "crash-report" : "login"} --machineuser`;
const assignmentDynamicCommandTemplate = `TAILOR=1 tailor-sdk ${showReports ? "crash-report" : "login"} --machineuser`;
const unknownInlineValue = "tailor-sdk login --name=--machineuser";
const argTemplatePayload = `tailor-sdk function test-run --arg=${payload ? "--machineuser" : ""}`;
const dynamicArgTemplatePayload = `tailor-sdk function test-run ${includeArg ? "--arg" : ""} ${payload ? "--machineuser" : ""} --machineuser`;
const quotedQueryTemplate = `tailor-sdk query --query "select --machineuser ${where}" --machineuser`;
const inlineQueryTemplate = `tailor-sdk query --query=${payload ? "--machineuser" : ""} --machineuser`;
const chainedCommandTemplate = `tailor-sdk login --machineuser && other-cli --machineuser`;
const joinedSeparatorTemplate = `tailor-sdk login --machineuser;other-cli --machineuser`;
const newlineCommandTemplate = `tailor-sdk login --machineuser
other-cli --machineuser`;
const other = "other-cli --machineuser ci";
