const packageName = "tailor-sdk";
const runnerArgs = ["npx", "@tailor-platform/sdk@latest", "login"];
const dynamicPackageVariableRunner = ["npx", pkg, "tailor", "login"];
const dynamicDlxPackageVariableRunner = ["pnpm", "dlx", pkg, "tailor", "login"];
const dynamicFlagRunner = ["npx", yes && "-y", "@tailor-platform/sdk", "login"];
const dynamicAmbiguousValueFlagRunner = ["npx", cond ? "--cache" : "--yes", "tailor-sdk", "login"];
const localPackageRunner = ["npx", "./tailor-sdk", "tailor", "login"];
const dynamicInlineValueFlagRunner = ["npx", useRegistry ? "--registry=https://npm.example" : "-y", "@tailor-platform/sdk", "login"];
const dynamicFlagConditionRunner = ["npx", mode === "prod" ? "-y" : "--yes", "@tailor-platform/sdk", "login"];
const packageConditionRunner = ["npx", pkg === "tailor-sdk" ? pkg : "@tailor-platform/sdk", "login"];
const inlineBooleanFlagRunner = ["npx", "--yes=true", "@tailor-platform/sdk", "login"];
const nestedRunner = spawn("npx", ["-y", "@tailor-platform/sdk", "login"]);
const pnpmRunner = spawn("pnpm", ["dlx", "@tailor-platform/sdk@2.0.0", "login"]);
const pnpmExecRunner = spawn("pnpm", ["exec", "tailor", "login"]);
const yarnExecRunner = ["yarn", "exec", "tailor", "login"];
const pnpmExecOtherCommand = ["pnpm", "exec", "other-cli", "tailor-sdk"];
const valuedFlagRunner = ["npx", "--cache", ".npm", "@tailor-platform/sdk", "login"];
const namedValueFlagRunner = ["npx", "--cache", "npm-cache", "@tailor-platform/sdk", "login"];
const registryValueFlagRunner = ["npx", "--registry", "https://npm.example", "@tailor-platform/sdk", "login"];
const prefixValueFlagRunner = ["npx", "--prefix", "npm-cache", "@tailor-platform/sdk", "login"];
const protectedValueFlagRunner = ["npx", "--cache", "tailor-sdk", "some-package"];
const expressionValueFlagRunner = ["npx", "--cache", cacheDir, "@tailor-platform/sdk", "login"];
const protectedExpressionValueFlagRunner = ["npx", "--cache", cacheDir || "tailor-sdk", "@tailor-platform/sdk", "login"];
const inlineValueFlagRunner = ["npx", "--registry=https://npm.example/tailor-sdk", "@tailor-platform/sdk"];
const inlinePackageFlagRunner = ["npx", "--package=@tailor-platform/sdk", "tailor", "login"];
const dynamicInlinePackageFlagRunner = ["npx", `--package=${useLocal ? "@tailor-platform/sdk" : pkg}`, "tailor", "login"];
const dynamicSeparatePackageFlagRunner = ["npx", useLocal ? "--package" : "", useLocal ? "@tailor-platform/sdk" : pkg, "tailor", "login"];
const dynamicPackageOptionCommandRunner = ["npx", "--package", "@tailor-platform/sdk", "tailor", cmd];
const dynamicInlinePackageOptionCommandRunner = ["npx", `--package=${pkg}`, "tailor", cmd];
const templateConditionalRunner = `npx ${useLatest ? "@tailor-platform/sdk@latest" : "@tailor-platform/sdk"} login`;
const templateDynamicInlineValueFlagRunner = `npx ${useRegistry ? "--registry=https://npm.example" : "-y"} @tailor-platform/sdk login`;
const pnpmOptionRunner = spawn("pnpm", ["--dir", ".", "dlx", "@tailor-platform/sdk", "login"]);
const pnpmFilterRunner = ["pnpm", "--filter", "app", "dlx", "@tailor-platform/sdk", "login"];
const pnpmRegistryRunner = ["pnpm", "--registry", "https://npm.example", "dlx", "@tailor-platform/sdk", "login"];
const dynamicPnpmFilterRunner = ["pnpm", use ? "--filter" : "", "app", "dlx", "@tailor-platform/sdk", "login"];
const dynamicInlinePnpmFilterRunner = ["pnpm", use ? "--filter=tailor-sdk" : "", "dlx", "@tailor-platform/sdk", "login"];
const dynamicInlineRegistryRunner = ["npx", use ? "--registry=https://npm.example/tailor-sdk" : "-y", "@tailor-platform/sdk", "login"];
const spreadFlagRunner = ["npx", ...["-y"], "@tailor-platform/sdk", "login"];
const unknownSpreadFlagRunner = ["npx", ...flags, "@tailor-platform/sdk", "login"];
const commentedRunner = ["npx", /* install CLI */ "@tailor-platform/sdk", "login"];
const commentedPackageFlagRunner = ["npx", "--package", /* package */ "@tailor-platform/sdk", "tailor", "login"];
const commentedPnpmDlxRunner = ["pnpm", /* comment */ "dlx", "@tailor-platform/sdk", "login"];
const commentedValueFlagRunner = ["npx", "--cache", /* cache dir */ ".npm", "@tailor-platform/sdk", "login"];
const unrelatedTailorPackageRunner = ["npx", "--cache", ".npm", "tailor", "sprite"];
const conditionalRunner = ["npx", useLatest ? "@tailor-platform/sdk@latest" : "@tailor-platform/sdk", "login"];
const binaryArgs = ["tailor", "login"];
const profileArgValue = ["tailor", "--profile", "tailor-sdk", "deploy"];
const shortProfileArgValue = ["tailor", "-p", "tailor-sdk", "deploy"];
const profileCommandPayload = ["tailor", "--profile", "tailor-sdk deploy", "deploy"];
const argCommandPayload = ["tailor", "function", "test-run", "--arg", "{\"cmd\":\"tailor-sdk deploy\"}"];
const argCommandPayloadExpression = ["tailor", "function", "test-run", "--arg", cond ? "tailor-sdk deploy" : "{}"];
const argCommandPayloadTemplate = ["tailor", "function", "test-run", "--arg", `tailor-sdk deploy`];
const dynamicBinaryArgs = ["tailor", cmd];
const spreadBinaryArgs = ["tailor", ...args];
const wrappedCommandArgs = ["tailor", "login" as const];
const parenthesizedCommandArgs = ["tailor", ("deploy")];
const commandArgPackageName = ["tailor", "login", "tailor-sdk"];
const packageManagerNames = ["pnpm", "tailor-sdk"];
const unrelatedNpxValues = ["npx", "create-tailor-sdk", "tailor-sdk-skills", "tailor-sdk"];
const packageNames = ["tailor-sdk", "react"];
const packageTuple = [["tailor-sdk", version]];
const packageTupleValue = ["tailor-sdk", version];
const packageOptionData = ["tailor-sdk", "--not-cli"];
const outputDir = ".tailor-sdk";
