const packageName = "tailor-sdk";
const runnerArgs = ["npx", "tailor-sdk@latest", "login"];
const wrappedRunnerArgs = ["npx" as const, "tailor-sdk", "login"];
const parenthesizedRunnerArgs = [("npx"), "tailor-sdk", "login"];
const dynamicPackageVariableRunner = ["npx", pkg, "tailor-sdk", "login"];
const dynamicDlxPackageVariableRunner = ["pnpm", "dlx", pkg, "tailor-sdk", "login"];
const dynamicFlagRunner = ["npx", yes && "-y", "tailor-sdk", "login"];
const dynamicAmbiguousValueFlagRunner = ["npx", cond ? "--cache" : "--yes", "tailor-sdk", "login"];
const localPackageRunner = ["npx", "./tailor-sdk", "tailor-sdk", "login"];
const dynamicInlineValueFlagRunner = ["npx", useRegistry ? "--registry=https://npm.example" : "-y", "tailor-sdk", "login"];
const dynamicFlagConditionRunner = ["npx", mode === "prod" ? "-y" : "--yes", "tailor-sdk", "login"];
const packageConditionRunner = ["npx", pkg === "tailor-sdk" ? pkg : "tailor-sdk", "login"];
const inlineBooleanFlagRunner = ["npx", "--yes=true", "tailor-sdk", "login"];
const nestedRunner = spawn("npx", ["-y", "tailor-sdk", "login"]);
const pnpmRunner = spawn("pnpm", ["dlx", "tailor-sdk@2.0.0", "login"]);
const pnpmExecRunner = spawn("pnpm", ["exec", "tailor-sdk", "login"]);
const yarnExecRunner = ["yarn", "exec", "tailor-sdk", "login"];
const pnpmExecOtherCommand = ["pnpm", "exec", "other-cli", "tailor-sdk"];
const valuedFlagRunner = ["npx", "--cache", ".npm", "tailor-sdk", "login"];
const namedValueFlagRunner = ["npx", "--cache", "npm-cache", "tailor-sdk", "login"];
const registryValueFlagRunner = ["npx", "--registry", "https://npm.example", "tailor-sdk", "login"];
const prefixValueFlagRunner = ["npx", "--prefix", "npm-cache", "tailor-sdk", "login"];
const protectedValueFlagRunner = ["npx", "--cache", "tailor-sdk", "some-package"];
const expressionValueFlagRunner = ["npx", "--cache", cacheDir, "tailor-sdk", "login"];
const protectedExpressionValueFlagRunner = ["npx", "--cache", cacheDir || "tailor-sdk", "tailor-sdk", "login"];
const inlineValueFlagRunner = ["npx", "--registry=https://npm.example/tailor-sdk", "tailor-sdk"];
const inlinePackageFlagRunner = ["npx", "--package=tailor-sdk", "tailor-sdk", "login"];
const dynamicInlinePackageFlagRunner = ["npx", `--package=${useLocal ? "tailor-sdk" : pkg}`, "tailor-sdk", "login"];
const dynamicSeparatePackageFlagRunner = ["npx", useLocal ? "--package" : "", useLocal ? "tailor-sdk" : pkg, "tailor-sdk", "login"];
const dynamicPackageOptionCommandRunner = ["npx", "--package", "tailor-sdk", "tailor-sdk", cmd];
const packageOptionArgPayloadRunner = ["npx", "--package", "tailor-sdk", "tailor-sdk", "function", "test-run", "--arg", cond ? "tailor-sdk deploy" : "{}"];
const dynamicInlinePackageOptionCommandRunner = ["npx", `--package=${pkg}`, "tailor-sdk", cmd];
const templateConditionalRunner = `npx ${useLatest ? "tailor-sdk@latest" : "tailor-sdk"} login`;
const templateDynamicInlineValueFlagRunner = `npx ${useRegistry ? "--registry=https://npm.example" : "-y"} tailor-sdk login`;
const pnpmOptionRunner = spawn("pnpm", ["--dir", ".", "dlx", "tailor-sdk", "login"]);
const pnpmFilterRunner = ["pnpm", "--filter", "app", "dlx", "tailor-sdk", "login"];
const pnpmRegistryRunner = ["pnpm", "--registry", "https://npm.example", "dlx", "tailor-sdk", "login"];
const dynamicPnpmFilterRunner = ["pnpm", use ? "--filter" : "", "app", "dlx", "tailor-sdk", "login"];
const dynamicInlinePnpmFilterRunner = ["pnpm", use ? "--filter=tailor-sdk" : "", "dlx", "tailor-sdk", "login"];
const dynamicInlineRegistryRunner = ["npx", use ? "--registry=https://npm.example/tailor-sdk" : "-y", "tailor-sdk", "login"];
const spreadFlagRunner = ["npx", ...["-y"], "tailor-sdk", "login"];
const unknownSpreadFlagRunner = ["npx", ...flags, "tailor-sdk", "login"];
const commentedRunner = ["npx", /* install CLI */ "tailor-sdk", "login"];
const commentedPackageFlagRunner = ["npx", "--package", /* package */ "tailor-sdk", "tailor-sdk", "login"];
const commentedPnpmDlxRunner = ["pnpm", /* comment */ "dlx", "tailor-sdk", "login"];
const commentedValueFlagRunner = ["npx", "--cache", /* cache dir */ ".npm", "tailor-sdk", "login"];
const unrelatedTailorPackageRunner = ["npx", "--cache", ".npm", "tailor", "sprite"];
const conditionalRunner = ["npx", useLatest ? "tailor-sdk@latest" : "tailor-sdk", "login"];
const binaryArgs = ["tailor-sdk", "login"];
const profileArgValue = ["tailor-sdk", "--profile", "tailor-sdk", "deploy"];
const shortProfileArgValue = ["tailor-sdk", "-p", "tailor-sdk", "deploy"];
const profileCommandPayload = ["tailor-sdk", "--profile", "tailor-sdk deploy", "deploy"];
const argCommandPayload = ["tailor-sdk", "function", "test-run", "--arg", "{\"cmd\":\"tailor-sdk deploy\"}"];
const argCommandPayloadExpression = ["tailor-sdk", "function", "test-run", "--arg", cond ? "tailor-sdk deploy" : "{}"];
const argCommandPayloadTemplate = ["tailor-sdk", "function", "test-run", "--arg", `tailor-sdk deploy`];
const dynamicArgFlagPayload = ["tailor-sdk", "function", "test-run", includeArg ? "--arg" : "", "tailor-sdk deploy"];
const dynamicBinaryArgs = ["tailor-sdk", cmd];
const spreadBinaryArgs = ["tailor-sdk", ...args];
const wrappedCommandArgs = ["tailor-sdk", "login" as const];
const parenthesizedCommandArgs = ["tailor-sdk", ("deploy")];
const commandArgPackageName = ["tailor-sdk", "login", "tailor-sdk"];
const packageManagerNames = ["pnpm", "tailor-sdk"];
const unrelatedNpxValues = ["npx", "create-tailor-sdk", "tailor-sdk-skills", "tailor-sdk"];
const packageNames = ["tailor-sdk", "react"];
const packageTuple = [["tailor-sdk", version]];
const packageTupleValue = ["tailor-sdk", version];
const packageOptionData = ["tailor-sdk", "--not-cli"];
const outputDir = ".tailor-sdk";
