name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: deploy-__WORKSPACE_NAME__
  cancel-in-progress: false

jobs:
  deploy:
    uses: tailor-platform/sdk/.github/workflows/deploy.yml@actions/v1
    with:
      workspace-name: __WORKSPACE_NAME__
      workspace-region: __WORKSPACE_REGION__
      organization-id: __ORGANIZATION_ID__
      folder-id: __FOLDER_ID__
    # __WORKING_DIRECTORY__
    secrets:
      PLATFORM_MACHINE_USER_CLIENT_ID: ${{ secrets.PLATFORM_MACHINE_USER_CLIENT_ID }}
      PLATFORM_MACHINE_USER_CLIENT_SECRET: ${{ secrets.PLATFORM_MACHINE_USER_CLIENT_SECRET }}
