import * as fs from "node:fs";
import { parseYAML } from "confbox";
import * as path from "pathe";
import { afterEach, beforeEach, describe, expect, test, vi } from "vitest";
import { detectDefaultBranch } from "./git";
import { decideAction, setupGitHub, type SetupGitHubOptions } from "./github";
import { hashContent, readLock } from "./lock";
import {
  detectPackageManager,
  renderBranchWorkflow,
  renderTagWorkflow,
  type RenderBranchParams,
  type RenderTagParams,
} from "./templates";

const NO_MARKER = /__[A-Z_]+__/;

const branchBase: RenderBranchParams = {
  workspaceName: "my-app",
  branch: "main",
  environment: "my-app",
  packageManager: "pnpm",
  plan: true,
};

const tagBase: RenderTagParams = {
  workspaceName: "my-app",
  tagPattern: "v*",
  environment: "my-app",
  packageManager: "pnpm",
};

describe("detectPackageManager", () => {
  const testDir = path.join(
    "/tmp",
    `detect-pm-${Date.now()}-${Math.random().toString(36).slice(2)}`,
  );
  beforeEach(() => fs.mkdirSync(testDir, { recursive: true }));
  afterEach(() => fs.rmSync(testDir, { recursive: true, force: true }));

  test("detects pnpm", () => {
    fs.writeFileSync(path.join(testDir, "pnpm-lock.yaml"), "");
    expect(detectPackageManager(testDir)).toBe("pnpm");
  });
  test("detects yarn", () => {
    fs.writeFileSync(path.join(testDir, "yarn.lock"), "");
    expect(detectPackageManager(testDir)).toBe("yarn");
  });
  test("detects bun", () => {
    fs.writeFileSync(path.join(testDir, "bun.lock"), "");
    expect(detectPackageManager(testDir)).toBe("bun");
  });
  test("defaults to npm", () => {
    expect(detectPackageManager(testDir)).toBe("npm");
  });
});

describe("renderBranchWorkflow", () => {
  test("leaves no markers and parses as YAML", () => {
    const { content } = renderBranchWorkflow(branchBase);
    expect(content).not.toMatch(NO_MARKER);
    expect(() => parseYAML(content)).not.toThrow();
  });

  test("emits the managed header and workspace-scoped name", () => {
    const { content } = renderBranchWorkflow(branchBase);
    expect(content.startsWith("# Generated by")).toBe(true);
    expect(content).toContain("name: Tailor (my-app)");
  });

  test("pins actions with SHA + version comment", () => {
    const { content } = renderBranchWorkflow(branchBase);
    expect(content).toMatch(/uses: actions\/checkout@[a-f0-9]+ # v\d+\.\d+\.\d+/);
    expect(content).toMatch(/uses: pnpm\/action-setup@[a-f0-9]+ # v\d+\.\d+\.\d+/);
    expect(content).toMatch(/uses: actions\/github-script@[a-f0-9]+ # v\d+/);
    expect(content).not.toContain("tailor-platform/actions/");
  });

  test("pins every `uses:` to a full commit SHA (no moving tags/branches)", () => {
    // Generated workflows are committed to user repos and must be reproducible
    // and pass zizmor/ghalint pinning checks: every action reference must be a
    // 40-char commit SHA, never a tag like @v1. (actionlint does not enforce
    // this, so it is asserted here.)
    const assertShaPinned = (content: string): void => {
      const refs = [...content.matchAll(/uses:\s*(\S+?)@(\S+)/g)];
      expect(refs.length).toBeGreaterThan(0);
      for (const [, action, ref] of refs) {
        expect(ref, `${action}@${ref} must be pinned to a 40-char commit SHA`).toMatch(
          /^[0-9a-f]{40}$/,
        );
      }
    };
    for (const pm of ["pnpm", "yarn", "npm", "bun"] as const) {
      assertShaPinned(renderBranchWorkflow({ ...branchBase, packageManager: pm }).content);
      assertShaPinned(renderTagWorkflow({ ...tagBase, packageManager: pm }).content);
    }
  });

  test("uses the unified secret names and targets the workspace-id variable", () => {
    const { content } = renderBranchWorkflow(branchBase);
    expect(content).toContain(
      "TAILOR_PLATFORM_MACHINE_USER_CLIENT_ID: ${{ secrets.TAILOR_PLATFORM_MACHINE_USER_CLIENT_ID }}",
    );
    expect(content).toContain(
      "TAILOR_PLATFORM_MACHINE_USER_CLIENT_SECRET: ${{ secrets.TAILOR_PLATFORM_MACHINE_USER_CLIENT_SECRET }}",
    );
    expect(content).toContain(
      "TAILOR_PLATFORM_WORKSPACE_ID: ${{ vars.TAILOR_PLATFORM_WORKSPACE_ID }}",
    );
    expect(content).not.toContain("secrets.PLATFORM_MACHINE_USER_CLIENT_ID");
  });

  test("targets the workspace by id, never by name or region", () => {
    const { content } = renderBranchWorkflow(branchBase);
    expect(content).not.toContain("workspace-name:");
    expect(content).not.toContain("workspace-region:");
    expect(content).not.toContain("organization-id:");
    expect(content).not.toContain("folder-id:");
  });

  test("sets environment on both the plan and deploy jobs", () => {
    const { content } = renderBranchWorkflow({ ...branchBase, environment: "production" });
    expect(content.match(/environment: production/g)).toHaveLength(2);
  });

  test("passes the workspace name as the plan label", () => {
    const { content } = renderBranchWorkflow(branchBase);
    expect(content).toContain("LABEL: my-app");
  });

  test("fetches the pull request base into the remote-tracking ref before merge", () => {
    const { content } = renderBranchWorkflow(branchBase);
    expect(content).toContain('git fetch origin "$BASE_REF:refs/remotes/origin/$BASE_REF"');
    expect(content).toContain('git merge --no-edit "origin/$BASE_REF"');
    expect(content).not.toContain("git merge --no-commit");
    expect(content.indexOf("id: tailor-merge-base")).toBeLessThan(
      content.indexOf("id: tailor-setup-pnpm"),
    );
  });

  test("paginates plan comment lookup", () => {
    const { content } = renderBranchWorkflow(branchBase);
    expect(content).toContain("github.paginate(github.rest.issues.listComments");
    expect(content).toContain("per_page: 100");
  });

  test("builds plan comment markdown without YAML indentation", () => {
    const { content } = renderBranchWorkflow(branchBase);
    expect(content).toContain("].join('\\n');");
    expect(content).toContain("`## ${status} Tailor Platform Plan (${key})`");
    expect(content).toContain("`<summary>Plan output (exit code: ${exitCode})</summary>`");
    expect(content).not.toContain("            ## ${status} Tailor Platform Plan");
  });

  test("logs full plan output before truncating comments and outputs", () => {
    const branch = renderBranchWorkflow(branchBase).content;
    const tag = renderTagWorkflow(tagBase).content;
    for (const content of [branch, tag]) {
      expect(content).toContain("::group::Full Tailor Platform plan output");
      expect(content).toContain("::stop-commands::$LOG_STOP_TOKEN");
      expect(content).toContain("printf '%s\\n' \"$OUTPUT\"");
      expect(content).toContain(
        "[output truncated to the last $MAX_OUTPUT characters - see the workflow logs for the full plan]",
      );
    }
  });

  test("references the dry-run dispatch input with bracket notation", () => {
    // `inputs.dry-run` is ambiguous to readers/tools; the bracket form is
    // unambiguous for a hyphenated input name.
    const { content } = renderBranchWorkflow(branchBase);
    expect(content).toContain("inputs['dry-run']");
    expect(content).not.toMatch(/inputs\.dry-run/);
  });

  test("includes the fork guard on the plan step", () => {
    const { content } = renderBranchWorkflow(branchBase);
    expect(content).toContain(
      "if: github.event_name != 'pull_request' || !github.event.pull_request.head.repo.fork",
    );
  });

  test("sets cancel-in-progress: false on the deploy concurrency group", () => {
    const { content } = renderBranchWorkflow(branchBase);
    expect(content).toContain("group: tailor-deploy-my-app");
    expect(content).toContain("cancel-in-progress: false");
  });

  test("runs generate checks in plan and deploys with the canonical command", () => {
    const { content } = renderBranchWorkflow(branchBase);
    const parsed = parseYAML(content) as { jobs: Record<string, unknown> };
    expect(Object.keys(parsed.jobs)).toEqual(["tailor-plan", "tailor-deploy"]);
    expect(content.match(/^ {6}- id: tailor-generate$/gm)).toHaveLength(2);
    expect(content.match(/id: tailor-generate-check/g)).toHaveLength(1);
    expect(content).toContain("pnpm exec tailor-sdk deploy --dry-run --yes");
    expect(content).toContain("pnpm exec tailor-sdk deploy --yes");
    expect(content).not.toContain("tailor-sdk apply");
  });

  test("emits PM exec prefix for generate", () => {
    expect(renderBranchWorkflow(branchBase).content).toContain(
      "run: pnpm exec tailor-sdk generate",
    );
    expect(renderBranchWorkflow({ ...branchBase, packageManager: "npm" }).content).toContain(
      "run: npx tailor-sdk generate",
    );
    expect(renderBranchWorkflow({ ...branchBase, packageManager: "bun" }).content).toContain(
      "run: bunx tailor-sdk generate",
    );
    expect(renderBranchWorkflow({ ...branchBase, packageManager: "yarn" }).content).toContain(
      "run: yarn tailor-sdk generate",
    );
  });

  test("--no-plan drops the plan job, pull_request trigger, and dry-run input", () => {
    const { content, generatedIds } = renderBranchWorkflow({ ...branchBase, plan: false });
    expect(content).not.toMatch(NO_MARKER);
    expect(content).not.toContain("tailor-platform/actions/plan@");
    expect(content).not.toContain("pull_request:");
    expect(content).not.toContain("dry-run:");
    expect(content).not.toContain("inputs:");
    const parsed = parseYAML(content) as { jobs: Record<string, unknown> };
    expect(Object.keys(parsed.jobs)).toEqual(["tailor-deploy"]);
    // deploy runs unconditionally (no `if`)
    expect(content).not.toContain("github.event_name == 'push'");
    expect(generatedIds).not.toContain("tailor-plan");
  });

  test("includes paths + working-directory only when dir != '.'", () => {
    const plain = renderBranchWorkflow(branchBase).content;
    expect(plain).not.toContain("paths:");
    expect(plain).not.toContain("working-directory:");

    const scoped = renderBranchWorkflow({ ...branchBase, workingDirectory: "apps/foo" }).content;
    expect(scoped).not.toMatch(NO_MARKER);
    expect(scoped).toContain('paths: ["apps/foo/**"]');
    // plan generate/login/dry-run and deploy login/generate/deploy
    expect(scoped.match(/working-directory: apps\/foo/g)).toHaveLength(6);
    expect(() => parseYAML(scoped)).not.toThrow();
  });

  test("defaults the environment to the passed environment value", () => {
    const { content } = renderBranchWorkflow({ ...branchBase, environment: "staging" });
    expect(content).not.toMatch(NO_MARKER);
    expect(content).toContain("environment: staging");
  });

  test("setup steps differ by package manager", () => {
    expect(renderBranchWorkflow({ ...branchBase, packageManager: "npm" }).content).toContain(
      "npm ci",
    );
    expect(renderBranchWorkflow({ ...branchBase, packageManager: "bun" }).content).toContain(
      "oven-sh/setup-bun@",
    );
  });

  test("generatedIds list the managed jobs and steps", () => {
    const { generatedIds } = renderBranchWorkflow(branchBase);
    expect(generatedIds).toContain("tailor-plan");
    expect(generatedIds).toContain("tailor-plan/tailor-setup-pnpm");
    expect(generatedIds).toContain("tailor-plan/tailor-plan");
    expect(generatedIds).toContain("tailor-deploy/tailor-deploy");
  });

  test("preserves $ characters in values", () => {
    const { content } = renderBranchWorkflow({ ...branchBase, workingDirectory: "apps/a$&b" });
    expect(content).toContain("working-directory: apps/a$&b");
  });
});

describe("renderTagWorkflow", () => {
  test("no guard: no tag-guard job, no needs/if on plan, parses", () => {
    const { content, generatedIds } = renderTagWorkflow(tagBase);
    expect(content).not.toMatch(NO_MARKER);
    expect(content).toContain('tags: ["v*"]');
    expect(content).not.toContain("tailor-tag-guard");
    expect(content).not.toContain("needs: tailor-tag-guard");
    expect(generatedIds).not.toContain("tailor-tag-guard");
    const parsed = parseYAML(content) as { jobs: Record<string, unknown> };
    expect(Object.keys(parsed.jobs)).toEqual(["tailor-plan", "tailor-deploy"]);
  });

  test("with guard: emits guard job gated by branch reachability", () => {
    const { content, generatedIds } = renderTagWorkflow({ ...tagBase, branch: "main" });
    expect(content).not.toMatch(NO_MARKER);
    expect(content).toContain("tailor-tag-guard:");
    expect(content).toContain('TARGET_BRANCH: "main"');
    expect(content).toContain("needs: tailor-tag-guard");
    expect(content).toContain("needs.tailor-tag-guard.outputs.on-branch == 'true'");
    expect(generatedIds).toContain("tailor-tag-guard");
    const parsed = parseYAML(content) as { jobs: Record<string, unknown> };
    expect(Object.keys(parsed.jobs)).toEqual(["tailor-tag-guard", "tailor-plan", "tailor-deploy"]);
  });

  test("plan job omits github-token (step summary only)", () => {
    const { content } = renderTagWorkflow(tagBase);
    expect(content).not.toContain("github-token:");
  });

  test("custom tag pattern", () => {
    expect(renderTagWorkflow({ ...tagBase, tagPattern: "release-*" }).content).toContain(
      'tags: ["release-*"]',
    );
  });
});

describe("detectDefaultBranch", () => {
  test("strips the origin/ prefix", () => {
    const run = vi.fn().mockReturnValue("origin/main");
    expect(detectDefaultBranch("/repo", run)).toBe("main");
  });

  test("throws an AI-first error when the ref is missing", () => {
    const run = vi.fn().mockReturnValue(null);
    expect(() => detectDefaultBranch("/repo", run)).toThrow(/--branch|set-head/);
  });
});

describe("decideAction", () => {
  const target = {
    kind: "branch" as const,
    workspaceName: "my-app",
    file: ".github/workflows/tailor-my-app.yml",
    templateVersion: 1,
    inputs: {} as never,
    generatedIds: [],
    ejectedIds: [],
    contentHash: hashContent("managed"),
  };

  test("create: no lock entry, no file", () => {
    expect(
      decideAction({ existing: undefined, fileExists: false, currentContent: null, force: false })
        .action,
    ).toBe("create");
  });

  test("conflict: no lock entry but file exists", () => {
    expect(
      decideAction({ existing: undefined, fileExists: true, currentContent: "x", force: false })
        .action,
    ).toBe("conflict");
  });

  test("--force adopts an unmanaged file", () => {
    expect(
      decideAction({ existing: undefined, fileExists: true, currentContent: "x", force: true })
        .action,
    ).toBe("regenerate");
  });

  test("regenerate: lock entry, hash matches", () => {
    expect(
      decideAction({ existing: target, fileExists: true, currentContent: "managed", force: false })
        .action,
    ).toBe("regenerate");
  });

  test("conflict: lock entry, hash mismatch (hand edited)", () => {
    expect(
      decideAction({ existing: target, fileExists: true, currentContent: "edited", force: false })
        .action,
    ).toBe("conflict");
  });

  test("--force overrides a hand edit", () => {
    expect(
      decideAction({ existing: target, fileExists: true, currentContent: "edited", force: true })
        .action,
    ).toBe("regenerate");
  });

  test("restore: lock entry, file missing", () => {
    expect(
      decideAction({ existing: target, fileExists: false, currentContent: null, force: false })
        .action,
    ).toBe("restore");
  });
});

describe("setupGitHub (integration)", () => {
  const testDir = path.join(
    "/tmp",
    `setup-gh-${Date.now()}-${Math.random().toString(36).slice(2)}`,
  );

  const writeConfig = (body: string): void => {
    fs.writeFileSync(path.join(testDir, "tailor.config.ts"), body, "utf-8");
  };

  const baseOptions = (overrides: Partial<SetupGitHubOptions> = {}): SetupGitHubOptions => ({
    tag: false,
    tagPattern: "v*",
    plan: true,
    dir: ".",
    force: false,
    outputDir: testDir,
    branch: "main",
    gitRunner: () => "origin/main",
    loadConfigName: async () => "cfg-app",
    ...overrides,
  });

  beforeEach(() => {
    fs.mkdirSync(testDir, { recursive: true });
    fs.writeFileSync(path.join(testDir, "pnpm-lock.yaml"), "");
    writeConfig(
      `import { defineConfig } from "@tailor-platform/sdk";\nexport default defineConfig({ name: "cfg-app" });\n`,
    );
  });

  afterEach(() => fs.rmSync(testDir, { recursive: true, force: true }));

  test("generates a workflow + lock and derives the name from config", async () => {
    await setupGitHub(baseOptions({ workspaceName: undefined }));
    const wf = path.join(testDir, ".github/workflows/tailor-cfg-app.yml");
    expect(fs.existsSync(wf)).toBe(true);
    const lock = readLock(testDir);
    expect(lock?.targets).toHaveLength(1);
    expect(lock?.targets[0]).toMatchObject({ kind: "branch", workspaceName: "cfg-app" });
    expect(lock?.targets[0]?.contentHash).toBe(hashContent(fs.readFileSync(wf, "utf-8")));
  });

  test("defaults the environment to the workspace name", async () => {
    await setupGitHub(baseOptions({ workspaceName: "my-app" }));
    const wf = fs.readFileSync(path.join(testDir, ".github/workflows/tailor-my-app.yml"), "utf-8");
    expect(wf.match(/environment: my-app/g)).toHaveLength(2);
    expect(readLock(testDir)?.targets[0]?.inputs.environment).toBe("my-app");
  });

  test("uses an explicit --environment over the workspace name", async () => {
    await setupGitHub(baseOptions({ workspaceName: "my-app", environment: "production" }));
    const wf = fs.readFileSync(path.join(testDir, ".github/workflows/tailor-my-app.yml"), "utf-8");
    expect(wf).toContain("environment: production");
    expect(readLock(testDir)?.targets[0]?.inputs.environment).toBe("production");
  });

  test("injects an app id when missing", async () => {
    await setupGitHub(baseOptions({ workspaceName: "my-app" }));
    expect(fs.readFileSync(path.join(testDir, "tailor.config.ts"), "utf-8")).toMatch(/id:\s*"/);
  });

  test("silent regenerate when hash matches", async () => {
    const opts = baseOptions({ workspaceName: "my-app" });
    await setupGitHub(opts);
    await expect(setupGitHub(opts)).resolves.toBeUndefined();
  });

  test("errors on a hand-edited file without --force", async () => {
    const opts = baseOptions({ workspaceName: "my-app" });
    await setupGitHub(opts);
    const wf = path.join(testDir, ".github/workflows/tailor-my-app.yml");
    fs.appendFileSync(wf, "\n# hand edit\n");
    await expect(setupGitHub(opts)).rejects.toThrow(/edited by hand|--force/);
    await expect(setupGitHub({ ...opts, force: true })).resolves.toBeUndefined();
  });

  test("errors on an unmanaged pre-existing file", async () => {
    const wf = path.join(testDir, ".github/workflows/tailor-my-app.yml");
    fs.mkdirSync(path.dirname(wf), { recursive: true });
    fs.writeFileSync(wf, "name: hand written\n");
    await expect(setupGitHub(baseOptions({ workspaceName: "my-app" }))).rejects.toThrow(
      /unmanaged|--force/,
    );
  });

  test("restores a deleted file from the lock", async () => {
    const opts = baseOptions({ workspaceName: "my-app" });
    await setupGitHub(opts);
    const wf = path.join(testDir, ".github/workflows/tailor-my-app.yml");
    fs.rmSync(wf);
    await setupGitHub(opts);
    expect(fs.existsSync(wf)).toBe(true);
  });

  test("rejects an invalid workspace name", async () => {
    await expect(setupGitHub(baseOptions({ workspaceName: "Bad_Name" }))).rejects.toThrow(
      /Invalid workspace name/,
    );
  });

  test("rejects --no-plan with --tag", async () => {
    await expect(
      setupGitHub(baseOptions({ workspaceName: "my-app", tag: true, plan: false })),
    ).rejects.toThrow(/--no-plan/);
  });

  test("rejects a branch name with YAML-unsafe characters", async () => {
    await expect(
      setupGitHub(baseOptions({ workspaceName: "my-app", branch: "feat,bar" })),
    ).rejects.toThrow(/Invalid branch name/);
  });

  test("rejects a tag pattern with YAML-unsafe characters", async () => {
    await expect(
      setupGitHub(
        baseOptions({ workspaceName: "my-app", tag: true, tagPattern: "v* #${{ evil }}" }),
      ),
    ).rejects.toThrow(/Invalid tag pattern/);
  });

  test("rejects an environment name with YAML-unsafe characters", async () => {
    await expect(
      setupGitHub(baseOptions({ workspaceName: "my-app", environment: "prod: evil" })),
    ).rejects.toThrow(/Invalid environment name/);
  });

  test("rejects a --dir with YAML-unsafe characters", async () => {
    await expect(
      setupGitHub(baseOptions({ workspaceName: "my-app", dir: "apps/${{ evil }}" })),
    ).rejects.toThrow(/Invalid --dir/);
  });

  test("normalizes a --dir with ./ prefix and trailing slash", async () => {
    fs.mkdirSync(path.join(testDir, "apps/backend"), { recursive: true });
    fs.writeFileSync(
      path.join(testDir, "apps/backend/tailor.config.ts"),
      `import { defineConfig } from "@tailor-platform/sdk";\nexport default defineConfig({ name: "my-app" });\n`,
      "utf-8",
    );
    const opts = baseOptions({
      workspaceName: "my-app",
      dir: "./apps/backend/",
      loadConfigName: async () => "my-app",
    });
    await setupGitHub(opts);
    const wf = fs.readFileSync(path.join(testDir, ".github/workflows/tailor-my-app.yml"), "utf-8");
    expect(wf).toContain('paths: ["apps/backend/**"]');
    expect(wf).not.toContain("apps/backend//");
    expect(wf).not.toContain('["./apps');
  });

  test("errors when the config is missing", async () => {
    fs.rmSync(path.join(testDir, "tailor.config.ts"));
    await expect(setupGitHub(baseOptions({ workspaceName: "my-app" }))).rejects.toThrow(
      /tailor\.config\.ts not found/,
    );
  });

  test("conflict on same path with different kind", async () => {
    await setupGitHub(baseOptions({ workspaceName: "my-app" }));
    await expect(
      setupGitHub(baseOptions({ workspaceName: "my-app", tag: true, branch: undefined })),
    ).rejects.toThrow(/conflicts with this tag target|--workspace-name/);
  });
});
