/**
 * Auto-generated Kysely types for migration script.
 * These types reflect the database schema state at this migration point.
 *
 * DO NOT EDIT - This file is auto-generated by the migration system.
 */

import {
  type ColumnType,
  type Transaction as KyselyTransaction,
} from "@tailor-platform/sdk/kysely";
import type { Env } from "@tailor-platform/sdk";

type Timestamp = ColumnType<Date, Date | string, Date | string>;
type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

interface Database {
  Event: {
    id: Generated<string>;
    name: "CLICK" | "VIEW" | "PURCHASE";
    createdAt: Timestamp;
    updatedAt: ColumnType<Date | null, Date | string, Date | string>;
  };
}

export type Transaction = KyselyTransaction<Database>;

/** Context passed as the second argument to the migration's `main` function. */
export type MigrationContext = {
  env: keyof Env extends never ? Record<string, string | number | boolean> : Env;
};
