import * as fs from "node:fs";
import * as path from "pathe";
import { describe, expect, test } from "vitest";
import { tempCwd } from "#/cli/shared/test-helpers/temp-cwd";
import { findDateRepresentationConflicts } from "./date-representation-conflict";
import { generateTypeDefinition } from "./type-generator";
import type { AppConfig } from "#/configure/config/types";

function writeFile(filePath: string, content: string): void {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, content);
}

function writeTailorDts(
  filePath: string,
  defaultDateRepresentation: AppConfig["defaultDateRepresentation"],
): void {
  writeFile(
    filePath,
    generateTypeDefinition(
      undefined,
      undefined,
      undefined,
      undefined,
      undefined,
      undefined,
      undefined,
      undefined,
      undefined,
      defaultDateRepresentation,
    ),
  );
}

describe("findDateRepresentationConflicts", () => {
  test("reports another tailor.d.ts in the same tsconfig that declares a different default", () => {
    using tmp = tempCwd("sdk-date-conflict-");
    writeFile(path.join(tmp.dir, "tsconfig.json"), JSON.stringify({ include: ["**/*.ts"] }));
    writeTailorDts(path.join(tmp.dir, "apps/user/tailor.d.ts"), undefined);

    expect(
      findDateRepresentationConflicts(path.join(tmp.dir, "apps/admin/tailor.d.ts"), "temporal"),
    ).toEqual({
      tsconfigPath: path.join(tmp.dir, "tsconfig.json"),
      conflicts: [{ file: path.join(tmp.dir, "apps/user/tailor.d.ts"), representation: undefined }],
    });
  });

  test("reports nothing when every tailor.d.ts in the tsconfig declares the same default", () => {
    using tmp = tempCwd("sdk-date-conflict-same-");
    writeFile(path.join(tmp.dir, "tsconfig.json"), JSON.stringify({ include: ["**/*.ts"] }));
    writeTailorDts(path.join(tmp.dir, "apps/user/tailor.d.ts"), "temporal");

    expect(
      findDateRepresentationConflicts(path.join(tmp.dir, "apps/admin/tailor.d.ts"), "temporal")
        ?.conflicts,
    ).toEqual([]);
  });

  test("ignores tailor.d.ts files that a different tsconfig includes", () => {
    using tmp = tempCwd("sdk-date-conflict-split-");
    for (const app of ["admin", "user"]) {
      writeFile(
        path.join(tmp.dir, "apps", app, "tsconfig.json"),
        JSON.stringify({ include: ["**/*.ts"] }),
      );
    }
    writeTailorDts(path.join(tmp.dir, "apps/user/tailor.d.ts"), undefined);

    expect(
      findDateRepresentationConflicts(path.join(tmp.dir, "apps/admin/tailor.d.ts"), "temporal")
        ?.conflicts,
    ).toEqual([]);
  });

  test("treats a tailor.d.ts generated before defaultDateRepresentation existed as unset", () => {
    using tmp = tempCwd("sdk-date-conflict-legacy-");
    writeFile(path.join(tmp.dir, "tsconfig.json"), JSON.stringify({ include: ["**/*.ts"] }));
    writeFile(
      path.join(tmp.dir, "apps/user/tailor.d.ts"),
      [
        "// This file is auto-generated by @tailor-platform/sdk",
        'declare module "@tailor-platform/sdk" {',
        "  interface Env {}",
        "}",
        "export {};",
        "",
      ].join("\n"),
    );

    expect(
      findDateRepresentationConflicts(path.join(tmp.dir, "apps/admin/tailor.d.ts"), "temporal")
        ?.conflicts,
    ).toEqual([{ file: path.join(tmp.dir, "apps/user/tailor.d.ts"), representation: undefined }]);
  });

  test("ignores declaration files the SDK did not generate", () => {
    using tmp = tempCwd("sdk-date-conflict-foreign-");
    writeFile(path.join(tmp.dir, "tsconfig.json"), JSON.stringify({ include: ["**/*.ts"] }));
    writeFile(path.join(tmp.dir, "types/env.d.ts"), "declare const BUILD_ID: string;\n");

    expect(
      findDateRepresentationConflicts(path.join(tmp.dir, "apps/admin/tailor.d.ts"), "temporal")
        ?.conflicts,
    ).toEqual([]);
  });

  test("returns undefined when no tsconfig includes the tailor.d.ts", () => {
    using tmp = tempCwd("sdk-date-conflict-none-");

    expect(
      findDateRepresentationConflicts(path.join(tmp.dir, "tailor.d.ts"), "temporal"),
    ).toBeUndefined();
  });
});
