import * as fs from "node:fs";
import * as path from "pathe";
import { logger } from "@/cli/shared/logger";
import ml from "@/utils/multiline";
import type { AppConfig } from "@/configure/config/types";

export interface AttributeMapConfig {
  [key: string]: string;
}

export type AttributeListConfig = readonly string[];

interface ExtractedAttributes {
  attributeMap?: AttributeMapConfig;
  attributeList?: AttributeListConfig;
  env?: Record<string, string | number | boolean>;
  machineUserNames?: string[];
  idpNames?: string[];
}

type AttributeFieldLike = {
  type?: string;
  metadata?: {
    array?: boolean;
    allowedValues?: Array<{ value: string }>;
  };
};

/**
 * Extract attribute definitions from the app config for user-defined typing.
 * @param config - Application config to inspect
 * @returns Extracted attribute map/list and env values
 * @internal
 */
export function extractAttributesFromConfig(config: AppConfig): ExtractedAttributes {
  return collectAttributesFromConfig(config);
}

/**
 * Generate the contents of the user-defined type definition file.
 * @param attributeMap - Attribute map configuration
 * @param attributeList - Attribute list configuration
 * @param env - Environment configuration
 * @param machineUserNames - Registered machine user names (used to narrow `authInvoker` strings)
 * @param idpNames - Registered IdP names (used to narrow `idpUser*Trigger({ idp })` strings)
 * @returns Generated type definition source
 */
export function generateTypeDefinition(
  attributeMap: AttributeMapConfig | undefined,
  attributeList: AttributeListConfig | undefined,
  env?: Record<string, string | number | boolean>,
  machineUserNames?: readonly string[],
  idpNames?: readonly string[],
): string {
  // Generate AttributeMap interface
  // attributeMap values are type string representations (e.g., "string", "boolean", "string[]")
  const mapFields = attributeMap
    ? Object.entries(attributeMap)
        .map(([key, value]) => `    ${key}: ${value};`)
        .join("\n")
    : "";

  const mapBody =
    !attributeMap || Object.keys(attributeMap).length === 0
      ? "{}"
      : `{
${mapFields}
  }`;

  // Generate AttributeList type as a tuple of strings based on the length
  const listType = attributeList ? `[${attributeList.map(() => "string").join(", ")}]` : "[]";

  // Use interface with __tuple marker for declaration merging and tuple type support
  const listBody = `{
    __tuple?: ${listType};
  }`;

  // Generate Env interface
  const envFields = env
    ? Object.entries(env)
        .map(([key, value]) => {
          const valueType = typeof value === "string" ? `"${value}"` : String(value);
          return `    ${key}: ${valueType};`;
        })
        .join("\n")
    : "";

  const envBody =
    !env || Object.keys(env).length === 0
      ? "{}"
      : `{
${envFields}
  }`;

  // Generate MachineUserNameRegistry interface.
  // Quote keys only when they aren't valid TypeScript identifiers — matches
  // the formatter (oxfmt) output so subsequent format passes are no-ops.
  const isValidIdentifier = (s: string): boolean => /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(s);
  const machineUserFields = machineUserNames?.length
    ? machineUserNames
        .map((name) => `    ${isValidIdentifier(name) ? name : JSON.stringify(name)}: true;`)
        .join("\n")
    : "";

  const machineUserBody =
    !machineUserNames || machineUserNames.length === 0
      ? "{}"
      : `{
${machineUserFields}
  }`;

  // Generate IdpNameRegistry interface (same quoting rules as machine users).
  const idpNameFields = idpNames?.length
    ? idpNames
        .map((name) => `    ${isValidIdentifier(name) ? name : JSON.stringify(name)}: true;`)
        .join("\n")
    : "";

  const idpNameBody =
    !idpNames || idpNames.length === 0
      ? "{}"
      : `{
${idpNameFields}
  }`;

  return ml /* ts */ `
// This file is auto-generated by @tailor-platform/sdk
// Do not edit this file manually
// Regenerated automatically when running 'tailor-sdk deploy' or 'tailor-sdk generate'

declare module "@tailor-platform/sdk" {
  interface AttributeMap ${mapBody}
  interface AttributeList ${listBody}
  interface Env ${envBody}
  interface MachineUserNameRegistry ${machineUserBody}
  interface IdpNameRegistry ${idpNameBody}
}

export {};

`;
}

function collectAttributesFromConfig(config: AppConfig): ExtractedAttributes {
  // De-duplicate IdP names so duplicates in config don't emit duplicate
  // `IdpNameRegistry` keys (which would be invalid TypeScript).
  const idpNames = config.idp?.length ? [...new Set(config.idp.map((idp) => idp.name))] : undefined;

  const auth = config.auth;
  if (!auth || typeof auth !== "object") {
    return idpNames ? { idpNames } : {};
  }

  // Extract machine user names from auth.machineUsers (available regardless of userProfile vs. machineUserAttributes)
  const machineUsersObj = (auth as { machineUsers?: Record<string, unknown> }).machineUsers;
  const machineUserNames =
    machineUsersObj && typeof machineUsersObj === "object"
      ? Object.keys(machineUsersObj)
      : undefined;

  const inferAttributeType = (field?: AttributeFieldLike): string => {
    const type = field?.type;
    const metadata = field?.metadata;

    // Default to string if no metadata
    if (!metadata) {
      return "string";
    }

    let typeStr = "string";

    if (type === "boolean") {
      typeStr = "boolean";
    } else if (type === "enum" && metadata.allowedValues) {
      // Generate union type from enum values
      typeStr = metadata.allowedValues.map((v) => `"${v.value}"`).join(" | ");
    }

    // Add array suffix if needed
    if (metadata.array) {
      typeStr += "[]";
    }

    return typeStr;
  };

  // Check if auth has userProfile with attributes/attributeList
  if ("userProfile" in auth) {
    const userProfile = (
      auth as {
        userProfile?: {
          type?: {
            fields?: Record<string, AttributeFieldLike>;
          };
          attributes?: Record<string, true>;
          attributeList?: AttributeListConfig;
        };
      }
    ).userProfile;

    const attributes = userProfile?.attributes;
    const fields = userProfile?.type?.fields;
    const attributeList = userProfile?.attributeList;

    // Convert attributes to AttributeMapConfig by inferring types from field metadata
    const attributeMap: AttributeMapConfig | undefined = attributes
      ? Object.keys(attributes).reduce((acc, key) => {
          acc[key] = inferAttributeType(fields?.[key]);
          return acc;
        }, {} as AttributeMapConfig)
      : undefined;

    return {
      attributeMap,
      attributeList,
      machineUserNames,
      idpNames,
    };
  }

  if ("machineUserAttributes" in auth) {
    const machineUserAttributes = (
      auth as {
        machineUserAttributes?: Record<string, AttributeFieldLike>;
      }
    ).machineUserAttributes;

    if (!machineUserAttributes) {
      return { machineUserNames, idpNames };
    }

    const attributeMap = Object.entries(machineUserAttributes).reduce((acc, [key, field]) => {
      acc[key] = inferAttributeType(field);
      return acc;
    }, {} as AttributeMapConfig);

    return {
      attributeMap,
      machineUserNames,
      idpNames,
    };
  }

  return { machineUserNames, idpNames };
}

/**
 * Resolve the output path for the generated type definition file.
 *
 * When the `TAILOR_PLATFORM_SDK_DTS_PATH` environment variable is set, the value is
 * used as the output path (resolved relative to cwd when relative).
 * Otherwise, the file is written next to the config file as `tailor.d.ts`.
 * @param configPath - Path to Tailor config file
 * @returns Absolute path to the type definition file
 */
export function resolveTypeDefinitionPath(configPath: string): string {
  const envPath = process.env.TAILOR_PLATFORM_SDK_DTS_PATH;
  if (envPath) {
    return path.resolve(envPath);
  }
  return path.join(path.dirname(path.resolve(configPath)), "tailor.d.ts");
}

/**
 * Options for generating user type definitions
 */
interface GenerateUserTypesOptions {
  /** Application config */
  config: AppConfig;
  /** Path to Tailor config file */
  configPath: string;
}

/**
 * Generate user type definitions from the app config and write them to disk.
 * @param options - Generation options
 * @returns Promise that resolves when types are generated
 */
export async function generateUserTypes(options: GenerateUserTypesOptions): Promise<void> {
  const { config, configPath } = options;
  try {
    const { attributeMap, attributeList, machineUserNames, idpNames } =
      extractAttributesFromConfig(config);
    if (!attributeMap && !attributeList) {
      logger.info("No attributes found in configuration", { mode: "plain" });
    }

    if (attributeMap) {
      logger.debug(`Extracted AttributeMap: ${JSON.stringify(attributeMap)}`);
    }
    if (attributeList) {
      logger.debug(`Extracted AttributeList: ${JSON.stringify(attributeList)}`);
    }
    if (machineUserNames?.length) {
      logger.debug(`Extracted MachineUserNames: ${JSON.stringify(machineUserNames)}`);
    }
    if (idpNames?.length) {
      logger.debug(`Extracted IdpNames: ${JSON.stringify(idpNames)}`);
    }

    const env = config.env;
    if (env) {
      logger.debug(`Extracted Env: ${JSON.stringify(env)}`);
    }

    // Generate type definition
    const typeDefContent = generateTypeDefinition(
      attributeMap,
      attributeList,
      env,
      machineUserNames,
      idpNames,
    );
    const outputPath = resolveTypeDefinitionPath(configPath);

    // Write to file
    fs.mkdirSync(path.dirname(outputPath), { recursive: true });
    fs.writeFileSync(outputPath, typeDefContent);
    const relativePath = path.relative(process.cwd(), outputPath);
    logger.newline();
    logger.success(`Generated type definitions: ${relativePath}`, {
      mode: "plain",
    });
  } catch (error) {
    logger.error("Error generating types");
    logger.error(String(error));
    // Don't throw - this should not block apply/generate
  }
}
