// @generated by protoc-gen-es v2.6.3
// @generated from file tailor/fieldmask/v1/option.proto (package tailor.fieldmask.v1, syntax proto3)
/* eslint-disable */

import { extDesc, fileDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_descriptor } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file tailor/fieldmask/v1/option.proto.
 */
export const file_tailor_fieldmask_v1_option = /*@__PURE__*/
  fileDesc("CiB0YWlsb3IvZmllbGRtYXNrL3YxL29wdGlvbi5wcm90bxITdGFpbG9yLmZpZWxkbWFzay52MTo1CgVtYXNrcxIdLmdvb2dsZS5wcm90b2J1Zi5GaWVsZE9wdGlvbnMYkb8FIAMoCVIFbWFza3NiBnByb3RvMw", [file_google_protobuf_descriptor]);

/**
 * @generated from extension: repeated string masks = 90001;
 */
export const masks = /*@__PURE__*/
  extDesc(file_tailor_fieldmask_v1_option, 0);

