import * as fs from "node:fs";
import { logger, styles, prompt } from "@tailor-platform/sdk/cli";
import { resolveWithinRoot } from "./check";
import { LOCK_VERSION, readLock, writeLock, type LockTarget } from "./lock";

export type DeleteOptions = {
  /** Repo-relative paths to managed workflow files, as printed by `setup <target>`. */
  files: string[];
  /** Skip the confirmation prompt. */
  yes: boolean;
  outputDir: string;
};

// Mirrors the --dir normalization in generate.ts's resolve(): POSIX separators,
// collapsed duplicate slashes, no leading "./" or trailing "/", so a path typed
// with either style still matches the posix-normalized `file` recorded in the lock.
function normalizeRelPath(input: string): string {
  return input
    .replaceAll("\\", "/")
    .replace(/\/{2,}/g, "/")
    .replace(/^\.\//, "")
    .replace(/\/$/, "");
}

type Match = { relPath: string; absPath: string; target: LockTarget };

function targetKey(target: LockTarget): string {
  return `${target.kind}:${target.workspaceName}`;
}

function resolveMatch(outputDir: string, targets: readonly LockTarget[], input: string): Match {
  const relPath = normalizeRelPath(input);
  const absPath = resolveWithinRoot(outputDir, relPath);
  if (absPath === null) {
    throw new Error(`"${input}" must be a path inside the repository.`);
  }
  const target = targets.find((t) => t.file === relPath);
  if (!target) {
    throw new Error(
      `"${relPath}" is not a managed workflow file (not recorded in .github/tailor.lock). ` +
        "Only files generated by `tailor setup` can be deleted with this command.",
    );
  }
  return { relPath, absPath, target };
}

/**
 * Delete managed workflow files and their `.github/tailor.lock` entries.
 *
 * Refuses to touch files that are not recorded in the lock, so it never
 * deletes hand-written workflows.
 * @param options - Delete options
 */
export async function setupDelete(options: DeleteOptions): Promise<void> {
  const { outputDir, yes } = options;
  const lock = readLock(outputDir);
  if (!lock || lock.targets.length === 0) {
    throw new Error(
      "No managed workflows found (.github/tailor.lock is missing or empty). " +
        "Run `tailor setup ci branch` (or another setup subcommand) first.",
    );
  }

  const relPaths = [...new Set(options.files.map(normalizeRelPath))];
  const matches = relPaths.map((relPath) => resolveMatch(outputDir, lock.targets, relPath));

  if (!yes) {
    const list = matches.map((m) => m.relPath).join("\n  ");
    const confirmed = await prompt.confirm({
      message:
        `This will delete the following file(s) and their .github/tailor.lock entries:\n  ${list}\n` +
        "Continue?",
      default: false,
    });
    if (!confirmed) {
      throw new Error("Delete cancelled. No files were changed.");
    }
  }

  const remaining = [...lock.targets];
  try {
    for (const { relPath, absPath, target } of matches) {
      fs.rmSync(absPath, { force: true });
      const index = remaining.findIndex((t) => targetKey(t) === targetKey(target));
      if (index !== -1) remaining.splice(index, 1);
      logger.success(`Deleted ${styles.path(relPath)} (${target.kind} ${target.workspaceName})`);
    }
  } finally {
    if (remaining.length !== lock.targets.length) {
      writeLock(outputDir, { ...lock, version: LOCK_VERSION, targets: remaining });
    }
  }
}
