// Generates the pinned script expression for SDK built-in TailorDB hooks whose
// `Function.prototype.toString()` output is embedded verbatim into deployed schemas
// and migration diffs (see parser/service/tailordb/hooks-validate-precompiled-expr.ts).
// A hand-typed copy of the hook's source drifts silently from the real function; this
// extracts the exact source text of each target declaration via oxc-parser and wraps
// it with the same call-argument template `field.ts` uses for user-authored hooks, so
// there is exactly one place that defines each hook's behavior.
import { execSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { parseSync } from "oxc-parser";
import {
  buildHookArgsObject,
  type ScriptExprKind,
} from "../src/parser/service/tailordb/hook-args-object.ts";
import { assertParsableExpression } from "../src/utils/script-expr.ts";

const here = dirname(fileURLToPath(import.meta.url));
const sdkRoot = resolve(here, "..");

type PinTarget = {
  /** Source file the hook `const` is declared in. */
  sourceFile: string;
  /** Name of the `const <name> = ...` declaration to extract. */
  declarationName: string;
  /** Kind of hook, used to build the matching call-argument object. */
  kind: ScriptExprKind;
  /** File to write the generated expr constant to. */
  outputFile: string;
  /** Name of the exported constant. */
  exportName: string;
};

const TARGETS: PinTarget[] = [
  {
    sourceFile: "src/configure/services/tailordb/schema.ts",
    declarationName: "timestampsUpdatedAtHook",
    kind: "hooks.update",
    outputFile: "src/configure/services/tailordb/timestamps-updated-at-hook.generated.ts",
    exportName: "TIMESTAMPS_UPDATED_AT_HOOK_EXPR",
  },
];

function extractDeclarationInitializerSource(sourceFile: string, declarationName: string): string {
  const source = readFileSync(sourceFile, "utf-8");
  const { program } = parseSync(sourceFile, source);
  for (const stmt of program.body) {
    if (stmt.type !== "VariableDeclaration") continue;
    for (const decl of stmt.declarations) {
      if (decl.id.type === "Identifier" && decl.id.name === declarationName && decl.init) {
        return source.slice(decl.init.start, decl.init.end);
      }
    }
  }
  throw new Error(`Could not find \`const ${declarationName} = ...\` in ${sourceFile}`);
}

/**
 * Format `content` the same way `pnpm format` would, so `--check` matches what's on disk.
 * @param content - Source text to format.
 * @param outputFile - Path oxfmt should infer the parser/style from.
 * @returns The formatted source text.
 */
function formatWithOxfmt(content: string, outputFile: string): string {
  // Runs through the platform shell (`execSync`, not `execFileSync`) so pnpm's
  // `.cmd` shim resolves on Windows - `execFileSync` can't launch a `.cmd` file
  // directly (EINVAL) without `shell: true`, and passing `shell: true` alongside
  // a separate `args` array is what Node's execFile* family deprecates instead.
  // `outputFile` is always one of this file's own hardcoded TARGETS paths, never
  // externally supplied, so building this literally is safe.
  return execSync(`pnpm exec oxfmt --stdin-filepath=${JSON.stringify(outputFile)}`, {
    input: content,
    encoding: "utf-8",
  });
}

function renderTarget(target: PinTarget): string {
  const fnSource = extractDeclarationInitializerSource(
    resolve(sdkRoot, target.sourceFile),
    target.declarationName,
  );
  const expr = assertParsableExpression(
    `(${fnSource})(${buildHookArgsObject(target.kind)})`,
    `${target.declarationName} in ${target.sourceFile}`,
  );
  const content =
    `// Generated by scripts/generate-precompiled-hooks.ts from ${target.sourceFile}. Do not edit manually.\n` +
    `export const ${target.exportName} = ${JSON.stringify(expr)};\n`;
  return formatWithOxfmt(content, target.outputFile);
}

function parseMode(args: string[]): "write" | "check" {
  const modes = args.filter((arg) => arg === "--check" || arg === "--write");
  if (modes.length !== 1 || modes.length !== args.length) {
    process.stderr.write(
      "Usage: node --experimental-strip-types scripts/generate-precompiled-hooks.ts --check|--write\n",
    );
    process.exit(2);
  }
  return modes[0] === "--write" ? "write" : "check";
}

const mode = parseMode(process.argv.slice(2));

let outdated = false;
for (const target of TARGETS) {
  const content = renderTarget(target);
  const outputPath = resolve(sdkRoot, target.outputFile);

  if (mode === "write") {
    writeFileSync(outputPath, content, "utf-8");
    process.stderr.write(`Wrote ${target.outputFile}\n`);
    continue;
  }

  let actual: string | null;
  try {
    actual = readFileSync(outputPath, "utf-8");
  } catch {
    actual = null;
  }
  if (actual !== content) {
    outdated = true;
    process.stderr.write(`${target.outputFile} is out of date. Run \`pnpm generate\`.\n`);
  }
}

if (mode === "check" && outdated) {
  process.exit(1);
}
