/**
 * Auto-generated Kysely types for migration script.
 * These types reflect the database schema state at this migration point.
 *
 * DO NOT EDIT - This file is auto-generated by the migration system.
 */

import { type ColumnType, type Transaction as KyselyTransaction } from "kysely";

type Timestamp = ColumnType<Date, Date | string, Date | string>;
type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

interface Database {
  Customer: {
    id: Generated<string>;
    name: string | null;
    email: string;
    phone: string | null;
    country: string | null;
    postalCode: string;
    address: string | null;
    city: string | null;
    fullAddress: string;
    state: string;
    createdAt: Timestamp;
    updatedAt: Timestamp | null;
  };
  Invoice: {
    id: Generated<string>;
    invoiceNumber: string;
    salesOrderID: string;
    amount: number | null;
    sequentialId: number;
    status: "draft" | "sent" | "paid" | "cancelled" | null;
    createdAt: Timestamp;
    updatedAt: Timestamp | null;
  };
  NestedProfile: {
    id: Generated<string>;
    userInfo: string;
    metadata: string;
    archived: boolean | null;
    createdAt: Timestamp;
    updatedAt: Timestamp | null;
  };
  PurchaseOrder: {
    id: Generated<string>;
    supplierID: string;
    totalPrice: number;
    discount: number | null;
    status: string;
    attachedFiles: string[];
    createdAt: Timestamp;
    updatedAt: Timestamp | null;
  };
  SalesOrder: {
    id: Generated<string>;
    customerID: string;
    approvedByUserIDs: string[] | null;
    totalPrice: number | null;
    discount: number | null;
    status: string | null;
    cancelReason: string | null;
    canceledAt: Timestamp | null;
    createdAt: Timestamp;
    updatedAt: Timestamp | null;
  };
  SalesOrderCreated: {
    id: Generated<string>;
    salesOrderID: string;
    customerID: string;
    totalPrice: number | null;
    status: string | null;
  };
  Selfie: {
    id: Generated<string>;
    name: string;
    parentID: string | null;
    dependId: string | null;
  };
  Supplier: {
    id: Generated<string>;
    name: string;
    phone: string;
    fax: string | null;
    email: string | null;
    postalCode: string;
    country: string;
    state: "Alabama" | "Alaska";
    city: string;
    createdAt: Timestamp;
    updatedAt: Timestamp | null;
  };
  User: {
    id: Generated<string>;
    name: string;
    email: string;
    createdAt: Timestamp;
    updatedAt: Timestamp | null;
    status: string | null;
    department: string | null;
    role: ColumnType<"MANAGER" | null, "MANAGER", "MANAGER">;
  };
  UserLog: {
    id: Generated<string>;
    userID: string;
    message: string;
    createdAt: Timestamp;
    updatedAt: Timestamp | null;
  };
  UserSetting: {
    id: Generated<string>;
    language: "jp" | "en";
    userID: string;
    createdAt: Timestamp;
    updatedAt: Timestamp | null;
  };
}

export type Transaction = KyselyTransaction<Database>;
