#!/usr/bin/env node

import { fileURLToPath } from "node:url";
import * as path from "pathe";
import { readPackageJSON } from "pkg-types";
import { defineCommand, runMain } from "politty";
import { z } from "zod";
import { seedApplyCommand } from "./apply";
import { commonArgs } from "./shared/args";
import { logger } from "./shared/logger";
import { seedValidateCommand } from "./validate";

function hasFormat(error: unknown): error is { format(): string } {
  return (
    typeof error === "object" &&
    error !== null &&
    typeof (error as { format?: unknown }).format === "function"
  );
}

const packageRoot = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");
const packageJson = await readPackageJSON(packageRoot);

const mainCommand = defineCommand({
  name: "tailor-seed",
  description:
    "Seed TailorDB and IdP data from JSONL files generated by seedPlugin.\n" +
    "Tailor CLI plugin: installed alongside the Tailor CLI, it runs as `tailor seed <command>`.",
  subCommands: {
    apply: seedApplyCommand,
    validate: seedValidateCommand,
  },
});

void runMain(mainCommand, {
  version: packageJson.version ?? "0.0.0",
  // strip unknown keys
  globalArgs: z.object(commonArgs),
  displayErrors: false,
  // Render the SDK's CLIError format (details/suggestion) like the host CLI does.
  cleanup: ({ error }) => {
    if (!error) return;
    if (hasFormat(error)) {
      logger.log(error.format());
    } else if (error instanceof Error) {
      logger.error(error.message);
    } else {
      logger.error(`Unknown error: ${String(error)}`);
    }
    if (error instanceof Error && error.stack) {
      logger.debug(`\nStack trace:\n${error.stack}`);
    }
  },
});
