name: Install aqua
description: Install aqua package manager

inputs:
  aqua_version:
    description: "Version of aqua to install"
    required: false
    default: "v2.53.2"

runs:
  using: composite
  steps:
    - name: Install aqua
      uses: aquaproj/aqua-installer@11dd79b4e498d471a9385aa9fb7f62bb5f52a73c # v4.0.4
      with:
        aqua_version: ${{ inputs.aqua_version }}
