import type { TailorAnyDBType } from "@/configure/services/tailordb";
import type { TailorAnyField } from "@/configure/types";

/**
 * Interface for plugin configuration mapping.
 * Extend this interface via declaration merging to add typed plugin configs.
 *
 * The `Fields` type parameter provides field names from the type being configured,
 * enabling type-safe field references in plugin configs.
 * @example
 * ```typescript
 * // In your plugin package or types file:
 * declare module "@tailor-platform/sdk" {
 *   interface PluginConfigs<Fields extends string> {
 *     "@my-company/i18n": {
 *       labels: Partial<Record<Fields, { ja: string; en: string }>>;
 *     };
 *   }
 * }
 * ```
 */
// Fields parameter is used by declaration merging in user-defined.d.ts
// oxlint-disable-next-line no-unused-vars
export interface PluginConfigs<Fields extends string = string> {
  // Built-in plugins with simple configs (not field-aware)
  "@tailor-platform/changeset": true;
  "@tailor-platform/audit-log": true;
}

/**
 * Plugin attachment stored on TailorAnyDBType instances.
 * This is the configuration passed via `.plugin()` method.
 */
export interface PluginAttachment {
  pluginId: string;
  config: unknown;
}

/**
 * Context passed to plugin's process method
 */
export interface PluginProcessContext<Config = unknown> {
  /** The raw TailorDB type being processed */
  type: TailorAnyDBType;
  /** Plugin-specific configuration passed via .plugin() method */
  config: Config;
  /** Namespace of the TailorDB type */
  namespace: string;
}

/**
 * Context passed to plugin's processStandalone method.
 * Used for plugins that generate types without requiring a source type.
 */
export interface StandalonePluginProcessContext<Config = unknown> {
  /** Plugin-specific configuration passed via definePlugins() */
  config: Config;
  /** Target namespace for generated types */
  namespace: string;
}

/**
 * Interface representing a TailorDB type for plugin output.
 * This interface is satisfied by db.type() instances.
 */
export interface TailorDBTypeForPlugin {
  /** The name of the type */
  readonly name: string;
  /** The field definitions */
  readonly fields: Record<string, unknown>;
}

/**
 * Type generated by a plugin - use db.type() to create these.
 */
export type PluginGeneratedType = TailorDBTypeForPlugin;

/**
 * Map of generated types keyed by kind identifier.
 * The kind is used to generate distinct TypeScript type files for each generated type.
 * @example
 * ```typescript
 * {
 *   request: changeRequest,
 *   step: changeStep,
 *   approval: changeApproval,
 * }
 * ```
 */
export type PluginGeneratedTypes = Record<string, PluginGeneratedType>;

/**
 * Resolver definition generated by a plugin.
 * Fields can be TailorDB field instances or raw field definitions.
 */
export interface PluginGeneratedResolver {
  name: string;
  operation: "query" | "mutation";
  inputFields?: Record<string, unknown>;
  outputFields: Record<string, unknown>;
  /** Function body code as string */
  body: string;
}

/**
 * Record trigger configuration for plugin-generated executors
 */
export interface PluginRecordTriggerConfig {
  kind: "recordCreated" | "recordUpdated" | "recordDeleted";
  /** TailorDB type name for record triggers */
  typeName: string;
}

/**
 * Schedule trigger configuration for plugin-generated executors
 */
export interface PluginScheduleTriggerConfig {
  kind: "schedule";
  /** Cron expression */
  cron: string;
  /** Timezone (defaults to UTC) */
  timezone?: string;
}

/**
 * Incoming webhook trigger configuration for plugin-generated executors
 */
export interface PluginIncomingWebhookTriggerConfig {
  kind: "incomingWebhook";
}

/**
 * Trigger configuration for plugin-generated executors
 */
export type PluginTriggerConfig =
  | PluginRecordTriggerConfig
  | PluginScheduleTriggerConfig
  | PluginIncomingWebhookTriggerConfig;

/**
 * Function operation configuration for plugin-generated executors
 */
export interface PluginFunctionOperationConfig {
  kind: "function";
  /** Function body code as string */
  body: string;
}

/**
 * GraphQL operation configuration for plugin-generated executors
 */
export interface PluginGraphQLOperationConfig {
  kind: "graphql";
  /** GraphQL query string */
  query: string;
  /** App name for the GraphQL endpoint */
  appName?: string;
}

/**
 * Webhook operation configuration for plugin-generated executors
 */
export interface PluginWebhookOperationConfig {
  kind: "webhook";
  /** Webhook URL */
  url: string;
}

/**
 * Workflow operation configuration for plugin-generated executors
 */
export interface PluginWorkflowOperationConfig {
  kind: "workflow";
  /** Workflow name */
  workflowName: string;
}

/**
 * Operation configuration for plugin-generated executors
 */
export type PluginOperationConfig =
  | PluginFunctionOperationConfig
  | PluginGraphQLOperationConfig
  | PluginWebhookOperationConfig
  | PluginWorkflowOperationConfig;

/**
 * Executor definition generated by a plugin
 */
export interface PluginGeneratedExecutor {
  name: string;
  description?: string;
  trigger: PluginTriggerConfig;
  operation: PluginOperationConfig;
}

/**
 * Extension options for modifying the source type
 */
export interface PluginExtends {
  /**
   * Fields to add to the source type.
   * These fields will be merged into the original type's fields.
   * Existing fields (from original definition or earlier plugins) take precedence.
   */
  fields?: Record<string, unknown>;
}

/**
 * Output returned by a plugin's process method
 */
export interface PluginOutput {
  /**
   * Additional TailorDB types to generate, keyed by kind identifier.
   * The kind is used to generate distinct TypeScript type files.
   * @example { request: changeRequest, step: changeStep }
   */
  types?: PluginGeneratedTypes;
  /** Additional resolvers to generate */
  resolvers?: PluginGeneratedResolver[];
  /** Additional executors to generate */
  executors?: PluginGeneratedExecutor[];
  /** Extensions to apply to the source type */
  extends?: PluginExtends;
}

/**
 * Base plugin interface that all plugins must implement
 */
export interface PluginBase {
  /** Unique identifier for the plugin */
  readonly id: string;
  /** Human-readable description of the plugin */
  readonly description: string;
  /**
   * Import path for this plugin's public API.
   * Used by code generators to create correct import statements.
   * @example "@tailor-platform/sdk/changeset-plugin"
   * @example "@my-company/audit-log-plugin"
   */
  readonly importPath: string;
  /**
   * Schema defining the expected configuration for this plugin.
   * Uses the same field types as createResolver's input (t.string(), t.number(), etc.).
   * This schema is used for runtime validation of plugin configuration.
   * @example
   * ```typescript
   * configSchema: t.object({
   *   trackedFields: t.array(t.string()),
   *   retentionDays: t.number({ optional: true }),
   * })
   * ```
   */
  readonly configSchema: TailorAnyField;

  /**
   * TypeScript type template for generating type-safe plugin configuration.
   * Use `Fields` to reference the field names of the type being configured.
   * If not provided, the type is generated from configSchema.
   * @example
   * ```typescript
   * // For field-aware configs:
   * configTypeTemplate: "{ labels: Partial<Record<Fields, FieldLabel>>; typeLabel?: FieldLabel }"
   * ```
   */
  readonly configTypeTemplate?: string;

  /**
   * Process a single TailorDB type and generate outputs.
   * This method is called for each type that has this plugin attached via .plugin().
   * @param context - Context containing the type, config, and namespace
   * @returns Plugin output with generated types, resolvers, and executors
   */
  process?(context: PluginProcessContext): PluginOutput | Promise<PluginOutput>;

  /**
   * Process standalone plugin without requiring a source type.
   * This method is called once per namespace for plugins configured via definePlugins().
   * Use this for plugins that generate types independently of user-defined types.
   * @param context - Context containing the config and target namespace
   * @returns Plugin output with generated types, resolvers, and executors
   */
  processStandalone?(context: StandalonePluginProcessContext): PluginOutput | Promise<PluginOutput>;
}

/**
 * Plugin configuration input type for definePlugins()
 * Can be:
 * - A string plugin ID (for plugins with no configuration, e.g., "@tailor-platform/changeset")
 * - A tuple [pluginId, options] for plugins with configuration
 * - A PluginBase object for custom plugins
 * Options can be any value - the plugin's configSchema handles validation.
 */
export type PluginConfig = string | readonly [string, unknown] | PluginBase;
