import type {
  TypeLoadedContext,
  TailorDBNamespaceLoadedContext,
  ResolverLoadedContext,
  ResolverNamespaceLoadedContext,
  ExecutorLoadedContext,
  PluginGenerateContext,
  GeneratorResult,
} from "./generation-types";
import type { TailorAnyDBField, TailorAnyDBType } from "@/configure/services/tailordb";

export type TypeConfigRequired<PluginConfig = unknown> =
  | boolean
  | ((pluginConfig: PluginConfig | undefined) => boolean);

/**
 * Interface for plugin configuration mapping.
 * Extend this interface via declaration merging to add typed plugin configs.
 *
 * The `Fields` type parameter provides field names from the type being configured,
 * enabling type-safe field references in plugin configs.
 * @example
 * ```typescript
 * // In your plugin package or types file:
 * declare module "@tailor-platform/sdk" {
 *   interface PluginConfigs<Fields extends string> {
 *     "@my-company/i18n": {
 *       labels: Partial<Record<Fields, { ja: string; en: string }>>;
 *     };
 *   }
 * }
 * ```
 */
// Fields parameter is used by declaration merging in user-defined.d.ts
// oxlint-disable-next-line no-unused-vars, no-empty-object-type
export interface PluginConfigs<Fields extends string = string> {
  // Extend this interface via declaration merging to add typed plugin configs
}

/**
 * Plugin attachment stored on TailorAnyDBType instances.
 * This is the configuration passed via `.plugin()` method.
 */
export interface PluginAttachment {
  pluginId: string;
  config: unknown;
}

/**
 * Context passed to plugin's process method
 */
export interface PluginProcessContext<TypeConfig = unknown, PluginConfig = unknown> {
  /** The raw TailorDB type being processed */
  type: TailorAnyDBType;
  /** Per-type configuration passed via .plugin() method */
  typeConfig: TypeConfig;
  /** Plugin-level configuration passed via definePlugins() */
  pluginConfig: PluginConfig;
  /** Namespace of the TailorDB type */
  namespace: string;
}

/**
 * Context passed to plugin's onNamespaceDefine hook.
 * Used for plugins that operate on a namespace without requiring a source type.
 */
export interface PluginNamespaceProcessContext<PluginConfig = unknown> {
  /** Plugin-level configuration passed via definePlugins() */
  pluginConfig: PluginConfig;
  /** Target namespace for generated types */
  namespace: string;
}

/**
 * Interface representing a TailorDB type for plugin output.
 * This interface is satisfied by db.type() instances.
 */
export interface TailorDBTypeForPlugin {
  /** The name of the type */
  readonly name: string;
  /** The field definitions */
  readonly fields: Record<string, unknown>;
}

/**
 * Type generated by a plugin - use db.type() to create these.
 */
export type PluginGeneratedType = TailorDBTypeForPlugin;

/**
 * Map of generated types keyed by kind identifier.
 * The kind is used to generate distinct TypeScript type files for each generated type.
 * @example
 * ```typescript
 * {
 *   request: changeRequest,
 *   step: changeStep,
 *   approval: changeApproval,
 * }
 * ```
 */
export type PluginGeneratedTypes = Record<string, PluginGeneratedType>;

/**
 * Resolver definition generated by a plugin.
 * Fields can be TailorDB field instances or raw field definitions.
 */
export interface PluginGeneratedResolver {
  name: string;
  operation: "query" | "mutation";
  inputFields?: Record<string, unknown>;
  outputFields: Record<string, unknown>;
  /** Function body code as string */
  body: string;
}

/**
 * Record trigger configuration for plugin-generated executors
 */
export interface PluginRecordTriggerConfig {
  kind: "recordCreated" | "recordUpdated" | "recordDeleted";
  /** TailorDB type name for record triggers */
  typeName: string;
}

/**
 * Schedule trigger configuration for plugin-generated executors
 */
export interface PluginScheduleTriggerConfig {
  kind: "schedule";
  /** Cron expression */
  cron: string;
  /** Timezone (defaults to UTC) */
  timezone?: string;
}

/**
 * Incoming webhook trigger configuration for plugin-generated executors
 */
export interface PluginIncomingWebhookTriggerConfig {
  kind: "incomingWebhook";
}

/**
 * Trigger configuration for plugin-generated executors
 */
export type PluginTriggerConfig =
  | PluginRecordTriggerConfig
  | PluginScheduleTriggerConfig
  | PluginIncomingWebhookTriggerConfig;

/**
 * Inject value types supported for plugin executor injection.
 * These values are serialized as const declarations in the generated file.
 */
export type PluginInjectValue = string | number | boolean | null;

/**
 * Inject map for plugin executor.
 * Keys become const variable names in the generated file.
 */
export type PluginInjectMap = Record<string, PluginInjectValue>;

/**
 * Function operation configuration for plugin-generated executors
 */
export interface PluginFunctionOperationConfig {
  kind: "function";
  /** Function body code as string */
  body: string;
  /**
   * Variables to inject into the generated file scope.
   * These become const declarations at the top of the generated file,
   * allowing the function body to reference them.
   * @example { namespace: "tailordb", historyTypeName: "CustomerHistory" }
   */
  inject?: PluginInjectMap;
}

/**
 * GraphQL operation configuration for plugin-generated executors
 */
export interface PluginGraphQLOperationConfig {
  kind: "graphql";
  /** GraphQL query string */
  query: string;
  /** App name for the GraphQL endpoint */
  appName?: string;
  /**
   * Variables expression as a string function.
   * Receives the executor args object and returns the variables object.
   * @example "(args) => ({ input: { recordId: args.newRecord.id } })"
   */
  variables?: string;
}

/**
 * Webhook operation configuration for plugin-generated executors
 */
export interface PluginWebhookOperationConfig {
  kind: "webhook";
  /** Webhook URL */
  url: string;
}

/**
 * Workflow operation configuration for plugin-generated executors
 */
export interface PluginWorkflowOperationConfig {
  kind: "workflow";
  /** Workflow name */
  workflowName: string;
}

/**
 * Operation configuration for plugin-generated executors
 */
export type PluginOperationConfig =
  | PluginFunctionOperationConfig
  | PluginGraphQLOperationConfig
  | PluginWebhookOperationConfig
  | PluginWorkflowOperationConfig;

/**
 * Context value types for plugin executor context.
 * Supports primitive values and type references.
 */
export type PluginExecutorContextValue =
  | TailorAnyDBType
  | string
  | number
  | boolean
  | null
  | undefined;

/**
 * Base executor context that can include type references and other values.
 * Type objects (TailorAnyDBType) will be handled specially by the generator
 * to create appropriate import statements.
 *
 * Plugin authors should extend this interface for their specific context needs.
 */
export interface PluginExecutorContextBase {
  /** Source type that the plugin is attached to. Null for namespace executors. */
  sourceType: TailorAnyDBType | null;
  /** TailorDB namespace for data operations */
  namespace: string;
}

/**
 * Flexible executor context type that allows additional properties.
 * Used as the context type in PluginGeneratedExecutorWithFile.
 */
export type PluginExecutorContext = PluginExecutorContextBase & {
  [key: string]: PluginExecutorContextValue;
};

/**
 * Module shape returned by plugin executor resolve().
 * The concrete context type is intentionally erased at this boundary.
 */
export interface PluginExecutorModule {
  default: unknown;
}

/**
 * Executor definition with dynamic import reference (new format).
 * Used with withPluginContext for type-safe executor definitions in separate files.
 */
export interface PluginGeneratedExecutorWithFile<Ctx = PluginExecutorContext> {
  /** Executor name (used for generated file name) */
  name: string;
  /**
   * Resolver function for the executor module.
   * Should return a dynamic import to the executor file.
   * Relative import specifiers are resolved from the plugin's importPath base.
   * @example `async () => await import("./executors/on-create")`
   */
  resolve: () => Promise<PluginExecutorModule>;
  /**
   * Context to pass to the executor factory.
   * Can include TailorAnyDBType objects - these will be handled specially
   * by the generator to create appropriate import statements.
   */
  context: Ctx;
}

/**
 * Executor definition generated by a plugin (legacy format).
 * @deprecated Use PluginGeneratedExecutorWithFile with withPluginContext instead.
 */
export interface PluginGeneratedExecutorLegacy {
  name: string;
  description?: string;
  trigger: PluginTriggerConfig;
  operation: PluginOperationConfig;
}

/**
 * Executor definition generated by a plugin.
 * Supports both legacy format (inline trigger/operation) and new format (executorFile/context).
 */
export type PluginGeneratedExecutor =
  | PluginGeneratedExecutorWithFile
  | PluginGeneratedExecutorLegacy;

/**
 * Type guard to check if executor uses the new dynamic import format.
 * @param executor - Executor definition to check
 * @returns True if executor uses dynamic import format
 */
export function isPluginExecutorWithFile(
  executor: PluginGeneratedExecutor,
): executor is PluginGeneratedExecutorWithFile {
  return "resolve" in executor && "context" in executor;
}

/**
 * Extension options for modifying the source type
 */
export interface PluginExtends {
  /**
   * Fields to add to the source type.
   * These fields will be merged into the original type's fields.
   * Existing fields (from original definition or earlier plugins) take precedence.
   */
  fields?: Record<string, TailorAnyDBField>;
}

/**
 * Base output returned by a plugin's definition-time hooks.
 * Used by both onTypeDefine and onNamespaceDefine.
 */
export interface PluginOutput {
  /**
   * Additional TailorDB types to generate, keyed by kind identifier.
   * The kind is used to generate distinct TypeScript type files.
   * @example { request: changeRequest, step: changeStep }
   */
  types?: PluginGeneratedTypes;
  /** Additional resolvers to generate */
  resolvers?: PluginGeneratedResolver[];
  /** Additional executors to generate */
  executors?: PluginGeneratedExecutor[];
}

/**
 * Output returned by a plugin's onTypeDefine hook.
 * Extends PluginOutput with the ability to add fields to the source type.
 */
export interface TypePluginOutput extends PluginOutput {
  /** Extensions to apply to the source type */
  extends?: PluginExtends;
}

/**
 * Output returned by a plugin's onNamespaceDefine hook.
 * Alias for PluginOutput (namespace plugins cannot extend a source type).
 */
export type NamespacePluginOutput = PluginOutput;

/**
 * Plugin interface that all plugins must implement.
 * Plugins can hook into two lifecycle phases:
 * - **Definition-time hooks** (`onTypeDefine`, `onNamespaceDefine`): Generate TailorDB types, resolvers, and executors
 * - **Generation-time hooks** (`onTypeLoaded`, `onResolverLoaded`, etc.): Process loaded artifacts and produce output files
 * @template TypeConfig - Type for per-type configuration passed via .plugin() method
 * @template PluginConfig - Type for plugin-level configuration passed via definePlugins()
 */
export interface Plugin<TypeConfig = unknown, PluginConfig = unknown> {
  /** Unique identifier for the plugin */
  readonly id: string;
  /** Human-readable description of the plugin */
  readonly description: string;
  /**
   * Import path for this plugin's public API.
   * Used by code generators to create correct import statements
   * (e.g., plugin executors and seed schema generation).
   * Required when plugin has definition-time hooks (onTypeDefine/onNamespaceDefine).
   * Optional for generation-only plugins.
   */
  readonly importPath?: string;

  /**
   * Controls whether per-type plugin config is required when attaching via .plugin().
   * If a function is provided, it receives pluginConfig from definePlugins().
   * Default is optional when not provided.
   */
  readonly typeConfigRequired?: TypeConfigRequired<PluginConfig>;

  /**
   * Plugin-level configuration passed via definePlugins().
   * This config is stored when the plugin is registered and made available
   * to all hook methods.
   */
  readonly pluginConfig?: PluginConfig;

  // =========================================================================
  // Definition-time hooks (produce TailorDB types, resolvers, executors)
  // =========================================================================

  /**
   * Process a single TailorDB type and generate outputs.
   * Called for each type that has this plugin attached via .plugin().
   * @param context - Context containing the type, config, pluginConfig, and namespace
   * @returns Plugin output with generated types, resolvers, and executors
   */
  onTypeDefine?(
    context: PluginProcessContext<TypeConfig, PluginConfig>,
  ): TypePluginOutput | Promise<TypePluginOutput>;

  /**
   * Process plugin for a namespace without requiring a source type.
   * Called once per namespace for plugins configured via definePlugins().
   * Use this for plugins that generate types independently of user-defined types.
   * @param context - Context containing the plugin config and namespace
   * @returns Plugin output with generated types, resolvers, and executors
   */
  onNamespaceDefine?(
    context: PluginNamespaceProcessContext<PluginConfig>,
  ): NamespacePluginOutput | Promise<NamespacePluginOutput>;

  // =========================================================================
  // Generation-time hooks (process loaded artifacts, produce output files)
  // =========================================================================

  /**
   * Process a single loaded TailorDB type.
   * Called for each TailorDB type after all types are loaded and parsed.
   * @param context - Context containing the parsed type, namespace, source info, and plugins
   * @returns Metadata to be aggregated per namespace
   */
  onTypeLoaded?(context: TypeLoadedContext<PluginConfig>): unknown | Promise<unknown>;

  /**
   * Aggregate type processing results per namespace.
   * Called once per namespace after all types are processed by onTypeLoaded.
   * @param context - Context containing the namespace and accumulated type results
   * @returns Aggregated namespace result
   */
  onTailorDBNamespaceLoaded?(
    context: TailorDBNamespaceLoadedContext<PluginConfig>,
  ): unknown | Promise<unknown>;

  /**
   * Process a single loaded resolver.
   * Called for each resolver after all resolvers are loaded.
   * @param context - Context containing the resolver and namespace
   * @returns Metadata to be aggregated per namespace
   */
  onResolverLoaded?(context: ResolverLoadedContext<PluginConfig>): unknown | Promise<unknown>;

  /**
   * Aggregate resolver processing results per namespace.
   * Called once per namespace after all resolvers are processed by onResolverLoaded.
   * @param context - Context containing the namespace and accumulated resolver results
   * @returns Aggregated namespace result
   */
  onResolverNamespaceLoaded?(
    context: ResolverNamespaceLoadedContext<PluginConfig>,
  ): unknown | Promise<unknown>;

  /**
   * Process a single loaded executor.
   * Called for each executor after all executors are loaded.
   * @param context - Context containing the executor
   * @returns Metadata for executor processing
   */
  onExecutorLoaded?(context: ExecutorLoadedContext<PluginConfig>): unknown | Promise<unknown>;

  /**
   * Final generation hook that produces output files.
   * Called after all generation-time hooks complete.
   * If not provided, the plugin produces no generated files.
   * @param context - Context containing all accumulated results, auth info, and output paths
   * @returns Generated files and optional errors
   */
  generate?(
    context: PluginGenerateContext<PluginConfig>,
  ): GeneratorResult | Promise<GeneratorResult>;
}
