import type { ParsedTailorDBType } from "@/parser/service/tailordb/types";

/**
 * Plugin attachment stored on TailorDBType instances.
 * This is the configuration passed via `.plugin()` method.
 */
export interface PluginAttachment {
  pluginId: string;
  config: unknown;
}

/**
 * Context passed to plugin's process method
 */
export interface PluginProcessContext {
  /** The parsed TailorDB type being processed */
  type: ParsedTailorDBType;
  /** Plugin-specific configuration passed via .plugin() method */
  config: unknown;
  /** Namespace of the TailorDB type */
  namespace: string;
}

/**
 * Field definition for plugin-generated types
 */
export interface PluginFieldDefinition {
  type:
    | "uuid"
    | "string"
    | "boolean"
    | "integer"
    | "float"
    | "date"
    | "datetime"
    | "time"
    | "enum"
    | "nested";
  required?: boolean;
  description?: string;
  array?: boolean;
  index?: boolean;
  unique?: boolean;
  allowedValues?: Array<{ value: string; description?: string }>;
  relation?: {
    type: "n-1" | "1-1" | "1-n";
    targetType: string;
    targetField?: string;
  };
  fields?: Record<string, PluginFieldDefinition>;
}

/**
 * Type definition generated by a plugin
 */
export interface PluginGeneratedType {
  name: string;
  fields: Record<string, PluginFieldDefinition>;
  description?: string;
  settings?: {
    pluralForm?: string;
    aggregation?: boolean;
    bulkUpsert?: boolean;
  };
}

/**
 * Resolver definition generated by a plugin
 */
export interface PluginGeneratedResolver {
  name: string;
  operation: "query" | "mutation";
  inputFields?: Record<string, PluginFieldDefinition>;
  outputFields: Record<string, PluginFieldDefinition>;
  /** Function body code as string */
  body: string;
}

/**
 * Trigger configuration for plugin-generated executors
 */
export interface PluginTriggerConfig {
  kind: "recordCreated" | "recordUpdated" | "recordDeleted" | "schedule" | "webhook";
  /** TailorDB type name for record triggers */
  type?: string;
  /** Cron expression for schedule trigger */
  schedule?: string;
}

/**
 * Operation configuration for plugin-generated executors
 */
export interface PluginOperationConfig {
  kind: "function" | "webhook" | "graphql" | "workflow";
  /** Function body code for function operations */
  body?: string;
  /** URL for webhook operations */
  url?: string;
  /** GraphQL query for graphql operations */
  query?: string;
}

/**
 * Executor definition generated by a plugin
 */
export interface PluginGeneratedExecutor {
  name: string;
  description?: string;
  trigger: PluginTriggerConfig;
  operation: PluginOperationConfig;
}

/**
 * Output returned by a plugin's process method
 */
export interface PluginOutput {
  /** Additional TailorDB types to generate */
  types?: PluginGeneratedType[];
  /** Additional resolvers to generate */
  resolvers?: PluginGeneratedResolver[];
  /** Additional executors to generate */
  executors?: PluginGeneratedExecutor[];
}

/**
 * Base plugin interface that all plugins must implement
 */
export interface PluginBase {
  /** Unique identifier for the plugin */
  readonly id: string;
  /** Human-readable description of the plugin */
  readonly description: string;

  /**
   * Process a single TailorDB type and generate outputs
   * @param context - Context containing the type, config, and namespace
   * @returns Plugin output with generated types, resolvers, and executors
   */
  process(context: PluginProcessContext): PluginOutput | Promise<PluginOutput>;
}

/**
 * Plugin configuration input type for definePlugins()
 * Can be either a tuple [pluginId, options] for built-in plugins
 * or a PluginBase object for custom plugins
 */
export type PluginConfig = readonly [string, Record<string, unknown>] | PluginBase;
