/**
 * Generate .d.ts content with declare module augmentation for GeneratedGqlSchema.
 */

import type { GqlSchemaTypeMetadata } from "./types";

/**
 * Generate the content of a .d.ts file that augments GeneratedGqlSchema.
 * @param allTypes - All processed type metadata entries across all namespaces
 * @returns The file content string
 */
export function generateGqlSchemaDts(allTypes: GqlSchemaTypeMetadata[]): string {
  const allEntries = allTypes.flatMap((t) => t.entries);
  if (allEntries.length === 0) return "";

  const lines: string[] = [
    "// Auto-generated by @tailor-platform/graphql-schema",
    "// Do not edit this file manually.",
    "",
    'import type { InferCreateInput, InferUpdateInput, InferGqlResult } from "@tailor-platform/sdk/graphql";',
    "",
    'declare module "@tailor-platform/sdk/graphql" {',
    "  interface GeneratedGqlSchema {",
  ];

  for (const entry of allEntries) {
    lines.push(`    ${entry.operationName}: {`);
    lines.push(`      variables: ${entry.variablesExpr};`);
    lines.push(`      result: ${entry.resultExpr};`);
    lines.push("    };");
  }

  lines.push("  }");
  lines.push("}");
  lines.push("");

  return lines.join("\n");
}
