import * as fs from "node:fs";
import ml from "multiline-ts";
import * as path from "pathe";
import { logger, styles } from "@/cli/utils/logger";
import type {
  PluginGeneratedExecutor,
  PluginTriggerConfig,
  PluginOperationConfig,
  PluginInjectMap,
} from "@/parser/plugin-config/types";
import type { PluginExecutorInfo } from "@/plugin/manager";

/**
 * Generate TypeScript files for plugin-generated executors.
 * These files will be processed by the standard executor bundler.
 * @param executors - Array of plugin executor information
 * @param outputDir - Directory to output the generated files
 * @returns Array of generated file paths
 */
export function generatePluginExecutorFiles(
  executors: ReadonlyArray<PluginExecutorInfo>,
  outputDir: string,
): string[] {
  if (executors.length === 0) {
    return [];
  }

  fs.mkdirSync(outputDir, { recursive: true });

  const generatedFiles: string[] = [];

  for (const info of executors) {
    const content = generateExecutorFileContent(info.executor);
    const filePath = path.join(outputDir, `${info.executor.name}.ts`);
    fs.writeFileSync(filePath, content);
    generatedFiles.push(filePath);

    const relativePath = path.relative(process.cwd(), filePath);
    logger.log(
      `  Plugin Executor File: ${styles.success(relativePath)} from plugin ${styles.info(info.pluginId)}`,
    );
  }

  return generatedFiles;
}

/**
 * Generate const declarations for injected variables.
 * @param inject - Map of variable names to values
 * @returns TypeScript const declarations
 */
function generateInjectDeclarations(inject: PluginInjectMap | undefined): string {
  if (!inject || Object.keys(inject).length === 0) {
    return "";
  }

  const declarations = Object.entries(inject)
    .map(([name, value]) => `const ${name} = ${JSON.stringify(value)};`)
    .join("\n");

  return `\n// Injected variables from plugin\n${declarations}\n`;
}

/**
 * Generate TypeScript file content for a single executor.
 * @param executor - The plugin-generated executor definition
 * @returns TypeScript source code
 */
function generateExecutorFileContent(executor: PluginGeneratedExecutor): string {
  const triggerCode = generateTriggerCode(executor.trigger);
  const operationCode = generateOperationCode(executor.operation);

  // Extract inject from function operation
  const inject = executor.operation.kind === "function" ? executor.operation.inject : undefined;
  const injectDeclarations = generateInjectDeclarations(inject);

  const descriptionLine = executor.description
    ? `\n  description: ${JSON.stringify(executor.description)},`
    : "";

  return ml /* ts */ `
    /**
     * Auto-generated executor by plugin
     * DO NOT EDIT - This file is generated by @tailor-platform/sdk
     */
    import { createExecutor } from "@tailor-platform/sdk";
    ${injectDeclarations}
    export default createExecutor({
      name: ${JSON.stringify(executor.name)},${descriptionLine}
      trigger: ${triggerCode},
      operation: ${operationCode},
    });
  `;
}

/**
 * Generate TypeScript code for trigger configuration.
 * @param trigger - Trigger configuration
 * @returns TypeScript code string
 */
function generateTriggerCode(trigger: PluginTriggerConfig): string {
  switch (trigger.kind) {
    case "recordCreated":
    case "recordUpdated":
    case "recordDeleted":
      return `{
    kind: ${JSON.stringify(trigger.kind)},
    typeName: ${JSON.stringify(trigger.typeName)},
  }`;

    case "schedule":
      return `{
    kind: "schedule",
    cron: ${JSON.stringify(trigger.cron)},
    timezone: ${JSON.stringify(trigger.timezone ?? "UTC")},
  }`;

    case "incomingWebhook":
      return `{
    kind: "incomingWebhook",
  }`;

    default:
      throw new Error(`Unknown trigger kind: ${(trigger as PluginTriggerConfig).kind}`);
  }
}

/**
 * Generate TypeScript code for operation configuration.
 * @param operation - Operation configuration
 * @returns TypeScript code string
 */
function generateOperationCode(operation: PluginOperationConfig): string {
  switch (operation.kind) {
    case "graphql": {
      const appNameLine = operation.appName
        ? `\n    appName: ${JSON.stringify(operation.appName)},`
        : "";
      const variablesLine = operation.variables ? `\n    variables: ${operation.variables},` : "";

      return `{
    kind: "graphql",
    query: \`${escapeTemplateLiteral(operation.query)}\`,${appNameLine}${variablesLine}
  }`;
    }

    case "function":
      return `{
    kind: "function",
    body: ${operation.body},
  }`;

    case "webhook":
      return `{
    kind: "webhook",
    url: () => ${JSON.stringify(operation.url)},
  }`;

    case "workflow":
      return `{
    kind: "workflow",
    workflowName: ${JSON.stringify(operation.workflowName)},
  }`;

    default:
      throw new Error(`Unknown operation kind: ${(operation as PluginOperationConfig).kind}`);
  }
}

/**
 * Escape special characters in template literal content.
 * @param str - String to escape
 * @returns Escaped string safe for use in template literals
 */
function escapeTemplateLiteral(str: string): string {
  return str.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}
