/**
 * Scaffolding helpers for the `tailor function script` command.
 *
 * A scaffolded one-off script is a plain default-exported function that
 * `tailor function run` executes on the platform without deploying. When the
 * project does not configure `kyselyTypePlugin`, the scaffold also writes a
 * script-scoped `db.ts` generated from the deployed schema, plus a
 * `db.snapshot.json` snapshot that `function run` checks for schema drift.
 */

import * as fs from "node:fs";
import * as path from "pathe";
import { hasChanges, formatMigrationDiff } from "#/cli/commands/tailordb/migrate/diff-calculator";
import { fetchRemoteSchemaSnapshot } from "#/cli/commands/tailordb/migrate/schema-checks";
import {
  compareLocalTypesWithSnapshot,
  createSnapshotType,
  normalizeSchemaSnapshot,
  type NormalizedSchemaSnapshot,
  type SchemaSnapshot,
  type TailorDBSnapshotType,
} from "#/cli/commands/tailordb/migrate/snapshot";
import { DEFAULT_CONFIG_PATH } from "#/cli/shared/args";
import { extractOwnedNamespaces } from "#/cli/shared/config";
import { formatCopyableCommand } from "#/cli/shared/errors";
import { loadTailorDBNamespaces } from "#/cli/shared/tailordb-namespaces";
import {
  generateUnifiedKyselyTypes,
  processKyselyFields,
} from "#/plugin/builtin/kysely-type/type-processor";
import type { OperatorClient } from "#/cli/shared/client";
import type { LoadedConfig } from "#/cli/shared/config-loader";

/** File name of the script-scoped Kysely types written next to a scaffolded script. */
export const SCRIPT_DB_TYPES_FILE_NAME = "db.ts";
/** File name of the schema snapshot written next to a scaffolded script. */
export const SCRIPT_SNAPSHOT_FILE_NAME = "db.snapshot.json";

const GENERATED_DB_TYPES_HEADER = [
  "/**",
  " * Auto-generated Kysely types for one-off scripts in this directory.",
  " * Generated by `tailor function script` from the deployed schema.",
  " *",
  " * DO NOT EDIT - Re-run `tailor function script` to refresh.",
  " */",
].join("\n");

/**
 * Generate the script-scoped `db.ts` contents from a schema snapshot.
 * @param snapshot - Schema snapshot of the target namespace
 * @returns Generated `db.ts` file contents
 */
export function generateScriptDbTypes(snapshot: SchemaSnapshot): string {
  const types = Object.values(snapshot.tables).map((table) =>
    processKyselyFields(table.name, table.fields),
  );
  const usedUtilityTypes = types.reduce(
    (acc, type) => ({
      Timestamp: acc.Timestamp || type.usedUtilityTypes.Timestamp,
      Serial: acc.Serial || type.usedUtilityTypes.Serial,
    }),
    { Timestamp: false, Serial: false },
  );
  const body = generateUnifiedKyselyTypes([
    { namespace: snapshot.namespace, types, usedUtilityTypes },
  ]);
  return `${GENERATED_DB_TYPES_HEADER}\n\n${body}`;
}

/**
 * Whether an existing file at the script-scoped `db.ts` path was written by
 * the scaffold (and is therefore safe to overwrite).
 * @param content - Existing file contents
 * @returns true when the scaffold header is present
 */
export function isGeneratedScriptDbTypes(content: string): boolean {
  return content.includes("Generated by `tailor function script`");
}

/** Options for {@link generateScriptSkeleton}. */
export interface ScriptSkeletonOptions {
  /** Module specifier the skeleton imports `getDB` from */
  getDBImportPath: string;
  /** TailorDB namespace passed to `getDB()` */
  namespace: string;
}

/**
 * Generate the one-off script skeleton.
 * @param options - Skeleton options
 * @returns Skeleton file contents
 */
export function generateScriptSkeleton(options: ScriptSkeletonOptions): string {
  const { getDBImportPath, namespace } = options;
  return [
    "/**",
    " * One-off script. Run it on the platform without deploying:",
    " *",
    " *   tailor function run <this file>",
    " *",
    " * For large tables, batch updates by primary-key range instead of one",
    ' * statement over the whole table; see the "Performance and Large Tables"',
    " * section in @tailor-platform/sdk's docs/services/tailordb-migration.md.",
    " */",
    "",
    `import { getDB } from "${getDBImportPath}";`,
    "",
    "export default async function main() {",
    `  const db = getDB("${namespace}");`,
    "",
    "  // A transaction rolls every change back when any statement fails.",
    "  await db.transaction().execute(async (trx) => {",
    '    // e.g. await trx.updateTable("MyTable").set({ ... }).where("id", "=", "...").execute();',
    "  });",
    "}",
    "",
  ].join("\n");
}

/** A schema snapshot sidecar found next to a script. */
export interface ScriptSchemaSnapshotSidecar {
  /** Path of the snapshot file */
  snapshotPath: string;
  /** The stored snapshot, normalized */
  snapshot: NormalizedSchemaSnapshot;
}

/**
 * Load the schema snapshot written next to a scaffolded script, if present.
 * @param scriptPath - Absolute path of the script passed to `function run`
 * @returns The snapshot sidecar, or null when the script has none
 */
export function loadScriptSchemaSnapshot(scriptPath: string): ScriptSchemaSnapshotSidecar | null {
  const snapshotPath = path.join(path.dirname(scriptPath), SCRIPT_SNAPSHOT_FILE_NAME);
  if (!fs.existsSync(snapshotPath)) {
    return null;
  }

  let parsed: unknown;
  try {
    parsed = JSON.parse(fs.readFileSync(snapshotPath, "utf-8"));
  } catch (error) {
    throw new Error(
      `Failed to parse schema snapshot ${snapshotPath}: ${error instanceof Error ? error.message : error}. ` +
        "Re-run `tailor function script` to regenerate it.",
      { cause: error },
    );
  }
  const candidate = parsed as Record<string, unknown> | null;
  if (
    typeof candidate !== "object" ||
    candidate === null ||
    typeof candidate.namespace !== "string" ||
    typeof candidate.tables !== "object" ||
    candidate.tables === null
  ) {
    throw new Error(
      `Schema snapshot ${snapshotPath} has an unexpected shape. ` +
        "Re-run `tailor function script` to regenerate it.",
    );
  }

  return {
    snapshotPath,
    snapshot: normalizeSchemaSnapshot(parsed as SchemaSnapshot),
  };
}

/** Options for {@link verifyScriptSchemaSnapshot}. */
export interface VerifyScriptSchemaSnapshotOptions {
  /** Operator client */
  client: OperatorClient;
  /** Workspace ID */
  workspaceId: string;
  /** Loaded config */
  config: LoadedConfig;
  /** Config path as passed on the command line (threaded into hints) */
  configArgValue: string;
  /** Script path as passed on the command line (threaded into hints) */
  scriptArgValue: string;
  /** The snapshot sidecar found next to the script */
  sidecar: ScriptSchemaSnapshotSidecar;
}

/**
 * Verify a scaffolded script's schema snapshot still matches the local table
 * definitions (when the config owns the namespace) and the deployed schema.
 * @param options - Verification inputs
 * @throws When either comparison detects drift
 */
export async function verifyScriptSchemaSnapshot(
  options: VerifyScriptSchemaSnapshotOptions,
): Promise<void> {
  const { client, workspaceId, config, configArgValue, sidecar } = options;
  const { snapshot } = sidecar;
  const namespace = snapshot.namespace;

  if (extractOwnedNamespaces(config).includes(namespace)) {
    const { namespaces } = await loadTailorDBNamespaces({
      configPath: configArgValue,
      namespaces: [namespace],
    });
    const namespaceData = namespaces[0];
    if (namespaceData) {
      const localTables: Record<string, TailorDBSnapshotType> = Object.fromEntries(
        Object.values(namespaceData.types).map((type) => [type.name, createSnapshotType(type)]),
      );
      const diff = compareLocalTypesWithSnapshot(snapshot, localTables, namespace);
      if (hasChanges(diff)) {
        throw schemaDriftError("the local table definitions", diff, options);
      }
    }
  }

  const remoteSnapshot = await fetchRemoteSchemaSnapshot(client, workspaceId, namespace);
  const remoteDiff = compareLocalTypesWithSnapshot(snapshot, remoteSnapshot.tables, namespace);
  if (hasChanges(remoteDiff)) {
    throw schemaDriftError("the deployed schema", remoteDiff, options);
  }
}

function schemaDriftError(
  target: string,
  diff: ReturnType<typeof compareLocalTypesWithSnapshot>,
  options: VerifyScriptSchemaSnapshotOptions,
): Error {
  const configFlags =
    options.configArgValue !== DEFAULT_CONFIG_PATH ? [`--config=${options.configArgValue}`] : [];
  const rescaffold = formatCopyableCommand([
    "tailor",
    "function",
    "script",
    options.scriptArgValue,
    ...configFlags,
  ]);
  const override = formatCopyableCommand([
    "tailor",
    "function",
    "run",
    options.scriptArgValue,
    "--allow-schema-drift",
    ...configFlags,
  ]);
  return new Error(
    `Schema drift detected: ${SCRIPT_SNAPSHOT_FILE_NAME} next to the script no longer matches ${target}.\n\n` +
      `${formatMigrationDiff(diff)}\n\n` +
      `Refresh the generated types with ${rescaffold}, or run anyway with ${override}.`,
  );
}
