// This file is auto-generated by @tailor-platform/sdk
// Do not edit this file manually
// Regenerated automatically when running 'tailor-sdk apply' or 'tailor-sdk generate'

declare module "@tailor-platform/sdk" {
  interface AttributeMap {
    role: "MANAGER" | "STAFF";
  }
  interface AttributeList {
    __tuple?: [];
  }
  interface Env {}
  interface MachineUserNameRegistry {
    manager: true;
    staff: true;
  }
  interface IdpNameRegistry {}
}

export {};
