locale: en
repository: ${GITHUB_REPOSITORY}/examples/basic

# Disable coverage metrics
coverage:
  if: false

codeToTestRatio:
  if: false

testExecutionTime:
  if: false

report:
  if: is_default_branch
  datastores:
    - artifact://${GITHUB_REPOSITORY}

diff:
  datastores:
    - artifact://${GITHUB_REPOSITORY}

comment:
  if: is_pull_request

summary:
  if: true

customMetrics:
  1-diagnostics-full:
    key: 1-diagnostics-full
  2-diagnostics-types:
    key: 2-diagnostics-types
  3-diagnostics-resolvers:
    key: 3-diagnostics-resolvers
  4-diagnostics-executors:
    key: 4-diagnostics-executors
