import type { PluginGeneratedTypeSource, TypeSourceInfoEntry } from "./types";

/**
 * Checks if a type source is generated by a plugin.
 * @param source - The type source entry to check.
 * @returns True if the source was generated by a plugin.
 */
export function isPluginGeneratedType(
  source: TypeSourceInfoEntry,
): source is PluginGeneratedTypeSource {
  return source.pluginId !== undefined;
}
