// Generated by zinfer - Do not edit manually

export type AppConfigParsed = {
  name: string;
  id?: string | undefined;
  env?:
    | {
        [x: string]: string | number | boolean;
      }
    | undefined;
  cors?: string[] | undefined;
  allowedIpAddresses?: string[] | undefined;
  disableIntrospection?: boolean | undefined;
  inlineSourcemap?: boolean | undefined;
  logLevel?: string | undefined;
  db?: unknown;
  resolver?: unknown;
  idp?: unknown;
  auth?: unknown;
  executor?: unknown;
  workflow?: unknown;
  httpAdapter?: unknown;
  staticWebsites?: unknown;
  secrets?: unknown;
};
export type AppConfigParsedInput = AppConfigParsed;
