// Generated by zinfer - Do not edit manually

export type AuthInvokerObject = {
  /** Auth namespace */
  namespace: string;
  /** Machine user name for authentication */
  machineUserName: string;
};
export type AuthInvokerObjectInput = AuthInvokerObject;

export type AuthInvoker = AuthInvokerObject;
export type AuthInvokerInput = AuthInvoker;

export type OIDC = {
  /** Identity provider name */
  name: string;
  kind: "OIDC";
  /** OAuth2 client ID */
  clientID: string;
  /** OAuth2 client secret */
  clientSecret: {
    /** Vault name containing the secret */
    vaultName: string;
    /** Key of the secret in the vault */
    secretKey: string;
  };
  /** OIDC provider URL */
  providerURL: string;
  /** OIDC issuer URL (defaults to providerURL) */
  issuerURL?: string | undefined;
  /** JWT claim to use as username */
  usernameClaim?: string | undefined;
};
export type OIDCInput = OIDC;

export type SAMLInput = {
  /** Identity provider name */
  name: string;
  kind: "SAML";
  /** Enable signing of SAML requests */
  enableSignRequest?: boolean | undefined;
  /** URL to fetch SAML metadata (mutually exclusive with rawMetadata) */
  metadataURL?: string | undefined;
  /** Raw SAML metadata XML (mutually exclusive with metadataURL) */
  rawMetadata?: string | undefined;
  /** URL to redirect to when SAML ACS receives a response with an empty RelayState. */
  defaultRedirectURL?: string | undefined;
};

export type SAML = {
  /** Identity provider name */
  name: string;
  kind: "SAML";
  /** Enable signing of SAML requests */
  enableSignRequest: boolean;
  /** URL to fetch SAML metadata (mutually exclusive with rawMetadata) */
  metadataURL?: string | undefined;
  /** Raw SAML metadata XML (mutually exclusive with metadataURL) */
  rawMetadata?: string | undefined;
  /** URL to redirect to when SAML ACS receives a response with an empty RelayState. */
  defaultRedirectURL?: string | undefined;
};

export type IDToken = {
  /** Identity provider name */
  name: string;
  kind: "IDToken";
  /** ID token provider URL */
  providerURL: string;
  /** Client ID for ID token validation */
  clientID: string;
  /** ID token issuer URL */
  issuerURL?: string | undefined;
  /** JWT claim to use as username */
  usernameClaim?: string | undefined;
};
export type IDTokenInput = IDToken;

export type BuiltinIdP = {
  /** Identity provider name */
  name: string;
  kind: "BuiltInIdP";
  /** IdP namespace */
  namespace: string;
  /** OAuth2 client name in the IdP */
  clientName: string;
};
export type BuiltinIdPInput = BuiltinIdP;

export type IdProviderInput = OIDC | SAMLInput | IDToken | BuiltinIdP;

export type IdProvider = OIDC | SAML | IDToken | BuiltinIdP;

/**
 * OAuth2 grant type
 */
export type OAuth2ClientGrantType = "authorization_code" | "refresh_token";
export type OAuth2ClientGrantTypeInput = OAuth2ClientGrantType;

export type OAuth2ClientInput = {
  /** Allowed redirect URIs */
  redirectURIs: (
    | `https://${string}`
    | `http://${string}`
    | `${string}:url`
    | `${string}:url/${string}`
  )[];
  /** Client description */
  description?: string | undefined;
  /** Allowed OAuth2 grant types */
  grantTypes?: ("authorization_code" | "refresh_token")[] | undefined;
  /** OAuth2 client type */
  clientType?: "confidential" | "public" | "browser" | undefined;
  /** Access token lifetime in seconds (60-86400) */
  accessTokenLifetimeSeconds?: number | undefined;
  /** Refresh token lifetime in seconds (60-604800) */
  refreshTokenLifetimeSeconds?: number | undefined;
  /** Require DPoP (Demonstrating Proof-of-Possession) for token requests */
  requireDpop?: boolean | undefined;
};

export type OAuth2Client = {
  /** Allowed OAuth2 grant types */
  grantTypes: ("authorization_code" | "refresh_token")[];
  /** Allowed redirect URIs */
  redirectURIs: (
    | `https://${string}`
    | `http://${string}`
    | `${string}:url`
    | `${string}:url/${string}`
  )[];
  /** Access token lifetime in seconds (60-86400) */
  accessTokenLifetimeSeconds:
    | {
        seconds: bigint;
        nanos: number;
      }
    | undefined;
  /** Refresh token lifetime in seconds (60-604800) */
  refreshTokenLifetimeSeconds:
    | {
        seconds: bigint;
        nanos: number;
      }
    | undefined;
  /** Client description */
  description?: string | undefined;
  /** OAuth2 client type */
  clientType?: "confidential" | "public" | "browser" | undefined;
  /** Require DPoP (Demonstrating Proof-of-Possession) for token requests */
  requireDpop?: boolean | undefined;
};

export type SCIMAuthorization = {
  /** SCIM authorization type */
  type: "oauth2" | "bearer";
  /** Bearer token secret (required for bearer type) */
  bearerSecret?:
    | {
        /** Vault name containing the secret */
        vaultName: string;
        /** Key of the secret in the vault */
        secretKey: string;
      }
    | undefined;
};
export type SCIMAuthorizationInput = SCIMAuthorization;

/**
 * SCIM attribute data type
 */
export type SCIMAttributeType = "string" | "number" | "boolean" | "datetime" | "complex";
export type SCIMAttributeTypeInput = SCIMAttributeType;

export type SCIMAttributeInput = {
  /** Attribute data type */
  type: SCIMAttributeType;
  /** Attribute name */
  name: string;
  /** Attribute description */
  description?: string | undefined;
  /** Attribute mutability */
  mutability?: "readOnly" | "readWrite" | "writeOnly" | undefined;
  /** Whether the attribute is required */
  required?: boolean | undefined;
  /** Whether the attribute can have multiple values */
  multiValued?: boolean | undefined;
  /** Uniqueness constraint */
  uniqueness?: "none" | "server" | "global" | undefined;
  /** List of canonical values */
  canonicalValues?: string[] | null | undefined;
  subAttributes?: SCIMAttributeInput[] | null | undefined;
};

export type SCIMAttribute = {
  /** Attribute data type */
  type: SCIMAttributeType;
  /** Attribute name */
  name: string;
  /** Attribute description */
  description?: string | undefined;
  /** Attribute mutability */
  mutability?: "readOnly" | "readWrite" | "writeOnly" | undefined;
  /** Whether the attribute is required */
  required?: boolean | undefined;
  /** Whether the attribute can have multiple values */
  multiValued?: boolean | undefined;
  /** Uniqueness constraint */
  uniqueness?: "none" | "server" | "global" | undefined;
  /** List of canonical values */
  canonicalValues?: string[] | null | undefined;
  subAttributes?: SCIMAttribute[] | null | undefined;
};

export type SCIMAttributeMapping = {
  /** TailorDB field name to map to */
  tailorDBField: string;
  /** SCIM attribute path */
  scimPath: string;
};
export type SCIMAttributeMappingInput = SCIMAttributeMapping;

export type SCIMResource = {
  /** SCIM resource name */
  name: string;
  /** TailorDB namespace for the resource */
  tailorDBNamespace: string;
  /** TailorDB type name for the resource */
  tailorDBType: string;
  /** Core SCIM schema definition */
  coreSchema: {
    /** SCIM schema name */
    name: string;
    /** Schema attributes */
    attributes: {
      /** Attribute data type */
      type: "string" | "number" | "boolean" | "datetime" | "complex";
      /** Attribute name */
      name: string;
      /** Attribute description */
      description?: string | undefined;
      /** Attribute mutability */
      mutability?: "readOnly" | "readWrite" | "writeOnly" | undefined;
      /** Whether the attribute is required */
      required?: boolean | undefined;
      /** Whether the attribute can have multiple values */
      multiValued?: boolean | undefined;
      /** Uniqueness constraint */
      uniqueness?: "none" | "server" | "global" | undefined;
      /** List of canonical values */
      canonicalValues?: string[] | null | undefined;
      subAttributes?: any[] | null | undefined;
    }[];
  };
  /** Attribute mapping configuration */
  attributeMapping: SCIMAttributeMapping[];
};
export type SCIMResourceInput = SCIMResource;

export type SCIMConfig = {
  /** Machine user name for SCIM operations */
  machineUserName: string;
  /** SCIM authorization configuration */
  authorization: SCIMAuthorization;
  /** SCIM resource definitions */
  resources: SCIMResource[];
};
export type SCIMConfigInput = SCIMConfig;

export type TenantProvider = {
  /** TailorDB namespace for the tenant type */
  namespace: string;
  /** TailorDB type name for tenants */
  type: string;
  /** Field used as the tenant signature */
  signatureField: string;
};
export type TenantProviderInput = TenantProvider;

export type AuthConfigInput =
  | {
      /** Auth service name */
      name: string;
      /** Auth hooks */
      hooks?:
        | {
            /** Before login auth hook */
            beforeLogin?:
              | {
                  handler: Function;
                  invoker: string;
                }
              | undefined;
          }
        | undefined;
      /** Machine user definitions */
      machineUsers?:
        | {
            [x: string]: {
              attributes?:
                | {
                    [x: string]: unknown;
                  }
                | undefined;
              attributeList?: string[] | undefined;
            };
          }
        | undefined;
      /** OAuth2 client definitions */
      oauth2Clients?:
        | {
            [x: string]: {
              redirectURIs: (
                | `https://${string}`
                | `http://${string}`
                | `${string}:url`
                | `${string}:url/${string}`
              )[];
              description?: string | undefined;
              grantTypes?: ("authorization_code" | "refresh_token")[] | undefined;
              clientType?: "confidential" | "public" | "browser" | undefined;
              accessTokenLifetimeSeconds?: number | undefined;
              refreshTokenLifetimeSeconds?: number | undefined;
              requireDpop?: boolean | undefined;
            };
          }
        | undefined;
      /** Identity provider configuration */
      idProvider?:
        | {
            /** Identity provider name */
            name: string;
            kind: "SAML";
            /** Enable signing of SAML requests */
            enableSignRequest?: boolean | undefined;
            /** URL to fetch SAML metadata (mutually exclusive with rawMetadata) */
            metadataURL?: string | undefined;
            /** Raw SAML metadata XML (mutually exclusive with metadataURL) */
            rawMetadata?: string | undefined;
            /** URL to redirect to when SAML ACS receives a response with an empty RelayState. */
            defaultRedirectURL?: string | undefined;
          }
        | {
            /** Identity provider name */
            name: string;
            kind: "OIDC";
            /** OAuth2 client ID */
            clientID: string;
            /** OAuth2 client secret */
            clientSecret: {
              /** Vault name containing the secret */
              vaultName: string;
              /** Key of the secret in the vault */
              secretKey: string;
            };
            /** OIDC provider URL */
            providerURL: string;
            /** OIDC issuer URL (defaults to providerURL) */
            issuerURL?: string | undefined;
            /** JWT claim to use as username */
            usernameClaim?: string | undefined;
          }
        | {
            /** Identity provider name */
            name: string;
            kind: "IDToken";
            /** OIDC provider URL */
            providerURL: string;
            /** OAuth2 client ID */
            clientID: string;
            /** OIDC issuer URL (defaults to providerURL) */
            issuerURL?: string | undefined;
            /** JWT claim to use as username */
            usernameClaim?: string | undefined;
          }
        | {
            /** Identity provider name */
            name: string;
            kind: "BuiltInIdP";
            /** IdP namespace */
            namespace: string;
            /** OAuth2 client name in the IdP */
            clientName: string;
          }
        | undefined;
      /** SCIM provisioning configuration */
      scim?:
        | {
            /** Machine user name for SCIM operations */
            machineUserName: string;
            /** SCIM authorization configuration */
            authorization: {
              /** SCIM authorization type */
              type: "oauth2" | "bearer";
              /** Bearer token secret (required for bearer type) */
              bearerSecret?:
                | {
                    /** Vault name containing the secret */
                    vaultName: string;
                    /** Key of the secret in the vault */
                    secretKey: string;
                  }
                | undefined;
            };
            /** SCIM resource definitions */
            resources: {
              /** SCIM resource name */
              name: string;
              /** TailorDB namespace for the resource */
              tailorDBNamespace: string;
              /** TailorDB type name for the resource */
              tailorDBType: string;
              /** Core SCIM schema definition */
              coreSchema: {
                /** SCIM schema name */
                name: string;
                /** Schema attributes */
                attributes: {
                  /** Attribute data type */
                  type: "string" | "number" | "boolean" | "datetime" | "complex";
                  /** Attribute name */
                  name: string;
                  /** Attribute description */
                  description?: string | undefined;
                  /** Attribute mutability */
                  mutability?: "readOnly" | "readWrite" | "writeOnly" | undefined;
                  /** Whether the attribute is required */
                  required?: boolean | undefined;
                  /** Whether the attribute can have multiple values */
                  multiValued?: boolean | undefined;
                  /** Uniqueness constraint */
                  uniqueness?: "none" | "server" | "global" | undefined;
                  /** List of canonical values */
                  canonicalValues?: string[] | null | undefined;
                  subAttributes?: any[] | null | undefined;
                }[];
              };
              /** Attribute mapping configuration */
              attributeMapping: {
                /** TailorDB field name to map to */
                tailorDBField: string;
                /** SCIM attribute path */
                scimPath: string;
              }[];
            }[];
          }
        | undefined;
      /** Multi-tenant provider configuration */
      tenantProvider?:
        | {
            /** TailorDB namespace for the tenant type */
            namespace: string;
            /** TailorDB type name for tenants */
            type: string;
            /** Field used as the tenant signature */
            signatureField: string;
          }
        | undefined;
      /** Auth connection definitions for external OAuth2 providers */
      connections?:
        | {
            [x: string]: {
              type: "oauth2";
              providerUrl: string;
              issuerUrl: string;
              clientId: string;
              clientSecret: string;
              authUrl?: string | undefined;
              tokenUrl?: string | undefined;
            };
          }
        | undefined;
      /** Enable publishing session events */
      publishSessionEvents?: boolean | undefined;
      /** User profile configuration */
      userProfile?:
        | {
            type: {
              name: string;
              fields: any;
              metadata: any;
              hooks: any;
              validate: any;
              features: any;
              indexes: any;
              files: any;
              permission: any;
              gqlPermission: any;
              _output: any;
            };
            usernameField: string;
            /** TailorDB namespace where the user type is defined */
            namespace?: string | undefined;
            attributes?:
              | {
                  [x: string]: true;
                }
              | undefined;
            attributeList?: string[] | undefined;
          }
        | undefined;
      /** Machine user attribute fields */
      machineUserAttributes?: undefined;
    }
  | {
      /** Auth service name */
      name: string;
      /** Machine user attribute fields */
      machineUserAttributes: {
        [x: string]: {
          type:
            | "string"
            | "boolean"
            | "date"
            | "enum"
            | "uuid"
            | "datetime"
            | "integer"
            | "float"
            | "decimal"
            | "time"
            | "nested";
          metadata: {
            required?: boolean | undefined;
            array?: boolean | undefined;
            description?: string | undefined;
            allowedValues?:
              | {
                  value: string;
                  description?: string | undefined;
                }[]
              | undefined;
            hooks?:
              | {
                  create?: Function | undefined;
                  update?: Function | undefined;
                }
              | undefined;
            typeName?: string | undefined;
          };
          fields: any;
        };
      };
      /** Auth hooks */
      hooks?:
        | {
            /** Before login auth hook */
            beforeLogin?:
              | {
                  handler: Function;
                  invoker: string;
                }
              | undefined;
          }
        | undefined;
      /** Machine user definitions */
      machineUsers?:
        | {
            [x: string]: {
              attributes?:
                | {
                    [x: string]: unknown;
                  }
                | undefined;
              attributeList?: string[] | undefined;
            };
          }
        | undefined;
      /** OAuth2 client definitions */
      oauth2Clients?:
        | {
            [x: string]: {
              redirectURIs: (
                | `https://${string}`
                | `http://${string}`
                | `${string}:url`
                | `${string}:url/${string}`
              )[];
              description?: string | undefined;
              grantTypes?: ("authorization_code" | "refresh_token")[] | undefined;
              clientType?: "confidential" | "public" | "browser" | undefined;
              accessTokenLifetimeSeconds?: number | undefined;
              refreshTokenLifetimeSeconds?: number | undefined;
              requireDpop?: boolean | undefined;
            };
          }
        | undefined;
      /** Identity provider configuration */
      idProvider?:
        | {
            /** Identity provider name */
            name: string;
            kind: "SAML";
            /** Enable signing of SAML requests */
            enableSignRequest?: boolean | undefined;
            /** URL to fetch SAML metadata (mutually exclusive with rawMetadata) */
            metadataURL?: string | undefined;
            /** Raw SAML metadata XML (mutually exclusive with metadataURL) */
            rawMetadata?: string | undefined;
            /** URL to redirect to when SAML ACS receives a response with an empty RelayState. */
            defaultRedirectURL?: string | undefined;
          }
        | {
            /** Identity provider name */
            name: string;
            kind: "OIDC";
            /** OAuth2 client ID */
            clientID: string;
            /** OAuth2 client secret */
            clientSecret: {
              /** Vault name containing the secret */
              vaultName: string;
              /** Key of the secret in the vault */
              secretKey: string;
            };
            /** OIDC provider URL */
            providerURL: string;
            /** OIDC issuer URL (defaults to providerURL) */
            issuerURL?: string | undefined;
            /** JWT claim to use as username */
            usernameClaim?: string | undefined;
          }
        | {
            /** Identity provider name */
            name: string;
            kind: "IDToken";
            /** OIDC provider URL */
            providerURL: string;
            /** OAuth2 client ID */
            clientID: string;
            /** OIDC issuer URL (defaults to providerURL) */
            issuerURL?: string | undefined;
            /** JWT claim to use as username */
            usernameClaim?: string | undefined;
          }
        | {
            /** Identity provider name */
            name: string;
            kind: "BuiltInIdP";
            /** IdP namespace */
            namespace: string;
            /** OAuth2 client name in the IdP */
            clientName: string;
          }
        | undefined;
      /** SCIM provisioning configuration */
      scim?:
        | {
            /** Machine user name for SCIM operations */
            machineUserName: string;
            /** SCIM authorization configuration */
            authorization: {
              /** SCIM authorization type */
              type: "oauth2" | "bearer";
              /** Bearer token secret (required for bearer type) */
              bearerSecret?:
                | {
                    /** Vault name containing the secret */
                    vaultName: string;
                    /** Key of the secret in the vault */
                    secretKey: string;
                  }
                | undefined;
            };
            /** SCIM resource definitions */
            resources: {
              /** SCIM resource name */
              name: string;
              /** TailorDB namespace for the resource */
              tailorDBNamespace: string;
              /** TailorDB type name for the resource */
              tailorDBType: string;
              /** Core SCIM schema definition */
              coreSchema: {
                /** SCIM schema name */
                name: string;
                /** Schema attributes */
                attributes: {
                  /** Attribute data type */
                  type: "string" | "number" | "boolean" | "datetime" | "complex";
                  /** Attribute name */
                  name: string;
                  /** Attribute description */
                  description?: string | undefined;
                  /** Attribute mutability */
                  mutability?: "readOnly" | "readWrite" | "writeOnly" | undefined;
                  /** Whether the attribute is required */
                  required?: boolean | undefined;
                  /** Whether the attribute can have multiple values */
                  multiValued?: boolean | undefined;
                  /** Uniqueness constraint */
                  uniqueness?: "none" | "server" | "global" | undefined;
                  /** List of canonical values */
                  canonicalValues?: string[] | null | undefined;
                  subAttributes?: any[] | null | undefined;
                }[];
              };
              /** Attribute mapping configuration */
              attributeMapping: {
                /** TailorDB field name to map to */
                tailorDBField: string;
                /** SCIM attribute path */
                scimPath: string;
              }[];
            }[];
          }
        | undefined;
      /** Multi-tenant provider configuration */
      tenantProvider?:
        | {
            /** TailorDB namespace for the tenant type */
            namespace: string;
            /** TailorDB type name for tenants */
            type: string;
            /** Field used as the tenant signature */
            signatureField: string;
          }
        | undefined;
      /** Auth connection definitions for external OAuth2 providers */
      connections?:
        | {
            [x: string]: {
              type: "oauth2";
              providerUrl: string;
              issuerUrl: string;
              clientId: string;
              clientSecret: string;
              authUrl?: string | undefined;
              tokenUrl?: string | undefined;
            };
          }
        | undefined;
      /** Enable publishing session events */
      publishSessionEvents?: boolean | undefined;
      /** User profile configuration */
      userProfile?: undefined;
    };

export type AuthConfig =
  | {
      /** Auth service name */
      name: string;
      /** Auth hooks */
      hooks?:
        | {
            /** Before login auth hook */
            beforeLogin?:
              | {
                  handler: Function;
                  invoker: string;
                }
              | undefined;
          }
        | undefined;
      /** Machine user definitions */
      machineUsers?:
        | {
            [x: string]: {
              attributes?:
                | {
                    [x: string]: string | boolean | string[] | boolean[];
                  }
                | undefined;
              attributeList?: string[] | undefined;
            };
          }
        | undefined;
      /** OAuth2 client definitions */
      oauth2Clients?:
        | {
            [x: string]: {
              grantTypes: ("authorization_code" | "refresh_token")[];
              redirectURIs: (
                | `https://${string}`
                | `http://${string}`
                | `${string}:url`
                | `${string}:url/${string}`
              )[];
              accessTokenLifetimeSeconds:
                | {
                    seconds: bigint;
                    nanos: number;
                  }
                | undefined;
              refreshTokenLifetimeSeconds:
                | {
                    seconds: bigint;
                    nanos: number;
                  }
                | undefined;
              description?: string | undefined;
              clientType?: "confidential" | "public" | "browser" | undefined;
              requireDpop?: boolean | undefined;
            };
          }
        | undefined;
      /** Identity provider configuration */
      idProvider?:
        | {
            /** Identity provider name */
            name: string;
            kind: "SAML";
            /** Enable signing of SAML requests */
            enableSignRequest: boolean;
            /** URL to fetch SAML metadata (mutually exclusive with rawMetadata) */
            metadataURL?: string | undefined;
            /** Raw SAML metadata XML (mutually exclusive with metadataURL) */
            rawMetadata?: string | undefined;
            /** URL to redirect to when SAML ACS receives a response with an empty RelayState. */
            defaultRedirectURL?: string | undefined;
          }
        | {
            /** Identity provider name */
            name: string;
            kind: "OIDC";
            /** OAuth2 client ID */
            clientID: string;
            /** OAuth2 client secret */
            clientSecret: {
              /** Vault name containing the secret */
              vaultName: string;
              /** Key of the secret in the vault */
              secretKey: string;
            };
            /** OIDC provider URL */
            providerURL: string;
            /** OIDC issuer URL (defaults to providerURL) */
            issuerURL?: string | undefined;
            /** JWT claim to use as username */
            usernameClaim?: string | undefined;
          }
        | {
            /** Identity provider name */
            name: string;
            kind: "IDToken";
            /** OIDC provider URL */
            providerURL: string;
            /** OAuth2 client ID */
            clientID: string;
            /** OIDC issuer URL (defaults to providerURL) */
            issuerURL?: string | undefined;
            /** JWT claim to use as username */
            usernameClaim?: string | undefined;
          }
        | {
            /** Identity provider name */
            name: string;
            kind: "BuiltInIdP";
            /** IdP namespace */
            namespace: string;
            /** OAuth2 client name in the IdP */
            clientName: string;
          }
        | undefined;
      /** SCIM provisioning configuration */
      scim?:
        | {
            /** Machine user name for SCIM operations */
            machineUserName: string;
            /** SCIM authorization configuration */
            authorization: {
              /** SCIM authorization type */
              type: "oauth2" | "bearer";
              /** Bearer token secret (required for bearer type) */
              bearerSecret?:
                | {
                    /** Vault name containing the secret */
                    vaultName: string;
                    /** Key of the secret in the vault */
                    secretKey: string;
                  }
                | undefined;
            };
            /** SCIM resource definitions */
            resources: {
              /** SCIM resource name */
              name: string;
              /** TailorDB namespace for the resource */
              tailorDBNamespace: string;
              /** TailorDB type name for the resource */
              tailorDBType: string;
              /** Core SCIM schema definition */
              coreSchema: {
                /** SCIM schema name */
                name: string;
                /** Schema attributes */
                attributes: {
                  /** Attribute data type */
                  type: "string" | "number" | "boolean" | "datetime" | "complex";
                  /** Attribute name */
                  name: string;
                  /** Attribute description */
                  description?: string | undefined;
                  /** Attribute mutability */
                  mutability?: "readOnly" | "readWrite" | "writeOnly" | undefined;
                  /** Whether the attribute is required */
                  required?: boolean | undefined;
                  /** Whether the attribute can have multiple values */
                  multiValued?: boolean | undefined;
                  /** Uniqueness constraint */
                  uniqueness?: "none" | "server" | "global" | undefined;
                  /** List of canonical values */
                  canonicalValues?: string[] | null | undefined;
                  subAttributes?: any[] | null | undefined;
                }[];
              };
              /** Attribute mapping configuration */
              attributeMapping: {
                /** TailorDB field name to map to */
                tailorDBField: string;
                /** SCIM attribute path */
                scimPath: string;
              }[];
            }[];
          }
        | undefined;
      /** Multi-tenant provider configuration */
      tenantProvider?:
        | {
            /** TailorDB namespace for the tenant type */
            namespace: string;
            /** TailorDB type name for tenants */
            type: string;
            /** Field used as the tenant signature */
            signatureField: string;
          }
        | undefined;
      /** Auth connection definitions for external OAuth2 providers */
      connections?:
        | {
            [x: string]: {
              type: "oauth2";
              providerUrl: string;
              issuerUrl: string;
              clientId: string;
              clientSecret: string;
              authUrl?: string | undefined;
              tokenUrl?: string | undefined;
            };
          }
        | undefined;
      /** Enable publishing session events */
      publishSessionEvents?: boolean | undefined;
      /** User profile configuration */
      userProfile?:
        | {
            type: {
              name: string;
              fields: any;
              metadata: any;
              hooks: any;
              validate: any;
              features: any;
              indexes: any;
              files: any;
              permission: any;
              gqlPermission: any;
              _output: any;
            };
            usernameField: string;
            /** TailorDB namespace where the user type is defined */
            namespace?: string | undefined;
            attributes?:
              | {
                  [x: string]: true;
                }
              | undefined;
            attributeList?: string[] | undefined;
          }
        | undefined;
      /** Machine user attribute fields */
      machineUserAttributes?: undefined;
    }
  | {
      /** Auth service name */
      name: string;
      /** Machine user attribute fields */
      machineUserAttributes: {
        [x: string]: {
          type:
            | "string"
            | "boolean"
            | "date"
            | "enum"
            | "uuid"
            | "datetime"
            | "integer"
            | "float"
            | "decimal"
            | "time"
            | "nested";
          metadata: {
            required?: boolean | undefined;
            array?: boolean | undefined;
            description?: string | undefined;
            allowedValues?:
              | {
                  value: string;
                  description?: string | undefined;
                }[]
              | undefined;
            hooks?:
              | {
                  create?: Function | undefined;
                  update?: Function | undefined;
                }
              | undefined;
            typeName?: string | undefined;
          };
          fields: any;
        };
      };
      /** Auth hooks */
      hooks?:
        | {
            /** Before login auth hook */
            beforeLogin?:
              | {
                  handler: Function;
                  invoker: string;
                }
              | undefined;
          }
        | undefined;
      /** Machine user definitions */
      machineUsers?:
        | {
            [x: string]: {
              attributes?:
                | {
                    [x: string]: string | boolean | string[] | boolean[];
                  }
                | undefined;
              attributeList?: string[] | undefined;
            };
          }
        | undefined;
      /** OAuth2 client definitions */
      oauth2Clients?:
        | {
            [x: string]: {
              grantTypes: ("authorization_code" | "refresh_token")[];
              redirectURIs: (
                | `https://${string}`
                | `http://${string}`
                | `${string}:url`
                | `${string}:url/${string}`
              )[];
              accessTokenLifetimeSeconds:
                | {
                    seconds: bigint;
                    nanos: number;
                  }
                | undefined;
              refreshTokenLifetimeSeconds:
                | {
                    seconds: bigint;
                    nanos: number;
                  }
                | undefined;
              description?: string | undefined;
              clientType?: "confidential" | "public" | "browser" | undefined;
              requireDpop?: boolean | undefined;
            };
          }
        | undefined;
      /** Identity provider configuration */
      idProvider?:
        | {
            /** Identity provider name */
            name: string;
            kind: "SAML";
            /** Enable signing of SAML requests */
            enableSignRequest: boolean;
            /** URL to fetch SAML metadata (mutually exclusive with rawMetadata) */
            metadataURL?: string | undefined;
            /** Raw SAML metadata XML (mutually exclusive with metadataURL) */
            rawMetadata?: string | undefined;
            /** URL to redirect to when SAML ACS receives a response with an empty RelayState. */
            defaultRedirectURL?: string | undefined;
          }
        | {
            /** Identity provider name */
            name: string;
            kind: "OIDC";
            /** OAuth2 client ID */
            clientID: string;
            /** OAuth2 client secret */
            clientSecret: {
              /** Vault name containing the secret */
              vaultName: string;
              /** Key of the secret in the vault */
              secretKey: string;
            };
            /** OIDC provider URL */
            providerURL: string;
            /** OIDC issuer URL (defaults to providerURL) */
            issuerURL?: string | undefined;
            /** JWT claim to use as username */
            usernameClaim?: string | undefined;
          }
        | {
            /** Identity provider name */
            name: string;
            kind: "IDToken";
            /** OIDC provider URL */
            providerURL: string;
            /** OAuth2 client ID */
            clientID: string;
            /** OIDC issuer URL (defaults to providerURL) */
            issuerURL?: string | undefined;
            /** JWT claim to use as username */
            usernameClaim?: string | undefined;
          }
        | {
            /** Identity provider name */
            name: string;
            kind: "BuiltInIdP";
            /** IdP namespace */
            namespace: string;
            /** OAuth2 client name in the IdP */
            clientName: string;
          }
        | undefined;
      /** SCIM provisioning configuration */
      scim?:
        | {
            /** Machine user name for SCIM operations */
            machineUserName: string;
            /** SCIM authorization configuration */
            authorization: {
              /** SCIM authorization type */
              type: "oauth2" | "bearer";
              /** Bearer token secret (required for bearer type) */
              bearerSecret?:
                | {
                    /** Vault name containing the secret */
                    vaultName: string;
                    /** Key of the secret in the vault */
                    secretKey: string;
                  }
                | undefined;
            };
            /** SCIM resource definitions */
            resources: {
              /** SCIM resource name */
              name: string;
              /** TailorDB namespace for the resource */
              tailorDBNamespace: string;
              /** TailorDB type name for the resource */
              tailorDBType: string;
              /** Core SCIM schema definition */
              coreSchema: {
                /** SCIM schema name */
                name: string;
                /** Schema attributes */
                attributes: {
                  /** Attribute data type */
                  type: "string" | "number" | "boolean" | "datetime" | "complex";
                  /** Attribute name */
                  name: string;
                  /** Attribute description */
                  description?: string | undefined;
                  /** Attribute mutability */
                  mutability?: "readOnly" | "readWrite" | "writeOnly" | undefined;
                  /** Whether the attribute is required */
                  required?: boolean | undefined;
                  /** Whether the attribute can have multiple values */
                  multiValued?: boolean | undefined;
                  /** Uniqueness constraint */
                  uniqueness?: "none" | "server" | "global" | undefined;
                  /** List of canonical values */
                  canonicalValues?: string[] | null | undefined;
                  subAttributes?: any[] | null | undefined;
                }[];
              };
              /** Attribute mapping configuration */
              attributeMapping: {
                /** TailorDB field name to map to */
                tailorDBField: string;
                /** SCIM attribute path */
                scimPath: string;
              }[];
            }[];
          }
        | undefined;
      /** Multi-tenant provider configuration */
      tenantProvider?:
        | {
            /** TailorDB namespace for the tenant type */
            namespace: string;
            /** TailorDB type name for tenants */
            type: string;
            /** Field used as the tenant signature */
            signatureField: string;
          }
        | undefined;
      /** Auth connection definitions for external OAuth2 providers */
      connections?:
        | {
            [x: string]: {
              type: "oauth2";
              providerUrl: string;
              issuerUrl: string;
              clientId: string;
              clientSecret: string;
              authUrl?: string | undefined;
              tokenUrl?: string | undefined;
            };
          }
        | undefined;
      /** Enable publishing session events */
      publishSessionEvents?: boolean | undefined;
      /** User profile configuration */
      userProfile?: undefined;
    };
