// Generated by zinfer - Do not edit manually

export type AuthInvoker = {
  /** Auth namespace */
  namespace: string;
  /** Machine user name for authentication */
  machineUserName: string;
};
export type AuthInvokerInput = AuthInvoker;

export type OIDC = {
  /** Identity provider name */
  name: string;
  kind: "OIDC";
  /** OAuth2 client ID */
  clientID: string;
  /** OAuth2 client secret */
  clientSecret: {
    vaultName: string;
    secretKey: string;
  };
  /** OIDC provider URL */
  providerURL: string;
  /** OIDC issuer URL (defaults to providerURL) */
  issuerURL?: string | undefined;
  /** JWT claim to use as username */
  usernameClaim?: string | undefined;
};
export type OIDCInput = OIDC;

export type SAMLInput = {
  /** Identity provider name */
  name: string;
  kind: "SAML";
  /** Enable signing of SAML requests */
  enableSignRequest?: boolean | undefined;
  /** URL to fetch SAML metadata (mutually exclusive with rawMetadata) */
  metadataURL?: string | undefined;
  /** Raw SAML metadata XML (mutually exclusive with metadataURL) */
  rawMetadata?: string | undefined;
  /** URL to redirect to when SAML ACS receives a response with an empty RelayState. This allows applications to handle the situation on their own, for example by initiating a standard SP-initiated login flow. */
  defaultRedirectURL?: string | undefined;
};

export type SAML = {
  /** Identity provider name */
  name: string;
  kind: "SAML";
  /** Enable signing of SAML requests */
  enableSignRequest: boolean;
  /** URL to fetch SAML metadata (mutually exclusive with rawMetadata) */
  metadataURL?: string | undefined;
  /** Raw SAML metadata XML (mutually exclusive with metadataURL) */
  rawMetadata?: string | undefined;
  /** URL to redirect to when SAML ACS receives a response with an empty RelayState. This allows applications to handle the situation on their own, for example by initiating a standard SP-initiated login flow. */
  defaultRedirectURL?: string | undefined;
};

export type IDToken = {
  /** Identity provider name */
  name: string;
  kind: "IDToken";
  /** ID token provider URL */
  providerURL: string;
  /** Client ID for ID token validation */
  clientID: string;
  /** ID token issuer URL */
  issuerURL?: string | undefined;
  /** JWT claim to use as username */
  usernameClaim?: string | undefined;
};
export type IDTokenInput = IDToken;

export type BuiltinIdP = {
  /** Identity provider name */
  name: string;
  kind: "BuiltInIdP";
  /** IdP namespace */
  namespace: string;
  /** OAuth2 client name in the IdP */
  clientName: string;
};
export type BuiltinIdPInput = BuiltinIdP;

export type IdProviderInput = OIDC | SAMLInput | IDToken | BuiltinIdP;

export type IdProvider = OIDC | SAML | IDToken | BuiltinIdP;

export type OAuth2ClientInput = {
  /** Allowed redirect URIs */
  redirectURIs: (
    | `https://${string}`
    | `http://${string}`
    | `${string}:url`
    | `${string}:url/${string}`
  )[];
  /** Client description */
  description?: string | undefined;
  /** Allowed OAuth2 grant types */
  grantTypes?: ("authorization_code" | "refresh_token")[] | undefined;
  /** OAuth2 client type */
  clientType?: "confidential" | "public" | "browser" | undefined;
  /** Access token lifetime in seconds (60-86400) */
  accessTokenLifetimeSeconds?: number | undefined;
  /** Refresh token lifetime in seconds (60-604800) */
  refreshTokenLifetimeSeconds?: number | undefined;
  /** Require DPoP (Demonstrating Proof-of-Possession) for token requests */
  requireDpop?: boolean | undefined;
};

export type OAuth2Client = {
  /** Allowed OAuth2 grant types */
  grantTypes: ("authorization_code" | "refresh_token")[];
  /** Allowed redirect URIs */
  redirectURIs: (
    | `https://${string}`
    | `http://${string}`
    | `${string}:url`
    | `${string}:url/${string}`
  )[];
  /** Access token lifetime in seconds (60-86400) */
  accessTokenLifetimeSeconds:
    | {
        seconds: bigint;
        nanos: number;
      }
    | undefined;
  /** Refresh token lifetime in seconds (60-604800) */
  refreshTokenLifetimeSeconds:
    | {
        seconds: bigint;
        nanos: number;
      }
    | undefined;
  /** Client description */
  description?: string | undefined;
  /** OAuth2 client type */
  clientType?: "confidential" | "public" | "browser" | undefined;
  /** Require DPoP (Demonstrating Proof-of-Possession) for token requests */
  requireDpop?: boolean | undefined;
};

export type SCIMAuthorization = {
  /** SCIM authorization type */
  type: "oauth2" | "bearer";
  /** Bearer token secret (required for bearer type) */
  bearerSecret?:
    | {
        vaultName: string;
        secretKey: string;
      }
    | undefined;
};
export type SCIMAuthorizationInput = SCIMAuthorization;

export type SCIMAttributeInput = {
  /** Attribute data type */
  type: "string" | "number" | "boolean" | "datetime" | "complex";
  /** Attribute name */
  name: string;
  /** Attribute description */
  description?: string | undefined;
  /** Attribute mutability */
  mutability?: "readOnly" | "readWrite" | "writeOnly" | undefined;
  /** Whether the attribute is required */
  required?: boolean | undefined;
  /** Whether the attribute can have multiple values */
  multiValued?: boolean | undefined;
  /** Uniqueness constraint */
  uniqueness?: "none" | "server" | "global" | undefined;
  /** List of canonical values */
  canonicalValues?: string[] | null | undefined;
  subAttributes?: SCIMAttributeInput[] | null | undefined;
};

export type SCIMAttribute = {
  /** Attribute data type */
  type: "string" | "number" | "boolean" | "datetime" | "complex";
  /** Attribute name */
  name: string;
  /** Attribute description */
  description?: string | undefined;
  /** Attribute mutability */
  mutability?: "readOnly" | "readWrite" | "writeOnly" | undefined;
  /** Whether the attribute is required */
  required?: boolean | undefined;
  /** Whether the attribute can have multiple values */
  multiValued?: boolean | undefined;
  /** Uniqueness constraint */
  uniqueness?: "none" | "server" | "global" | undefined;
  /** List of canonical values */
  canonicalValues?: string[] | null | undefined;
  subAttributes?: SCIMAttribute[] | null | undefined;
};

export type SCIMAttributeMapping = {
  /** TailorDB field name to map to */
  tailorDBField: string;
  /** SCIM attribute path */
  scimPath: string;
};
export type SCIMAttributeMappingInput = SCIMAttributeMapping;

export type SCIMResource = {
  /** SCIM resource name */
  name: string;
  /** TailorDB namespace for the resource */
  tailorDBNamespace: string;
  /** TailorDB type name for the resource */
  tailorDBType: string;
  /** Core SCIM schema definition */
  coreSchema: {
    /** SCIM resource name */
    name: string;
    attributes: {
      type: "string" | "number" | "boolean" | "datetime" | "complex";
      /** SCIM resource name */
      name: string;
      description?: string | undefined;
      mutability?: "readOnly" | "readWrite" | "writeOnly" | undefined;
      required?: boolean | undefined;
      multiValued?: boolean | undefined;
      uniqueness?: "none" | "server" | "global" | undefined;
      canonicalValues?: string[] | null | undefined;
      subAttributes?: any[] | null | undefined;
    }[];
  };
  /** Attribute mapping configuration */
  attributeMapping: {
    tailorDBField: string;
    scimPath: string;
  }[];
};
export type SCIMResourceInput = SCIMResource;

export type SCIMConfig = {
  /** Machine user name for SCIM operations */
  machineUserName: string;
  /** SCIM authorization configuration */
  authorization: {
    type: "oauth2" | "bearer";
    bearerSecret?:
      | {
          vaultName: string;
          secretKey: string;
        }
      | undefined;
  };
  /** SCIM resource definitions */
  resources: {
    name: string;
    tailorDBNamespace: string;
    tailorDBType: string;
    coreSchema: {
      name: string;
      attributes: {
        type: "string" | "number" | "boolean" | "datetime" | "complex";
        name: string;
        description?: string | undefined;
        mutability?: "readOnly" | "readWrite" | "writeOnly" | undefined;
        required?: boolean | undefined;
        multiValued?: boolean | undefined;
        uniqueness?: "none" | "server" | "global" | undefined;
        canonicalValues?: string[] | null | undefined;
        subAttributes?: any[] | null | undefined;
      }[];
    };
    attributeMapping: {
      tailorDBField: string;
      scimPath: string;
    }[];
  }[];
};
export type SCIMConfigInput = SCIMConfig;

export type TenantProvider = {
  /** TailorDB namespace for the tenant type */
  namespace: string;
  /** TailorDB type name for tenants */
  type: string;
  /** Field used as the tenant signature */
  signatureField: string;
};
export type TenantProviderInput = TenantProvider;

export type AuthConfigInput =
  | {
      name: string;
      hooks?:
        | {
            beforeLogin?:
              | {
                  handler: Function;
                  invoker: string;
                }
              | undefined;
          }
        | undefined;
      machineUsers?:
        | {
            [x: string]: {
              attributes?:
                | {
                    [x: string]: unknown;
                  }
                | undefined;
              attributeList?: string[] | undefined;
            };
          }
        | undefined;
      oauth2Clients?:
        | {
            [x: string]: {
              redirectURIs: (
                | `https://${string}`
                | `http://${string}`
                | `${string}:url`
                | `${string}:url/${string}`
              )[];
              description?: string | undefined;
              grantTypes?: ("authorization_code" | "refresh_token")[] | undefined;
              clientType?: "confidential" | "public" | "browser" | undefined;
              accessTokenLifetimeSeconds?: number | undefined;
              refreshTokenLifetimeSeconds?: number | undefined;
              requireDpop?: boolean | undefined;
            };
          }
        | undefined;
      idProvider?:
        | {
            name: string;
            kind: "SAML";
            enableSignRequest?: boolean | undefined;
            metadataURL?: string | undefined;
            rawMetadata?: string | undefined;
            defaultRedirectURL?: string | undefined;
          }
        | {
            name: string;
            kind: "OIDC";
            clientID: string;
            clientSecret: {
              vaultName: string;
              secretKey: string;
            };
            providerURL: string;
            issuerURL?: string | undefined;
            usernameClaim?: string | undefined;
          }
        | {
            name: string;
            kind: "IDToken";
            providerURL: string;
            clientID: string;
            issuerURL?: string | undefined;
            usernameClaim?: string | undefined;
          }
        | {
            name: string;
            kind: "BuiltInIdP";
            namespace: string;
            clientName: string;
          }
        | undefined;
      scim?:
        | {
            machineUserName: string;
            authorization: {
              type: "oauth2" | "bearer";
              bearerSecret?:
                | {
                    vaultName: string;
                    secretKey: string;
                  }
                | undefined;
            };
            resources: {
              name: string;
              tailorDBNamespace: string;
              tailorDBType: string;
              coreSchema: {
                name: string;
                attributes: {
                  type: "string" | "number" | "boolean" | "datetime" | "complex";
                  name: string;
                  description?: string | undefined;
                  mutability?: "readOnly" | "readWrite" | "writeOnly" | undefined;
                  required?: boolean | undefined;
                  multiValued?: boolean | undefined;
                  uniqueness?: "none" | "server" | "global" | undefined;
                  canonicalValues?: string[] | null | undefined;
                  subAttributes?: any[] | null | undefined;
                }[];
              };
              attributeMapping: {
                tailorDBField: string;
                scimPath: string;
              }[];
            }[];
          }
        | undefined;
      tenantProvider?:
        | {
            namespace: string;
            type: string;
            signatureField: string;
          }
        | undefined;
      connections?:
        | {
            [x: string]: {
              type: "oauth2";
              providerUrl: string;
              issuerUrl: string;
              clientId: string;
              clientSecret: string;
              authUrl?: string | undefined;
              tokenUrl?: string | undefined;
            };
          }
        | undefined;
      publishSessionEvents?: boolean | undefined;
      userProfile?: undefined;
      machineUserAttributes?: undefined;
    }
  | {
      name: string;
      userProfile: {
        type: {
          name: string;
          fields: any;
          metadata: any;
          hooks: any;
          validate: any;
          features: any;
          indexes: any;
          files: any;
          permission: any;
          gqlPermission: any;
          _output: any;
        };
        usernameField: string;
        attributes?:
          | {
              [x: string]: true;
            }
          | undefined;
        attributeList?: string[] | undefined;
      };
      hooks?:
        | {
            beforeLogin?:
              | {
                  handler: Function;
                  invoker: string;
                }
              | undefined;
          }
        | undefined;
      machineUsers?:
        | {
            [x: string]: {
              attributes?:
                | {
                    [x: string]: unknown;
                  }
                | undefined;
              attributeList?: string[] | undefined;
            };
          }
        | undefined;
      oauth2Clients?:
        | {
            [x: string]: {
              redirectURIs: (
                | `https://${string}`
                | `http://${string}`
                | `${string}:url`
                | `${string}:url/${string}`
              )[];
              description?: string | undefined;
              grantTypes?: ("authorization_code" | "refresh_token")[] | undefined;
              clientType?: "confidential" | "public" | "browser" | undefined;
              accessTokenLifetimeSeconds?: number | undefined;
              refreshTokenLifetimeSeconds?: number | undefined;
              requireDpop?: boolean | undefined;
            };
          }
        | undefined;
      idProvider?:
        | {
            name: string;
            kind: "SAML";
            enableSignRequest?: boolean | undefined;
            metadataURL?: string | undefined;
            rawMetadata?: string | undefined;
            defaultRedirectURL?: string | undefined;
          }
        | {
            name: string;
            kind: "OIDC";
            clientID: string;
            clientSecret: {
              vaultName: string;
              secretKey: string;
            };
            providerURL: string;
            issuerURL?: string | undefined;
            usernameClaim?: string | undefined;
          }
        | {
            name: string;
            kind: "IDToken";
            providerURL: string;
            clientID: string;
            issuerURL?: string | undefined;
            usernameClaim?: string | undefined;
          }
        | {
            name: string;
            kind: "BuiltInIdP";
            namespace: string;
            clientName: string;
          }
        | undefined;
      scim?:
        | {
            machineUserName: string;
            authorization: {
              type: "oauth2" | "bearer";
              bearerSecret?:
                | {
                    vaultName: string;
                    secretKey: string;
                  }
                | undefined;
            };
            resources: {
              name: string;
              tailorDBNamespace: string;
              tailorDBType: string;
              coreSchema: {
                name: string;
                attributes: {
                  type: "string" | "number" | "boolean" | "datetime" | "complex";
                  name: string;
                  description?: string | undefined;
                  mutability?: "readOnly" | "readWrite" | "writeOnly" | undefined;
                  required?: boolean | undefined;
                  multiValued?: boolean | undefined;
                  uniqueness?: "none" | "server" | "global" | undefined;
                  canonicalValues?: string[] | null | undefined;
                  subAttributes?: any[] | null | undefined;
                }[];
              };
              attributeMapping: {
                tailorDBField: string;
                scimPath: string;
              }[];
            }[];
          }
        | undefined;
      tenantProvider?:
        | {
            namespace: string;
            type: string;
            signatureField: string;
          }
        | undefined;
      connections?:
        | {
            [x: string]: {
              type: "oauth2";
              providerUrl: string;
              issuerUrl: string;
              clientId: string;
              clientSecret: string;
              authUrl?: string | undefined;
              tokenUrl?: string | undefined;
            };
          }
        | undefined;
      publishSessionEvents?: boolean | undefined;
      machineUserAttributes?: undefined;
    }
  | {
      name: string;
      machineUserAttributes: {
        [x: string]: {
          type:
            | "string"
            | "boolean"
            | "date"
            | "enum"
            | "uuid"
            | "datetime"
            | "integer"
            | "float"
            | "decimal"
            | "time"
            | "nested";
          metadata: {
            required?: boolean | undefined;
            array?: boolean | undefined;
            description?: string | undefined;
            allowedValues?:
              | {
                  value: string;
                  description?: string | undefined;
                }[]
              | undefined;
            hooks?:
              | {
                  create?: Function | undefined;
                  update?: Function | undefined;
                }
              | undefined;
            typeName?: string | undefined;
          };
          fields: any;
        };
      };
      hooks?:
        | {
            beforeLogin?:
              | {
                  handler: Function;
                  invoker: string;
                }
              | undefined;
          }
        | undefined;
      machineUsers?:
        | {
            [x: string]: {
              attributes?:
                | {
                    [x: string]: unknown;
                  }
                | undefined;
              attributeList?: string[] | undefined;
            };
          }
        | undefined;
      oauth2Clients?:
        | {
            [x: string]: {
              redirectURIs: (
                | `https://${string}`
                | `http://${string}`
                | `${string}:url`
                | `${string}:url/${string}`
              )[];
              description?: string | undefined;
              grantTypes?: ("authorization_code" | "refresh_token")[] | undefined;
              clientType?: "confidential" | "public" | "browser" | undefined;
              accessTokenLifetimeSeconds?: number | undefined;
              refreshTokenLifetimeSeconds?: number | undefined;
              requireDpop?: boolean | undefined;
            };
          }
        | undefined;
      idProvider?:
        | {
            name: string;
            kind: "SAML";
            enableSignRequest?: boolean | undefined;
            metadataURL?: string | undefined;
            rawMetadata?: string | undefined;
            defaultRedirectURL?: string | undefined;
          }
        | {
            name: string;
            kind: "OIDC";
            clientID: string;
            clientSecret: {
              vaultName: string;
              secretKey: string;
            };
            providerURL: string;
            issuerURL?: string | undefined;
            usernameClaim?: string | undefined;
          }
        | {
            name: string;
            kind: "IDToken";
            providerURL: string;
            clientID: string;
            issuerURL?: string | undefined;
            usernameClaim?: string | undefined;
          }
        | {
            name: string;
            kind: "BuiltInIdP";
            namespace: string;
            clientName: string;
          }
        | undefined;
      scim?:
        | {
            machineUserName: string;
            authorization: {
              type: "oauth2" | "bearer";
              bearerSecret?:
                | {
                    vaultName: string;
                    secretKey: string;
                  }
                | undefined;
            };
            resources: {
              name: string;
              tailorDBNamespace: string;
              tailorDBType: string;
              coreSchema: {
                name: string;
                attributes: {
                  type: "string" | "number" | "boolean" | "datetime" | "complex";
                  name: string;
                  description?: string | undefined;
                  mutability?: "readOnly" | "readWrite" | "writeOnly" | undefined;
                  required?: boolean | undefined;
                  multiValued?: boolean | undefined;
                  uniqueness?: "none" | "server" | "global" | undefined;
                  canonicalValues?: string[] | null | undefined;
                  subAttributes?: any[] | null | undefined;
                }[];
              };
              attributeMapping: {
                tailorDBField: string;
                scimPath: string;
              }[];
            }[];
          }
        | undefined;
      tenantProvider?:
        | {
            namespace: string;
            type: string;
            signatureField: string;
          }
        | undefined;
      connections?:
        | {
            [x: string]: {
              type: "oauth2";
              providerUrl: string;
              issuerUrl: string;
              clientId: string;
              clientSecret: string;
              authUrl?: string | undefined;
              tokenUrl?: string | undefined;
            };
          }
        | undefined;
      publishSessionEvents?: boolean | undefined;
      userProfile?: undefined;
    };

export type AuthConfig =
  | {
      name: string;
      hooks?:
        | {
            beforeLogin?:
              | {
                  handler: Function;
                  invoker: string;
                }
              | undefined;
          }
        | undefined;
      machineUsers?:
        | {
            [x: string]: {
              attributes?:
                | {
                    [x: string]: string | boolean | string[] | boolean[];
                  }
                | undefined;
              attributeList?: string[] | undefined;
            };
          }
        | undefined;
      oauth2Clients?:
        | {
            [x: string]: {
              grantTypes: ("authorization_code" | "refresh_token")[];
              redirectURIs: (
                | `https://${string}`
                | `http://${string}`
                | `${string}:url`
                | `${string}:url/${string}`
              )[];
              accessTokenLifetimeSeconds:
                | {
                    seconds: bigint;
                    nanos: number;
                  }
                | undefined;
              refreshTokenLifetimeSeconds:
                | {
                    seconds: bigint;
                    nanos: number;
                  }
                | undefined;
              description?: string | undefined;
              clientType?: "confidential" | "public" | "browser" | undefined;
              requireDpop?: boolean | undefined;
            };
          }
        | undefined;
      idProvider?:
        | {
            name: string;
            kind: "SAML";
            enableSignRequest: boolean;
            metadataURL?: string | undefined;
            rawMetadata?: string | undefined;
            defaultRedirectURL?: string | undefined;
          }
        | {
            name: string;
            kind: "OIDC";
            clientID: string;
            clientSecret: {
              vaultName: string;
              secretKey: string;
            };
            providerURL: string;
            issuerURL?: string | undefined;
            usernameClaim?: string | undefined;
          }
        | {
            name: string;
            kind: "IDToken";
            providerURL: string;
            clientID: string;
            issuerURL?: string | undefined;
            usernameClaim?: string | undefined;
          }
        | {
            name: string;
            kind: "BuiltInIdP";
            namespace: string;
            clientName: string;
          }
        | undefined;
      scim?:
        | {
            machineUserName: string;
            authorization: {
              type: "oauth2" | "bearer";
              bearerSecret?:
                | {
                    vaultName: string;
                    secretKey: string;
                  }
                | undefined;
            };
            resources: {
              name: string;
              tailorDBNamespace: string;
              tailorDBType: string;
              coreSchema: {
                name: string;
                attributes: {
                  type: "string" | "number" | "boolean" | "datetime" | "complex";
                  name: string;
                  description?: string | undefined;
                  mutability?: "readOnly" | "readWrite" | "writeOnly" | undefined;
                  required?: boolean | undefined;
                  multiValued?: boolean | undefined;
                  uniqueness?: "none" | "server" | "global" | undefined;
                  canonicalValues?: string[] | null | undefined;
                  subAttributes?: any[] | null | undefined;
                }[];
              };
              attributeMapping: {
                tailorDBField: string;
                scimPath: string;
              }[];
            }[];
          }
        | undefined;
      tenantProvider?:
        | {
            namespace: string;
            type: string;
            signatureField: string;
          }
        | undefined;
      connections?:
        | {
            [x: string]: {
              type: "oauth2";
              providerUrl: string;
              issuerUrl: string;
              clientId: string;
              clientSecret: string;
              authUrl?: string | undefined;
              tokenUrl?: string | undefined;
            };
          }
        | undefined;
      publishSessionEvents?: boolean | undefined;
      userProfile?: undefined;
      machineUserAttributes?: undefined;
    }
  | {
      name: string;
      userProfile: {
        type: {
          name: string;
          fields: any;
          metadata: any;
          hooks: any;
          validate: any;
          features: any;
          indexes: any;
          files: any;
          permission: any;
          gqlPermission: any;
          _output: any;
        };
        usernameField: string;
        attributes?:
          | {
              [x: string]: true;
            }
          | undefined;
        attributeList?: string[] | undefined;
      };
      hooks?:
        | {
            beforeLogin?:
              | {
                  handler: Function;
                  invoker: string;
                }
              | undefined;
          }
        | undefined;
      machineUsers?:
        | {
            [x: string]: {
              attributes?:
                | {
                    [x: string]: string | boolean | string[] | boolean[];
                  }
                | undefined;
              attributeList?: string[] | undefined;
            };
          }
        | undefined;
      oauth2Clients?:
        | {
            [x: string]: {
              grantTypes: ("authorization_code" | "refresh_token")[];
              redirectURIs: (
                | `https://${string}`
                | `http://${string}`
                | `${string}:url`
                | `${string}:url/${string}`
              )[];
              accessTokenLifetimeSeconds:
                | {
                    seconds: bigint;
                    nanos: number;
                  }
                | undefined;
              refreshTokenLifetimeSeconds:
                | {
                    seconds: bigint;
                    nanos: number;
                  }
                | undefined;
              description?: string | undefined;
              clientType?: "confidential" | "public" | "browser" | undefined;
              requireDpop?: boolean | undefined;
            };
          }
        | undefined;
      idProvider?:
        | {
            name: string;
            kind: "SAML";
            enableSignRequest: boolean;
            metadataURL?: string | undefined;
            rawMetadata?: string | undefined;
            defaultRedirectURL?: string | undefined;
          }
        | {
            name: string;
            kind: "OIDC";
            clientID: string;
            clientSecret: {
              vaultName: string;
              secretKey: string;
            };
            providerURL: string;
            issuerURL?: string | undefined;
            usernameClaim?: string | undefined;
          }
        | {
            name: string;
            kind: "IDToken";
            providerURL: string;
            clientID: string;
            issuerURL?: string | undefined;
            usernameClaim?: string | undefined;
          }
        | {
            name: string;
            kind: "BuiltInIdP";
            namespace: string;
            clientName: string;
          }
        | undefined;
      scim?:
        | {
            machineUserName: string;
            authorization: {
              type: "oauth2" | "bearer";
              bearerSecret?:
                | {
                    vaultName: string;
                    secretKey: string;
                  }
                | undefined;
            };
            resources: {
              name: string;
              tailorDBNamespace: string;
              tailorDBType: string;
              coreSchema: {
                name: string;
                attributes: {
                  type: "string" | "number" | "boolean" | "datetime" | "complex";
                  name: string;
                  description?: string | undefined;
                  mutability?: "readOnly" | "readWrite" | "writeOnly" | undefined;
                  required?: boolean | undefined;
                  multiValued?: boolean | undefined;
                  uniqueness?: "none" | "server" | "global" | undefined;
                  canonicalValues?: string[] | null | undefined;
                  subAttributes?: any[] | null | undefined;
                }[];
              };
              attributeMapping: {
                tailorDBField: string;
                scimPath: string;
              }[];
            }[];
          }
        | undefined;
      tenantProvider?:
        | {
            namespace: string;
            type: string;
            signatureField: string;
          }
        | undefined;
      connections?:
        | {
            [x: string]: {
              type: "oauth2";
              providerUrl: string;
              issuerUrl: string;
              clientId: string;
              clientSecret: string;
              authUrl?: string | undefined;
              tokenUrl?: string | undefined;
            };
          }
        | undefined;
      publishSessionEvents?: boolean | undefined;
      machineUserAttributes?: undefined;
    }
  | {
      name: string;
      machineUserAttributes: {
        [x: string]: {
          type:
            | "string"
            | "boolean"
            | "date"
            | "enum"
            | "uuid"
            | "datetime"
            | "integer"
            | "float"
            | "decimal"
            | "time"
            | "nested";
          metadata: {
            required?: boolean | undefined;
            array?: boolean | undefined;
            description?: string | undefined;
            allowedValues?:
              | {
                  value: string;
                  description?: string | undefined;
                }[]
              | undefined;
            hooks?:
              | {
                  create?: Function | undefined;
                  update?: Function | undefined;
                }
              | undefined;
            typeName?: string | undefined;
          };
          fields: any;
        };
      };
      hooks?:
        | {
            beforeLogin?:
              | {
                  handler: Function;
                  invoker: string;
                }
              | undefined;
          }
        | undefined;
      machineUsers?:
        | {
            [x: string]: {
              attributes?:
                | {
                    [x: string]: string | boolean | string[] | boolean[];
                  }
                | undefined;
              attributeList?: string[] | undefined;
            };
          }
        | undefined;
      oauth2Clients?:
        | {
            [x: string]: {
              grantTypes: ("authorization_code" | "refresh_token")[];
              redirectURIs: (
                | `https://${string}`
                | `http://${string}`
                | `${string}:url`
                | `${string}:url/${string}`
              )[];
              accessTokenLifetimeSeconds:
                | {
                    seconds: bigint;
                    nanos: number;
                  }
                | undefined;
              refreshTokenLifetimeSeconds:
                | {
                    seconds: bigint;
                    nanos: number;
                  }
                | undefined;
              description?: string | undefined;
              clientType?: "confidential" | "public" | "browser" | undefined;
              requireDpop?: boolean | undefined;
            };
          }
        | undefined;
      idProvider?:
        | {
            name: string;
            kind: "SAML";
            enableSignRequest: boolean;
            metadataURL?: string | undefined;
            rawMetadata?: string | undefined;
            defaultRedirectURL?: string | undefined;
          }
        | {
            name: string;
            kind: "OIDC";
            clientID: string;
            clientSecret: {
              vaultName: string;
              secretKey: string;
            };
            providerURL: string;
            issuerURL?: string | undefined;
            usernameClaim?: string | undefined;
          }
        | {
            name: string;
            kind: "IDToken";
            providerURL: string;
            clientID: string;
            issuerURL?: string | undefined;
            usernameClaim?: string | undefined;
          }
        | {
            name: string;
            kind: "BuiltInIdP";
            namespace: string;
            clientName: string;
          }
        | undefined;
      scim?:
        | {
            machineUserName: string;
            authorization: {
              type: "oauth2" | "bearer";
              bearerSecret?:
                | {
                    vaultName: string;
                    secretKey: string;
                  }
                | undefined;
            };
            resources: {
              name: string;
              tailorDBNamespace: string;
              tailorDBType: string;
              coreSchema: {
                name: string;
                attributes: {
                  type: "string" | "number" | "boolean" | "datetime" | "complex";
                  name: string;
                  description?: string | undefined;
                  mutability?: "readOnly" | "readWrite" | "writeOnly" | undefined;
                  required?: boolean | undefined;
                  multiValued?: boolean | undefined;
                  uniqueness?: "none" | "server" | "global" | undefined;
                  canonicalValues?: string[] | null | undefined;
                  subAttributes?: any[] | null | undefined;
                }[];
              };
              attributeMapping: {
                tailorDBField: string;
                scimPath: string;
              }[];
            }[];
          }
        | undefined;
      tenantProvider?:
        | {
            namespace: string;
            type: string;
            signatureField: string;
          }
        | undefined;
      connections?:
        | {
            [x: string]: {
              type: "oauth2";
              providerUrl: string;
              issuerUrl: string;
              clientId: string;
              clientSecret: string;
              authUrl?: string | undefined;
              tokenUrl?: string | undefined;
            };
          }
        | undefined;
      publishSessionEvents?: boolean | undefined;
      userProfile?: undefined;
    };
