// Generated by zinfer - Do not edit manually

export type TailorDBTrigger = {
  /** TailorDB record event trigger */
  kind: "tailordb";
  /** TailorDB event types to trigger on */
  events: (
    | "tailordb.type_record.created"
    | "tailordb.type_record.updated"
    | "tailordb.type_record.deleted"
  )[];
  /** TailorDB type name to watch for events */
  typeName: string;
  /** Condition function to filter events */
  condition?: Function | undefined;
};
export type TailorDBTriggerInput = TailorDBTrigger;

export type ResolverExecutedTrigger = {
  kind: "resolverExecuted";
  /** Name of the resolver to trigger on */
  resolverName: string;
  /** Condition function to filter events */
  condition?: Function | undefined;
};
export type ResolverExecutedTriggerInput = ResolverExecutedTrigger;

export type ScheduleTriggerInput = {
  kind: "schedule";
  /** CRON expression for the schedule */
  cron: string;
  /** Timezone for the CRON schedule (default: UTC) */
  timezone?: string | undefined;
};

export type ScheduleTrigger = {
  kind: "schedule";
  /** CRON expression for the schedule */
  cron: string;
  /** Timezone for the CRON schedule (default: UTC) */
  timezone: string;
};

export type IncomingWebhookTriggerResponse = {
  /** Function returning the response body */
  body?: Function | undefined;
  /** HTTP status code for the response */
  statusCode?: number | undefined;
};
export type IncomingWebhookTriggerResponseInput = IncomingWebhookTriggerResponse;

export type IncomingWebhookTrigger = {
  kind: "incomingWebhook";
  /** Response configuration */
  response?: IncomingWebhookTriggerResponse;
};
export type IncomingWebhookTriggerInput = IncomingWebhookTrigger;

export type IdpUserTrigger = {
  /** IdP user event trigger */
  kind: "idpUser";
  /** IdP user event types to trigger on */
  events: ("idp.user.created" | "idp.user.updated" | "idp.user.deleted")[];
  /** IdP namespace name to subscribe to. If omitted, the project's only IdP is used; throws when multiple IdPs exist. */
  idp?: string | undefined;
};
export type IdpUserTriggerInput = IdpUserTrigger;

export type AuthAccessTokenTrigger = {
  /** Auth access token event trigger */
  kind: "authAccessToken";
  /** Auth access token event types to trigger on */
  events: (
    | "auth.access_token.issued"
    | "auth.access_token.refreshed"
    | "auth.access_token.revoked"
  )[];
};
export type AuthAccessTokenTriggerInput = AuthAccessTokenTrigger;

export type WorkflowExecutionTrigger = {
  /** Workflow execution event trigger */
  kind: "workflowExecution";
  /** Workflow execution event types to trigger on */
  events: (
    | "workflow.workflow_execution.started"
    | "workflow.workflow_execution.completed"
    | "workflow.workflow_execution.retried"
    | "workflow.workflow_execution.resumed"
    | "workflow.workflow_execution.wait_started"
    | "workflow.workflow_execution.wait_resolved"
  )[];
  /** Workflow name to subscribe to. */
  workflowName: string;
  /** Condition function to filter events */
  condition?: Function | undefined;
};
export type WorkflowExecutionTriggerInput = WorkflowExecutionTrigger;

export type WorkflowJobExecutionTrigger = {
  /** Workflow job execution event trigger */
  kind: "workflowJobExecution";
  /** Workflow job execution event types to trigger on */
  events: (
    | "workflow.workflow_execution.job_execution.started"
    | "workflow.workflow_execution.job_execution.completed"
    | "workflow.workflow_execution.job_execution.wait_started"
    | "workflow.workflow_execution.job_execution.wait_resolved"
  )[];
  /** Workflow name to subscribe to. */
  workflowName: string;
  /** Condition function to filter events */
  condition?: Function | undefined;
};
export type WorkflowJobExecutionTriggerInput = WorkflowJobExecutionTrigger;

export type TriggerInput =
  | TailorDBTrigger
  | ResolverExecutedTrigger
  | ScheduleTriggerInput
  | IncomingWebhookTrigger
  | IdpUserTrigger
  | AuthAccessTokenTrigger
  | WorkflowExecutionTrigger
  | WorkflowJobExecutionTrigger;

export type Trigger =
  | TailorDBTrigger
  | ResolverExecutedTrigger
  | ScheduleTrigger
  | IncomingWebhookTrigger
  | IdpUserTrigger
  | AuthAccessTokenTrigger
  | WorkflowExecutionTrigger
  | WorkflowJobExecutionTrigger;

export type FunctionOperation = {
  kind: "function" | "jobFunction";
  /** Function implementation */
  body: Function;
  /** Invoker for the function execution */
  invoker?:
    | string
    | {
        /** Auth namespace */
        namespace: string;
        /** Machine user name for authentication */
        machineUserName: string;
      }
    | undefined;
};
export type FunctionOperationInput = FunctionOperation;

export type GqlOperationInput = {
  kind: "graphql";
  query: unknown;
  /** Target application name for the GraphQL query */
  appName?: string | undefined;
  /** Function to compute GraphQL variables */
  variables?: Function | undefined;
  /** Invoker for the GraphQL execution */
  invoker?:
    | string
    | {
        /** Auth namespace */
        namespace: string;
        /** Machine user name for authentication */
        machineUserName: string;
      }
    | undefined;
};

export type GqlOperation = {
  kind: "graphql";
  query: string;
  /** Target application name for the GraphQL query */
  appName?: string | undefined;
  /** Function to compute GraphQL variables */
  variables?: Function | undefined;
  /** Invoker for the GraphQL execution */
  invoker?:
    | string
    | {
        /** Auth namespace */
        namespace: string;
        /** Machine user name for authentication */
        machineUserName: string;
      }
    | undefined;
};

export type WebhookOperation = {
  kind: "webhook";
  /** Function returning the webhook URL */
  url: Function;
  /** Function to compute the request body */
  requestBody?: Function | undefined;
  /** HTTP headers for the webhook request */
  headers?:
    | {
        [x: string]:
          | string
          | {
              vault: string;
              key: string;
            };
      }
    | undefined;
};
export type WebhookOperationInput = WebhookOperation;

export type JsonValueInput =
  | string
  | number
  | boolean
  | JsonValueInput[]
  | { [key: string]: JsonValueInput }
  | null;

export type JsonValue =
  | string
  | number
  | boolean
  | JsonValue[]
  | { [key: string]: JsonValue }
  | null;

export type WorkflowInput = string | number | boolean | JsonValue[] | { [key: string]: JsonValue };
export type WorkflowInputInput = WorkflowInput;

/**
 * Arguments to pass to the workflow
 */
export type WorkflowOperationArgs = WorkflowInput | Function;
export type WorkflowOperationArgsInput = WorkflowOperationArgs;

export type WorkflowOperationInput =
  | {
      workflow: {
        [x: string]: unknown;
        name: string;
      };
      kind: "workflow";
      /** Name of the workflow to execute */
      workflowName?: string | undefined;
      args?: WorkflowOperationArgs;
      /** Invoker for the workflow execution */
      invoker?:
        | string
        | {
            /** Auth namespace */
            namespace: string;
            /** Machine user name for authentication */
            machineUserName: string;
          }
        | undefined;
    }
  | {
      /** Name of the workflow to execute */
      workflowName: string;
      kind: "workflow";
      workflow?: undefined;
      args?: WorkflowOperationArgs;
      /** Invoker for the workflow execution */
      invoker?:
        | string
        | {
            /** Auth namespace */
            namespace: string;
            /** Machine user name for authentication */
            machineUserName: string;
          }
        | undefined;
    };

export type WorkflowOperation =
  | {
      /** Name of the workflow to execute */
      workflowName: string;
      kind: "workflow";
      args?: WorkflowOperationArgs;
      /** Invoker for the workflow execution */
      invoker?:
        | string
        | {
            /** Auth namespace */
            namespace: string;
            /** Machine user name for authentication */
            machineUserName: string;
          }
        | undefined;
    }
  | {
      /** Name of the workflow to execute */
      workflowName: string;
      kind: "workflow";
      workflow?: undefined;
      args?: WorkflowOperationArgs;
      /** Invoker for the workflow execution */
      invoker?:
        | string
        | {
            /** Auth namespace */
            namespace: string;
            /** Machine user name for authentication */
            machineUserName: string;
          }
        | undefined;
    };

export type OperationInput =
  | FunctionOperation
  | GqlOperationInput
  | WebhookOperation
  | WorkflowOperationInput;

export type Operation = FunctionOperation | GqlOperation | WebhookOperation | WorkflowOperation;

export type ExecutorInput = {
  /** Executor name */
  name: string;
  /** Event trigger configuration */
  trigger: TriggerInput;
  /** Operation to execute when triggered */
  operation: OperationInput;
  /** Executor description */
  description?: string | undefined;
  /** Whether the executor is disabled */
  disabled?: boolean | undefined;
};

export type Executor = {
  /** Executor name */
  name: string;
  /** Whether the executor is disabled */
  disabled: boolean;
  /** Event trigger configuration */
  trigger: Trigger;
  /** Operation to execute when triggered */
  operation: Operation;
  /** Executor description */
  description?: string | undefined;
};
