// Generated by zinfer - Do not edit manually

export type TailorFieldInput = {
  /** Field data type */
  type:
    | "string"
    | "boolean"
    | "uuid"
    | "integer"
    | "float"
    | "decimal"
    | "enum"
    | "date"
    | "datetime"
    | "time"
    | "nested";
  /** Field metadata configuration */
  metadata: {
    required?: boolean | undefined;
    array?: boolean | undefined;
    description?: string | undefined;
    allowedValues?:
      | {
          value: string;
          description?: string | undefined;
        }[]
      | undefined;
    hooks?:
      | {
          create?: Function | undefined;
          update?: Function | undefined;
        }
      | undefined;
    validate?: (Function | [Function, string])[] | undefined;
    typeName?: string | undefined;
  };
  fields: {
    [x: string]: TailorFieldInput;
  };
};

export type TailorField = {
  /** Field data type */
  type:
    | "string"
    | "boolean"
    | "uuid"
    | "integer"
    | "float"
    | "decimal"
    | "enum"
    | "date"
    | "datetime"
    | "time"
    | "nested";
  /** Field metadata configuration */
  metadata: {
    required?: boolean | undefined;
    array?: boolean | undefined;
    description?: string | undefined;
    allowedValues?:
      | {
          value: string;
          description?: string | undefined;
        }[]
      | undefined;
    hooks?:
      | {
          create?: Function | undefined;
          update?: Function | undefined;
        }
      | undefined;
    validate?: (Function | [Function, string])[] | undefined;
    typeName?: string | undefined;
  };
  fields: {
    [x: string]: TailorField;
  };
};
