// Generated by zinfer - Do not edit manually

/**
 * GraphQL operation type
 */
export type QueryType = "query" | "mutation";
export type QueryTypeInput = QueryType;

/**
 * Access requirement for this resolver, evaluated against the original caller (unaffected by `authInvoker`) before `body` runs. "allowAnonymous" documents that anonymous callers are allowed. Omitted (default): unchanged, anonymous callers can reach the resolver
 */
export type ResolverPermission =
  | "allowAnonymous"
  | readonly {
      conditions:
        | readonly [
            string | boolean | { user: string },
            "=" | "!=",
            string | boolean | { user: string },
          ]
        | readonly (readonly [
            string | boolean | { user: string },
            "=" | "!=",
            string | boolean | { user: string },
          ])[];
      permit: boolean;
      description?: string | undefined;
    }[];
export type ResolverPermissionInput = ResolverPermission;

export type Resolver = {
  /** GraphQL operation type (query or mutation) */
  operation: QueryType;
  /** Resolver name */
  name: string;
  /** Resolver implementation function */
  body: Function;
  /** Output field definition */
  output: {
    type:
      | "string"
      | "boolean"
      | "date"
      | "enum"
      | "uuid"
      | "integer"
      | "float"
      | "decimal"
      | "datetime"
      | "time"
      | "nested";
    metadata: {
      required?: boolean | undefined;
      array?: boolean | undefined;
      /** Resolver description */
      description?: string | undefined;
      allowedValues?:
        | {
            value: string;
            /** Resolver description */
            description?: string | undefined;
          }[]
        | undefined;
      hooks?:
        | {
            create?: Function | undefined;
            update?: Function | undefined;
          }
        | undefined;
      typeName?: string | undefined;
    };
    fields: {
      [x: string]: any;
    };
  };
  /** Resolver description */
  description?: string | undefined;
  /** Input field definitions */
  input?:
    | {
        [x: string]: any;
      }
    | undefined;
  /** Enable publishing events from this resolver */
  publishEvents?: boolean | undefined;
  /** Machine user to execute this resolver as */
  authInvoker?:
    | string
    | {
        namespace: string;
        machineUserName: string;
      }
    | undefined;
  permission?:
    | "allowAnonymous"
    | readonly {
        conditions:
          | readonly [
              (
                | string
                | boolean
                | {
                    user: string;
                  }
              ),
              "=" | "!=",
              (
                | string
                | boolean
                | {
                    user: string;
                  }
              ),
            ]
          | readonly (readonly [
              (
                | string
                | boolean
                | {
                    user: string;
                  }
              ),
              "=" | "!=",
              (
                | string
                | boolean
                | {
                    user: string;
                  }
              ),
            ])[];
        permit: boolean;
        /** Resolver description */
        description?: string | undefined;
      }[]
    | undefined;
};
export type ResolverInput = Resolver;
