// Generated by vinfer - Do not edit manually

/**
 * GraphQL operation type
 */
export type QueryType = "query" | "mutation";
export type QueryTypeInput = QueryType;

/**
 * Access requirement for this resolver, evaluated against the original caller (unaffected by `invoker`) before `body` runs. "allowAnonymous" documents that anonymous callers are allowed. Omitted (default): unchanged, anonymous callers can reach the resolver
 */
export type ResolverPermissionInput =
  | "allowAnonymous"
  | {
      conditions:
        | [string | boolean | { user: string }, "=" | "!=", string | boolean | { user: string }]
        | [string | boolean | { user: string }, "=" | "!=", string | boolean | { user: string }][];
      permit: boolean;
      description?: string | undefined;
    }[];

export type ResolverPermission =
  | "allowAnonymous"
  | readonly {
      conditions:
        | readonly [
            string | boolean | { user: string },
            "=" | "!=",
            string | boolean | { user: string },
          ]
        | readonly (readonly [
            string | boolean | { user: string },
            "=" | "!=",
            string | boolean | { user: string },
          ])[];
      permit: boolean;
      description?: string | undefined;
    }[];

export type ResolverInput = {
  /** GraphQL operation type (query or mutation) */
  operation: QueryType;
  /** Resolver name */
  name: string;
  /** Resolver description */
  description?: string | undefined;
  /** Input field definitions */
  input?:
    | {
        [x: string]: {
          type:
            | "string"
            | "boolean"
            | "uuid"
            | "integer"
            | "float"
            | "decimal"
            | "enum"
            | "date"
            | "datetime"
            | "time"
            | "nested";
          metadata: {
            required?: boolean | undefined;
            array?: boolean | undefined;
            description?: string | undefined;
            allowedValues?:
              | {
                  value: string;
                  description?: string | undefined;
                }[]
              | undefined;
            hooks?:
              | {
                  create?: Function | undefined;
                  update?: Function | undefined;
                }
              | undefined;
            validate?: Function[] | undefined;
            typeName?: string | undefined;
            default?: unknown;
          };
          fields: {
            [x: string]: {
              type:
                | "uuid"
                | "string"
                | "boolean"
                | "integer"
                | "float"
                | "decimal"
                | "enum"
                | "date"
                | "datetime"
                | "time"
                | "nested";
              metadata: {
                required?: boolean | undefined;
                array?: boolean | undefined;
                description?: string | undefined;
                allowedValues?:
                  | {
                      value: string;
                      description?: string | undefined;
                    }[]
                  | undefined;
                hooks?:
                  | {
                      create?: Function | undefined;
                      update?: Function | undefined;
                    }
                  | undefined;
                validate?: Function[] | undefined;
                typeName?: string | undefined;
                default?: unknown;
              };
              fields: any;
            };
          };
        };
      }
    | undefined;
  /** Resolver implementation function */
  body: Function;
  /** Output field definition */
  output: {
    /** Field data type */
    type:
      | "string"
      | "boolean"
      | "uuid"
      | "integer"
      | "float"
      | "decimal"
      | "enum"
      | "date"
      | "datetime"
      | "time"
      | "nested";
    /** Field metadata configuration */
    metadata: {
      /** Whether the field is required */
      required?: boolean | undefined;
      /** Whether the field is an array */
      array?: boolean | undefined;
      /** Field description */
      description?: string | undefined;
      /** Allowed values for enum fields */
      allowedValues?:
        | {
            /** The allowed value */
            value: string;
            /** Description of the allowed value */
            description?: string | undefined;
          }[]
        | undefined;
      /** Lifecycle hooks */
      hooks?:
        | {
            /** Hook function called on creation */
            create?: Function | undefined;
            /** Hook function called on update */
            update?: Function | undefined;
          }
        | undefined;
      /** Validation functions for the field */
      validate?: Function[] | undefined;
      /** Type name for nested or enum fields */
      typeName?: string | undefined;
      /** Default value for the field on create */
      default?: unknown;
    };
    fields: {
      [x: string]: {
        type:
          | "uuid"
          | "string"
          | "boolean"
          | "integer"
          | "float"
          | "decimal"
          | "enum"
          | "date"
          | "datetime"
          | "time"
          | "nested";
        metadata: {
          required?: boolean | undefined;
          array?: boolean | undefined;
          description?: string | undefined;
          allowedValues?:
            | {
                value: string;
                description?: string | undefined;
              }[]
            | undefined;
          hooks?:
            | {
                create?: Function | undefined;
                update?: Function | undefined;
              }
            | undefined;
          validate?: Function[] | undefined;
          typeName?: string | undefined;
          default?: unknown;
        };
        fields: any;
      };
    };
  };
  /** Enable publishing events from this resolver */
  publishEvents?: boolean | undefined;
  /** Machine user to execute this resolver as */
  invoker?:
    | string
    | {
        /** Auth namespace */
        namespace: string;
        /** Machine user name for authentication */
        machineUserName: string;
      }
    | undefined;
  /** Access requirement for this resolver, evaluated against the original caller (unaffected by `invoker`) before `body` runs. "allowAnonymous" documents that anonymous callers are allowed. Omitted (default): unchanged, anonymous callers can reach the resolver */
  permission?:
    | "allowAnonymous"
    | {
        conditions:
          | [
              (
                | string
                | boolean
                | {
                    user: string;
                  }
              ),
              "=" | "!=",
              (
                | string
                | boolean
                | {
                    user: string;
                  }
              ),
            ]
          | [
              (
                | string
                | boolean
                | {
                    user: string;
                  }
              ),
              "=" | "!=",
              (
                | string
                | boolean
                | {
                    user: string;
                  }
              ),
            ][];
        permit: boolean;
        /** Reason recorded for this policy, used in the access-denied error message */
        description?: string | undefined;
      }[]
    | undefined;
};

export type Resolver = {
  /** GraphQL operation type (query or mutation) */
  operation: QueryType;
  /** Resolver name */
  name: string;
  /** Resolver description */
  description?: string | undefined;
  /** Input field definitions */
  input?:
    | {
        [x: string]: {
          type:
            | "string"
            | "boolean"
            | "uuid"
            | "integer"
            | "float"
            | "decimal"
            | "enum"
            | "date"
            | "datetime"
            | "time"
            | "nested";
          metadata: {
            required?: boolean | undefined;
            array?: boolean | undefined;
            description?: string | undefined;
            allowedValues?:
              | {
                  value: string;
                  description?: string | undefined;
                }[]
              | undefined;
            hooks?:
              | {
                  create?: Function | undefined;
                  update?: Function | undefined;
                }
              | undefined;
            validate?: Function[] | undefined;
            typeName?: string | undefined;
            default?: unknown;
          };
          fields: {
            [x: string]: {
              type:
                | "uuid"
                | "string"
                | "boolean"
                | "integer"
                | "float"
                | "decimal"
                | "enum"
                | "date"
                | "datetime"
                | "time"
                | "nested";
              metadata: {
                required?: boolean | undefined;
                array?: boolean | undefined;
                description?: string | undefined;
                allowedValues?:
                  | {
                      value: string;
                      description?: string | undefined;
                    }[]
                  | undefined;
                hooks?:
                  | {
                      create?: Function | undefined;
                      update?: Function | undefined;
                    }
                  | undefined;
                validate?: Function[] | undefined;
                typeName?: string | undefined;
                default?: unknown;
              };
              fields: any;
            };
          };
        };
      }
    | undefined;
  /** Resolver implementation function */
  body: Function;
  /** Output field definition */
  output: {
    /** Field data type */
    type:
      | "string"
      | "boolean"
      | "uuid"
      | "integer"
      | "float"
      | "decimal"
      | "enum"
      | "date"
      | "datetime"
      | "time"
      | "nested";
    /** Field metadata configuration */
    metadata: {
      /** Whether the field is required */
      required?: boolean | undefined;
      /** Whether the field is an array */
      array?: boolean | undefined;
      /** Field description */
      description?: string | undefined;
      /** Allowed values for enum fields */
      allowedValues?:
        | {
            /** The allowed value */
            value: string;
            /** Description of the allowed value */
            description?: string | undefined;
          }[]
        | undefined;
      /** Lifecycle hooks */
      hooks?:
        | {
            /** Hook function called on creation */
            create?: Function | undefined;
            /** Hook function called on update */
            update?: Function | undefined;
          }
        | undefined;
      /** Validation functions for the field */
      validate?: Function[] | undefined;
      /** Type name for nested or enum fields */
      typeName?: string | undefined;
      /** Default value for the field on create */
      default?: unknown;
    };
    fields: {
      [x: string]: {
        type:
          | "uuid"
          | "string"
          | "boolean"
          | "integer"
          | "float"
          | "decimal"
          | "enum"
          | "date"
          | "datetime"
          | "time"
          | "nested";
        metadata: {
          required?: boolean | undefined;
          array?: boolean | undefined;
          description?: string | undefined;
          allowedValues?:
            | {
                value: string;
                description?: string | undefined;
              }[]
            | undefined;
          hooks?:
            | {
                create?: Function | undefined;
                update?: Function | undefined;
              }
            | undefined;
          validate?: Function[] | undefined;
          typeName?: string | undefined;
          default?: unknown;
        };
        fields: any;
      };
    };
  };
  /** Enable publishing events from this resolver */
  publishEvents?: boolean | undefined;
  /** Machine user to execute this resolver as */
  invoker?:
    | string
    | {
        /** Auth namespace */
        namespace: string;
        /** Machine user name for authentication */
        machineUserName: string;
      }
    | undefined;
  /** Access requirement for this resolver, evaluated against the original caller (unaffected by `invoker`) before `body` runs. "allowAnonymous" documents that anonymous callers are allowed. Omitted (default): unchanged, anonymous callers can reach the resolver */
  permission?:
    | "allowAnonymous"
    | readonly {
        conditions:
          | readonly [
              (
                | string
                | boolean
                | {
                    user: string;
                  }
              ),
              "=" | "!=",
              (
                | string
                | boolean
                | {
                    user: string;
                  }
              ),
            ]
          | readonly (readonly [
              (
                | string
                | boolean
                | {
                    user: string;
                  }
              ),
              "=" | "!=",
              (
                | string
                | boolean
                | {
                    user: string;
                  }
              ),
            ])[];
        permit: boolean;
        /** Reason recorded for this policy, used in the access-denied error message */
        description?: string | undefined;
      }[]
    | undefined;
};
