import type { ValueOperand } from "./auth";
import type { DefinedFieldMetadata, FieldMetadata, EnumValue } from "./field-types";
import type { Prettify } from "./helpers";
import type {
  DBFieldMetadata as DBFieldMetadataGenerated,
  RawPermissions,
  RawRelationConfig as RawRelationConfigGenerated,
  TailorDBServiceConfig,
  TailorDBServiceConfigInput,
  TailorDBTypeParsedSettings,
  GqlOperationsInput,
} from "./tailordb.generated";

// Re-exports from tailor-db-field (needed because parser cannot import from configure)
export type {
  TailorAnyDBField,
  TailorAnyDBType,
  TailorDBField,
  TailorDBInstance,
} from "./tailor-db-field";

export type { GqlOperations } from "./tailordb.generated";

// --- Types from configure/services/tailordb/types.ts ---

export type SerialConfig<T extends "string" | "integer" = "string" | "integer"> = Prettify<
  {
    start: number;
    maxValue?: number;
  } & (T extends "string"
    ? {
        format?: string;
      }
    : object)
>;

export interface DBFieldMetadata extends FieldMetadata {
  index?: boolean;
  unique?: boolean;
  vector?: boolean;
  foreignKey?: boolean;
  foreignKeyType?: string;
  foreignKeyField?: string;
  /** Lifecycle hooks for the field */
  hooks?: DBFieldMetadataGenerated["hooks"];
  serial?: SerialConfig;
  relation?: boolean;
  scale?: number;
}

export interface DefinedDBFieldMetadata extends DefinedFieldMetadata {
  index?: boolean;
  unique?: boolean;
  vector?: boolean;
  foreignKey?: boolean;
  foreignKeyType?: boolean;
  validate?: boolean;
  hooks?: {
    create: boolean;
    update: boolean;
  };
  serial?: boolean;
  relation?: boolean;
}

export type IndexDef<T extends { fields: Record<PropertyKey, unknown> }> = {
  fields: [keyof T["fields"], keyof T["fields"], ...(keyof T["fields"])[]];
  unique?: boolean;
  name?: string;
};

export type GqlOperationsConfig = GqlOperationsInput;

// --- Original types/tailordb.ts types ---

export type TailorDBFieldOutput = {
  type: string;
  fields?: Record<string, TailorDBFieldOutput>;
  metadata: DBFieldMetadataGenerated;
  rawRelation?: RawRelationConfigGenerated;
};

export type TypeSourceInfo = Record<string, TypeSourceInfoEntry>;

export type RelationType = "1-1" | "oneToOne" | "n-1" | "manyToOne" | "N-1" | "keyOnly";

// Service config types
export type TailorDBExternalConfig = { external: true };

export type TailorDBServiceInput = {
  [namespace: string]: TailorDBServiceConfigInput | TailorDBExternalConfig;
};

export type TailorDBMigrationConfig = NonNullable<TailorDBServiceConfig["migration"]>;

// Source info types
export interface UserDefinedTypeSource {
  filePath: string;
  exportName: string;
  pluginId?: never;
}

export interface PluginGeneratedTypeSource {
  filePath?: never;
  exportName: string;
  pluginId: string;
  pluginImportPath: string;
  originalFilePath: string;
  originalExportName: string;
  generatedTypeKind?: string;
  pluginConfig?: unknown;
  namespace?: string;
}

export type TypeSourceInfoEntry = UserDefinedTypeSource | PluginGeneratedTypeSource;

/**
 * Checks if a type source is generated by a plugin.
 * @param source - The type source entry to check.
 * @returns True if the source was generated by a plugin.
 */
export function isPluginGeneratedType(
  source: TypeSourceInfoEntry,
): source is PluginGeneratedTypeSource {
  return source.pluginId !== undefined;
}

// Operator field types
export interface Script {
  expr: string;
}

interface OperatorValidateConfig {
  script: Script;
  errorMessage: string;
}

interface OperatorFieldHook {
  create?: Script;
  update?: Script;
}

export interface RawRelationConfig {
  type: "1-1" | "n-1" | "keyOnly" | "oneToOne" | "manyToOne" | "N-1";
  toward: {
    type: string;
    as?: string;
    key?: string;
  };
  backward?: string;
}

export interface OperatorFieldConfig {
  type: string;
  required?: boolean;
  description?: string;
  allowedValues?: EnumValue[];
  array?: boolean;
  index?: boolean;
  unique?: boolean;
  vector?: boolean;
  foreignKey?: boolean;
  foreignKeyType?: string;
  foreignKeyField?: string;
  rawRelation?: RawRelationConfig;
  validate?: OperatorValidateConfig[];
  hooks?: OperatorFieldHook;
  serial?: {
    start: number;
    maxValue?: number;
    format?: string;
  };
  scale?: number;
  fields?: Record<string, OperatorFieldConfig>;
}

// Permission types (parsed/standard format)
type GqlPermissionAction = "read" | "create" | "update" | "delete" | "aggregate" | "bulkUpsert";

type StandardPermissionOperator = "eq" | "ne" | "in" | "nin" | "hasAny" | "nhasAny";

type UserOperand = {
  user: string;
};

type StandardRecordOperand<Update extends boolean = false> = Update extends true
  ? { oldRecord: string } | { newRecord: string }
  : { record: string };

export type PermissionOperand<
  Level extends "record" | "gql" = "record" | "gql",
  Update extends boolean = boolean,
> = UserOperand | ValueOperand | (Level extends "record" ? StandardRecordOperand<Update> : never);

export type StandardPermissionCondition<
  Level extends "record" | "gql" = "record" | "gql",
  Update extends boolean = boolean,
> = readonly [
  PermissionOperand<Level, Update>,
  StandardPermissionOperator,
  PermissionOperand<Level, Update>,
];

export type StandardActionPermission<
  Level extends "record" | "gql" = "record" | "gql",
  Update extends boolean = boolean,
> = {
  conditions: readonly StandardPermissionCondition<Level, Update>[];
  description?: string;
  permit: "allow" | "deny";
};

export type StandardTailorTypePermission = {
  create: readonly StandardActionPermission<"record", false>[];
  read: readonly StandardActionPermission<"record", false>[];
  update: readonly StandardActionPermission<"record", true>[];
  delete: readonly StandardActionPermission<"record", false>[];
};

export type StandardGqlPermissionPolicy = {
  conditions: readonly StandardPermissionCondition<"gql">[];
  actions: readonly ["all"] | readonly GqlPermissionAction[];
  permit: "allow" | "deny";
  description?: string;
};

export type StandardTailorTypeGqlPermission = readonly StandardGqlPermissionPolicy[];

export interface Permissions {
  record?: StandardTailorTypePermission;
  gql?: StandardTailorTypeGqlPermission;
}

// TailorDB type metadata and parsed types
export interface TailorDBTypeMetadata {
  name: string;
  description?: string;
  settings?: {
    pluralForm?: string;
    aggregation?: boolean;
    bulkUpsert?: boolean;
    gqlOperations?: GqlOperationsConfig;
    publishEvents?: boolean;
  };
  permissions: RawPermissions;
  files: Record<string, string>;
  indexes?: Record<
    string,
    {
      fields: string[];
      unique?: boolean;
    }
  >;
}

export interface ParsedField {
  name: string;
  config: OperatorFieldConfig;
  relation?: {
    targetType: string;
    forwardName: string;
    backwardName: string;
    key: string;
    unique: boolean;
  };
}

export interface ParsedRelationship {
  name: string;
  targetType: string;
  targetField: string;
  sourceField: string;
  isArray: boolean;
  description: string;
}

export interface TailorDBType {
  name: string;
  pluralForm: string;
  description?: string;
  fields: Record<string, ParsedField>;
  forwardRelationships: Record<string, ParsedRelationship>;
  backwardRelationships: Record<string, ParsedRelationship>;
  settings: TailorDBTypeParsedSettings;
  permissions: Permissions;
  indexes?: TailorDBTypeMetadata["indexes"];
  files?: TailorDBTypeMetadata["files"];
}
