// Generated by zinfer - Do not edit manually

export type WorkflowJob = {
  /** Job name (must be unique across the project) */
  name: string;
  /** Trigger function that initiates the job */
  trigger: Function;
  /** Job implementation function */
  body: Function;
};
export type WorkflowJobInput = WorkflowJob;

export type RetryPolicy = {
  /** Maximum number of retries (1-10) */
  maxRetries: number;
  /** Initial backoff duration (e.g., '1s', '500ms', '1m', max 1h) */
  initialBackoff: `${number}ms` | `${number}s` | `${number}m`;
  /** Maximum backoff duration (e.g., '30s', '5m', max 24h) */
  maxBackoff: `${number}ms` | `${number}s` | `${number}m`;
  /** Backoff multiplier (>= 1) */
  backoffMultiplier: number;
};
export type RetryPolicyInput = RetryPolicy;

export type Workflow = {
  /** Workflow name */
  name: string;
  /** Main job that starts the workflow */
  mainJob: {
    /** Workflow name */
    name: string;
    trigger: Function;
    body: Function;
  };
  /** Retry policy for the workflow */
  retryPolicy?:
    | {
        maxRetries: number;
        initialBackoff: `${number}ms` | `${number}s` | `${number}m`;
        maxBackoff: `${number}ms` | `${number}s` | `${number}m`;
        backoffMultiplier: number;
      }
    | undefined;
};
export type WorkflowInput = Workflow;
