import { existsSync } from "node:fs";
import { generateSchemaDDL, toDDLTables } from "@tailor-platform/sdk/plugin";
import { dirname, join, relative, resolve } from "pathe";
import { columnTypeOverrides } from "./overrides";
import type { GeneratorResult, Plugin } from "@tailor-platform/sdk/cli";

/** Unique identifier for the SafeQL plugin. */
export const SafeqlPluginID = "@tailor-platform/safeql";

const DEFAULT_DIST_PATH = "./generated/safeql/eslint.ts";
const DEFAULT_ESLINT_CONFIG_PATH = "./eslint.config.ts";
const ESLINT_CONFIG_FILE_NAMES = [
  "eslint.config.js",
  "eslint.config.mjs",
  "eslint.config.cjs",
  "eslint.config.ts",
  "eslint.config.mts",
  "eslint.config.cts",
];

/** Options for {@link safeqlPlugin}. */
export interface SafeqlPluginOptions {
  /** Where to write the generated ESLint config module. Defaults to `./generated/safeql/eslint.ts`. */
  distPath?: string;
  /**
   * Where to create an `eslint.config.ts` that uses the generated module. Nothing is created
   * when an ESLint config file already exists there. Defaults to `./eslint.config.ts`.
   */
  eslintConfigPath?: string;
  /** The TailorDB namespace to check SQL against. Required when several namespaces have tables. */
  namespace?: string;
  /** Files to check. Defaults to every `.ts` file. */
  files?: string[];
}

function selectNamespace<T extends { namespace: string; tables: object }>(
  namespaces: readonly T[],
  requested: string | undefined,
): T | undefined {
  const withTables = namespaces.filter(({ tables }) => Object.keys(tables).length > 0);
  const names = withTables.map(({ namespace }) => namespace).join(", ");
  if (requested !== undefined) {
    const found = withTables.find(({ namespace }) => namespace === requested);
    if (!found) {
      throw new Error(
        `safeqlPlugin: the namespace option "${requested}" matches no TailorDB namespace with tables. Available: ${names || "(none)"}.`,
      );
    }
    return found;
  }
  if (withTables.length > 1) {
    throw new Error(
      `safeqlPlugin: several TailorDB namespaces have tables (${names}); set the namespace option to choose one.`,
    );
  }
  return withTables[0];
}

function configModule(config: object): string {
  return [
    "/**",
    " * Auto-generated SafeQL config for TailorDB tables.",
    " * Spread it into eslint.config.ts: `export default [...safeql]`.",
    " *",
    " * DO NOT EDIT - This file is auto-generated by the safeql plugin.",
    " */",
    'import { tailorSafeqlConfig } from "@tailor-platform/sdk-plugin-safeql/eslint";',
    "",
    `export default tailorSafeqlConfig(${JSON.stringify(config, null, 2)});`,
    "",
  ].join("\n");
}

function eslintConfigModule(eslintConfigPath: string, distPath: string): string {
  const target = relative(dirname(resolve(eslintConfigPath)), resolve(distPath)).replace(
    /\.ts$/,
    "",
  );
  const specifier = target.startsWith(".") ? target : `./${target}`;
  return `import safeql from "${specifier}";\n\nexport default [...safeql];\n`;
}

function hasEslintConfig(eslintConfigPath: string): boolean {
  const directory = dirname(resolve(eslintConfigPath));
  return ESLINT_CONFIG_FILE_NAMES.some((name) => existsSync(join(directory, name)));
}

/**
 * Plugin that generates an ESLint config checking `sql` statements against your TailorDB tables with SafeQL.
 * @param options - Plugin options
 * @returns Plugin instance with an onTailorDBReady hook
 */
export function safeqlPlugin(
  options: SafeqlPluginOptions = {},
): Plugin<unknown, SafeqlPluginOptions> {
  return {
    id: SafeqlPluginID,
    description: "Generates an ESLint config that checks sql statements with SafeQL",
    pluginConfig: options,

    onTailorDBReady(ctx): GeneratorResult {
      const {
        distPath = DEFAULT_DIST_PATH,
        eslintConfigPath = DEFAULT_ESLINT_CONFIG_PATH,
        namespace,
        files,
      } = ctx.pluginConfig;
      const selected = selectNamespace(ctx.tailordb, namespace);
      if (!selected) return { files: [] };

      const tables = toDDLTables(selected.tables);
      const generated: GeneratorResult["files"] = [
        {
          path: distPath,
          content: configModule({
            ddl: generateSchemaDDL(tables),
            overrides: { columns: columnTypeOverrides(tables) },
            files,
          }),
        },
      ];
      if (!hasEslintConfig(eslintConfigPath)) {
        generated.push({
          path: eslintConfigPath,
          content: eslintConfigModule(eslintConfigPath, distPath),
          skipIfExists: true,
        });
      }
      return { files: generated };
    },
  };
}
