name: Check Licenses

on:
  push:
    branches: [main]
    paths:
      - "pnpm-lock.yaml"
      - ".github/workflows/check-license.yml"
  pull_request:
    paths:
      - "pnpm-lock.yaml"
      - ".github/workflows/check-license.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  check-licenses:
    name: Check licenses
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read # checkout the repository
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install deps
        uses: ./.github/actions/install-deps

      - name: Check licenses
        uses: tailor-platform/actions/check-licenses@33ae978702edd2de673419e84b66065e7a364dab # v2.3.0
        with:
          license-groups: ${{ vars.CHECK_LICENSES_ALLOWED_LICENSE_GROUPS }}
          additional-licenses: ${{ vars.CHECK_LICENSES_ALLOWED_LICENSES }}
          denied-licenses: ${{ vars.CHECK_LICENSES_DENIED_LICENSES }}
