name: Check Licenses

on:
  push:
    branches: [main]
    paths:
      - "pnpm-lock.yaml"
  pull_request:
    paths:
      - "pnpm-lock.yaml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  check-licenses:
    name: Check licenses
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read # checkout the repository
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Install deps
        uses: ./.github/actions/install-deps

      - name: Check licenses
        uses: tailor-platform/actions/check-licenses@d3040e3b5da92f72696d89db24bc9da62e0993d8 # v1.6.0
        with:
          license-groups: ${{ vars.LICENSE_GROUPS }}
          additional-licenses: ${{ vars.ALLOWED_LICENSES }}
          denied-licenses: ${{ vars.DENIED_LICENSES }}
