name: update aqua-checksums.json

on:
  pull_request:
    paths:
      - aqua.yaml
      - aqua-checksums.json

jobs:
  update-aqua-checksums:
    uses: aquaproj/update-checksum-workflow/.github/workflows/update-checksum.yaml@eba908314cdc3b2ab7fb7546950c05a666effbc0 # v1.0.5
    permissions:
      contents: read
    with:
      aqua_version: v2.59.1
      prune: true
    secrets:
      gh_app_id: ${{ secrets.TAILOR_GITHUB_APP_ID }}
      gh_app_private_key: ${{ secrets.TAILOR_GITHUB_APP_PRIVATE_KEY }}
